<?php
namespace COUPONEMAILS;

class Calendars
{	
			public function get_slovak_namedays_array()
			{
				$ndjson = '{
		 "1.1.": "Nový rok",
		 "2.1.": "Alexandra, Karina, Ábel, Makar, Karin, Kara, Kasandra, Sanda, Sandra, Saša, Senda",
		 "3.1.": "Daniela, Danila, Danuta, Genovéva, Radmila",
		 "4.1.": "Drahoslav, Drahoľub, Drahomil, Drahoň, Drahoš, Duchoslav, León, Títus, Drahoľuba, Drahomila, Duchoslava, Leóna, Leónia",
		 "5.1.": "Andrea, Artúr",
		 "6.1.": "Antónia, Melchior, Melichar, Menhard",
		 "7.1.": "Bohuslava, Atila, Lucián, Bohuna, Boleslava, Božislava, Luciána",
		 "8.1.": "Severín, Čestmír, Pravomil, Čestmíra, Pravomila, Severína",
		 "9.1.": "Alexej, Alex, Domoľub, Julián, Pravoľub, Vladan, Vladen, Alexia, Pravoľuba, Vladana, Vladena",
		 "10.1.": "Dáša, Agatón, Dalimil, Dalimír, Dalimila, Dalimíra",
		 "11.1.": "Malvína, Honorát, Tasilo, Honoráta",
		 "12.1.": "Ernest, Arkád, Arnošt, Arkádia, Arnoštka, Erna, Ernestína",
		 "13.1.": "Rastislav, Čistomil, Čistoslav, Rastic, Rastimír, Ratislav, Vidor, Čistomila, Čistoslava, Rastislava, Ratislava",
		 "14.1.": "Radovan, Hilár, Uriáš, Uriel, Hilária, Radovana",
		 "15.1.": "Dobroslav, Dobrotín, Domoslav, Loránt, Múdroslav, Domoslava",
		 "16.1.": "Kristína",
		 "17.1.": "Nataša, Antal",
		 "18.1.": "Bohdana, Priskus, Piroška, Priska",
		 "19.1.": "Drahomíra, Mário, Sára, Márius, Dúbravka",
		 "20.1.": "Dalibor, Fabián, Fábius, Sebastián, Šebastián, Fábia, Fabiána, Fabiola, Sebastiána",
		 "21.1.": "Vincent, Vincencia",
		 "22.1.": "Zora, Dorián, Sírius, Slavoľub, Slavomil, Zoran, Auróra, Cyntia, Doriána, Sinda, Slavomila, Zorana",
		 "23.1.": "Miloš, Miloň, Selma",
		 "24.1.": "Timotej, Ctiboh, Timotea",
		 "25.1.": "Gejza, Saul, Šavol",
		 "26.1.": "Tamara, Polykarp, Slavibor, Slavislav, Slaviboj, Slavoboj, Svätoboj, Svätobor, Xenofón, Žarko, Polykarpa",
		 "27.1.": "Bohuš, Pribislav, Pribiš",
		 "28.1.": "Alfonz, Manfréd, Alfonzia",
		 "29.1.": "Gašpar, Pribina",
		 "30.1.": "Ema, Jasna",
		 "31.1.": "Emil, Emilián, Emiliána",
        "1.2.": "Tatiana, Hynek, Trifon, Táňa",
        "2.2.": "Erik, Erika, Aida",
        "3.2.": "Blažej, Celerín, Celerína",
        "4.2.": "Veronika, Nika, Verena, Verona, Veronica",
        "5.2.": "Agáta, Moderát, Modest, Leda, Moderáta, Modesta",
        "6.2.": "Dorota, Dorisa, Titanila",
        "7.2.": "Vanda, Romuald",
        "8.2.": "Zoja, Aranka",
        "9.2.": "Zdenko, Rainold, Rinaldo, Zdeno, Apolena, Apoliena, Apolónia",
        "10.2.": "Gabriela, Scholastika, Školastika",
        "11.2.": "Dezider, Želislav, Dezidera, Želislava",
        "12.2.": "Perla, Ron, Ronald, Zoro, Zoroslav, Eulália, Slavena, Solveiga, Zoroslava",
        "13.2.": "Arpád, Jordán, Jordána",
        "14.2.": "Valentín, Velimír",
        "15.2.": "Pravoslav, Faust, Faustína, Georgia, Georgína, Pravoslava",
        "16.2.": "Ida, Liana, Pamfil, Pamfília",
        "17.2.": "Miloslava, Flavián, Flávius, Silván, Silvín, Flávia, Milomíra, Miluša, Silvána",
        "18.2.": "Jaromír, Simeon, Jaromíra, Konkordia, Bernadetta",
        "19.2.": "Vlasta, Konrád, Kurt",
        "20.2.": "Lívia, Aladár, Lívio, Lívius, Udo, Ulrich, Alma, Ulrika, Ulriška",
        "21.2.": "Eleonóra",
        "22.2.": "Etela",
        "23.2.": "Roman, Romana, Romina",
        "24.2.": "Matej, Jazmína, Goran, Mateja",
        "25.2.": "Frederik, Frederika, Taras, Federika",
        "26.2.": "Viktor, Porfýr, Edina",
        "27.2.": "Alexander, Leander, Sandro, Skender, Drahotína, Dražica, Leandra",
        "28.2.": "Zlatica, Elemír, Elo, Lumír, Zlata",
        "29.2.": "Radomír",
        "1.3.": "Albín",
        "2.3.": "Anežka",
        "3.3.": "Bohumil, Bohumila, Ticián, Ginda, Kunigunda, Ticiána",
        "4.3.": "Kazimír, Gerazim, Romeo, Jadrana, Kazimíra",
        "5.3.": "Fridrich, Lucius, Teofil, Friderika, Teofila",
        "6.3.": "Radoslav, Radoslava, Fridolín, Koriolán, Radislav, Radovan, Felícia, Fridolína, Radislava",
        "7.3.": "Tomáš, Tomislav, Tomáška, Tomislava",
        "8.3.": "Alan, Alana",
        "9.3.": "Františka, Erhard",
        "10.3.": "Branislav, Bruno, Bratislav, Bronislav, Bratislava, Taras",
        "11.3.": "Angela, Angelika, Angel, Volfram, Algelína, Jurina",
        "12.3.": "Gregor, Teofan, Gregora, Gregoria, Gregorína",
        "13.3.": "Vlastimil, Kira, Rozína",
        "14.3.": "Matilda, Metaneta",
        "15.3.": "Svetlana,Agap, Belomír, Rodan, Roderich, Roderik, Torkvát, Agapa, Agapia, Rodana, Roderika",
        "16.3.": "Boleslav, Amos, Bolemír, Heribert, Bolemíra",
        "17.3.": "Ľubica, Ľuban, Ľuben, Zbignev, Zbyšek, Ľuba",
        "18.3.": "Eduard, Ctislav, Salvátor, Ctislava, Eduarda",
        "19.3.": "Jozef, Sibyla",
        "20.3.": "Víťazoslav, Klaudián, Klaudín, Klaudio, Klaudius, Víťazoslava",
        "21.3.": "Blahoslav, Blahoboj, Blahosej, Radek, Radko",
        "22.3.": "Beňadik, Benedikt, Oktavián, Oktávius, Benedikta, Benilda, Benita, Izolda, Oktávia",
        "23.3.": "Adrián, Apián, Dárius, Viktorián, Apia",
        "24.3.": "Gabriel",
        "25.3.": "Marián, Humbert, Anunciáta, Irida, Irisa",
        "26.3.": "Emanuel, Eman, Manuel, Emanuela, Manuela",
        "27.3.": "Alena, Rupert, Ruprecht, Dita",
        "28.3.": "Soňa, Ilarion",
        "29.3.": "Miroslav, Mieroslav, Bertold, Bertolda, Mieroslava",
        "30.3.": "Vieroslava, Vieroľub, Vieromil, Vieroslav",
        "31.3.": "Benjamín, Kvído, Balbína",
        "1.4.": "Hugo, Hugolín",
        "2.4.": "Zita, Áron",
        "3.4.": "Richard, Richarda",
        "4.4.": "Izidor, Izidora",
        "5.4.": "Miroslava, Mira",
        "6.4.": "Irena, Irína, Celestín, Ruben, Sixtus, Celestína, Venuša",
        "7.4.": "Zoltán, Armand, Herman, Rufínus, Rúfus, Armanda, Rufína, Rumjana",
        "8.4.": "Albert, Albertín, Albrecht, Valter, Alberta, Albertína, Albrechta",
        "9.4.": "Milena, Erhard, Mileva",
        "10.4.": "Igor, Ezechiel, Ivar, Ivor, Radomil, Igora, Radomila",
        "11.4.": "Július, Antip, Ariel, Ariela, Arleta, Leo, Lev",
        "12.4.": "Estera, Aster, Davorín, Zenon, Astéria",
        "13.4.": "Aleš, Artem, Artemon, Artemia, Artemida, Norma",
        "14.4.": "Justína, Hrdoslav, Hrdoš, Justín, Davorína, Hrdoslava, Justa",
        "15.4.": "Fedor, Fedora",
        "16.4.": "Dana, Danica",
        "17.4.": "Rudolf, Ralf, Rolf, Rudolfa, Rudolfína",
        "18.4.": "Valér, Apolón, Erich, Verner, Ilma",
        "19.4.": "Jela, Krescenc, Krescencia",
        "20.4.": "Marcel, Hvezdoň",
        "21.4.": "Ervín, Abelard, Adelard, Anzelm, Žitoslav, Anzelma, Ervína, Saskia, Žitoslava",
        "22.4.": "Slavomír, Slávo, Tvrdomír, Jelena, Noema",
        "23.4.": "Vojtech, Adalbert, Roger, Adalberta, Vojtecha, Vojteška",
        "24.4.": "Juraj, Fidél, Gaston, Georg, Helmut, Jorik, Jürgen, Deora, Fidélia, Jorga, Jorika, Juraja",
        "25.4.": "Marek, Izmael, Marko, Markus",
        "26.4.": "Jaroslava",
        "27.4.": "Jaroslav, Aristid, Tulius, Aristída, Tulia",
        "28.4.": "Jarmila, Prudencius, Prudencia",
        "29.4.": "Lea, Timon",
        "30.4.": "Anastázia, Anastáz, Blahomil, Asia, Blahomila, Nasťa, Nastasia",
        "1.5.": "Amarila, Pamela, Kevin",
        "2.5.": "Žigmund, Atanáz, Atanázia, Aténa",
        "3.5.": "Galina, Horác, Desana, Halina, Timea",
        "4.5.": "Florián, Flór, Aglája, Floriána, Florína, Pelagia",
        "5.5.": "Lesana, Gothard, Pius, Lesia, Pia, Toska",
        "6.5.": "Hermína, Ovídius, Radivoj, Tankréd, Elfrída, Frída, Herina, Mineta",
        "7.5.": "Monika, Napoleon, Stanimír, Mona",
        "8.5.": "Ingrida, Ina, Inga",
        "9.5.": "Roland, Rolanda",
        "10.5.": "Viktória, Armín, Armína, Beatrica",
        "11.5.": "Blažena, Miranda, Svatava",
        "12.5.": "Pankrác, Achiles",
        "13.5.": "Servác, Chraniboj, Chranibor, Chranislav, Servián, Chranislava, Imelda, Konzuela",
        "14.5.": "Bonifác",
        "15.5.": "Žofia, Brenda, Raisa, Sofia, Zosia",
        "16.5.": "Svetozár, Peregrín, Peregrína",
        "17.5.": "Gizela, Andronik, Ditmar, Paskal, Andronika, Paskália",
        "18.5.": "Viola",
        "19.5.": "Gertrúda, Gerda",
        "20.5.": "Bernard, Bernardín, Hviezdoslav, Bernadeta, Bernarda, Bernardína, Hviezdoslava",
        "21.5.": "Zina, Dobromír, Hostimil, Hostirad, Hostislav, Hostisvit, Teobald, Dobromíra, Hostimila, Hostislava",
        "22.5.": "Júlia, Juliána, Liana, Rita",
        "23.5.": "Želmíra, Želmír, Želimír",
        "24.5.": "Ela",
        "25.5.": "Urban, Vselovod, Vševlad, Vanesa",
        "26.5.": "Dušan",
        "27.5.": "Iveta, Vadim, Valdemar, Valdemara",
        "28.5.": "Viliam, Vilhelm, Elektra, Elma, Vilhelmína",
        "29.5.": "Vilma, Elmar, Maxim, Maxima",
        "30.5.": "Ferdinand, Neander, Ferdinanda",
        "31.5.": "Petrana, Petronela, Petrónius, Blahoslav, Nela, Petrónia, Nelly",
        "1.6.": "Žaneta",
        "2.6.": "Oxana, Xénia, Erazim, Erazmus, Jaromil, Vlastimila",
        "3.6.": "Karolína, Kevin, Lino, Linus, Palmíro, Kaja, Klotilda, Lina, Lineta, Palmíra",
        "4.6.": "Lenka, Lena",
        "5.6.": "Laura, Dorotej, Fatima, Laurencia, Loreta, Loriána",
        "6.6.": "Norbert, Norman, Romulus, Adolfína, Norberta, Perzida",
        "7.6.": "Róbert, Borislav, Robin, Teodot, Dalma, Oriána, Róberta, Robina",
        "8.6.": "Medard",
        "9.6.": "Stanislava, Felicián, Prímus, Vojeslav, Berenika, Vojeslava",
        "10.6.": "Margaréta, Gréta",
        "11.6.": "Dobroslava, Barnabáš, Dobrava, Dobrota, Dobrotína, Flóra, Pavoslava",
        "12.6.": "Zlatko, Svätoslav, Svetislav, Svetoslav, Zlatan, Zlatomír, Zlatoň, Zlatoš, Svätoslava, Svetislava, Svetoslava, Zlatana, Zlatomíra",
        "13.6.": "Anton, Genadij, Tobiáš",
        "14.6.": "Vasil, Bazil, Elizej, Kvintilián, Kvintín, Kvintus, Herta, Kvinta, Kvintiliána",
        "15.6.": "Vít, Jolana",
        "16.6.": "Bianka, Blanka, Benon, Božetech, Alina, Božetecha",
        "17.6.": "Adolf, Adolfína",
        "18.6.": "Vratislav, Leontín, Milovan, Milovín, Sedrik, Leontína, Milovana",
        "19.6.": "Alfréd, Leonid, Leonídas, Leoš, Ruslan, Alfréda",
        "20.6.": "Valéria, Florencián, Florentín, Silver, Florencia, Florentína",
        "21.6.": "Alojz, Elvis, Lejla",
        "22.6.": "Paulína, Achác, Eberhard, Paulín, Paula, Rozvita, Zaira",
        "23.6.": "Sidónia, Sidón",
        "24.6.": "Ján, Janis, Jaško, Jens, Johan, Jovan, Nino, Sean",
        "25.6.": "Tadeáš, Olívia, Olívius, Prosper, Febrónia, Oliva",
        "26.6.": "Adriána, Stojan, Adriena, Ria, Riana, Stojana",
        "27.6.": "Ladislav, Ladislava, Samson, Sulamita",
        "28.6.": "Beáta, Beátus, Slavoj, Bea",
        "29.6.": "Peter, Pavol, Petra, Pavel, Pavla, Petula",
        "30.6.": "Melánia, Vlastibor, Vlastimír, Šárka, Vlastimíra",
        "1.7.": "Diana, Dean, Dejan, Dina, Zian, Dajana, Deana, Kalina, Tabita, Tajana, Annamária",
        "2.7.": "Berta, Bertín, Bertína",
        "3.7.": "Miloslav, Irenej, Miliduch, Milomír, Milorad, Radimír, Rodimír, Radimíra",
        "4.7.": "Prokop, Procius, Prokopa",
        "5.7.": "Cyril, Metod, Cyrus, Cyrila",
        "6.7.": "Patrik, Patrícia, Patrokles",
        "7.7.": "Oliver, Donald, Kastor, Veleslav, Velislav, Valibals, Veleslava, Velislava",
        "8.7.": "Ivan, Ivo, Kilián, Perikles",
        "9.7.": "Lujza, Lukrécius, Lizelota, Lukrécia",
        "10.7.": "Amália, Amína, Lada",
        "11.7.": "Milota, Milutín",
        "12.7.": "Nina, Fortunát, Fortunáta",
        "13.7.": "Margita, Arne, Borivoj, Merkéta",
        "14.7.": "Kamil",
        "15.7.": "Henrich, Egon, Enrik, Enriko, Henrik, Henrika, Lota, Šarlota",
        "16.7.": "Drahomír, Karmela, Karmen, Karmena, Rút, Rúta",
        "17.7.": "Bohuslav, Božislav, Svorad",
        "18.7.": "Kamila",
        "19.7.": "Dušana",
        "20.7.": "Eliáš, Iľja, Ilia, Eliána, Iliana",
        "21.7.": "Daniel, Dan, Dalina",
        "22.7.": "Magdaléna, Magda, Mahuliena, Majda",
        "23.7.": "Oľga, Apolinár, Libérius, Libor, Liborius, Apolinára, Libora, Lilien",
        "24.7.": "Vladimír, Vlado, Kinga",
        "25.7.": "Jakub, Kubo, Žakelína",
        "26.7.": "Anna, Hana, Aneta, Anica, Anita, Annamária, Naneta",
        "27.7.": "Božena, Gorazd, Pantaleon",
        "28.7.": "Krištof, Inocent, Svätomír, Svätoš, Inocencia, Nausika, Svätomíra",
        "29.7.": "Marta, Olaf, Serafín, Serafa, Serafína",
        "30.7.": "Libuša, Abdon, Ingemar, Ingeborga, Ľubuša, Rowena",
        "31.7.": "Ignác, Ignát, Vatroslav, Ignácia",
        "1.8.": "Božidara, Božidar, Ľudomír, Božica, Kleopatra, Ľudomíra, Penelopa",
        "2.8.": "Gustáv, Gustáva",
        "3.8.": "Jerguš, Nikodém, Nikodéma",
        "4.8.": "Dominik, Dominika, Krasoslav, Rainer, Krasoslava",
        "5.8.": "Hortenzia, Hortenz, Milivoj, Osvald, Snežana",
        "6.8.": "Jozefína, Nehoslav, Jozefa",
        "7.8.": "Štefánia, Kajetán, Afra, Afrodita, Kajetána, Štefana",
        "8.8.": "Oskár, Donát, Hartvig, Virgín, Donáta, Virgínia",
        "9.8.": "Ľubomíra, Rastic",
        "10.8.": "Vavrinec, Lars, Laurenc, Laurus, Lorenc, Vavro",
        "11.8.": "Zuzana, Trojan, Dulcia, Dulcinela, Dulcínia",
        "12.8.": "Darina, Dárius, Dária",
        "13.8.": "Ľubomír, Hypolit, Kasián, Kasius, Belinda",
        "14.8.": "Mojmír, Eusébius, Mojtech, Eusébia",
        "15.8.": "Marcela",
        "16.8.": "Leonard, Jáchim, Joachim, Linhart, Rochus, Leonarda",
        "17.8.": "Milica, Bertram, Bertrand, Hyacint, Libert, Mirón, Hyacinta",
        "18.8.": "Elena, Helena, Ilona",
        "19.8.": "Lýdia, Vratislava",
        "20.8.": "Anabela, Arabela",
        "21.8.": "Jana, Johana, Jovana",
        "22.8.": "Tichomír, Sigfríd, Tichomil, Tichomíra",
        "23.8.": "Filip, Vlastislav, Filipa, Filipína, Vlastislava",
        "24.8.": "Bartolomej, Bartolomea",
        "25.8.": "Ľudovít, Ludvig, Radim, Ľudovíta",
        "26.8.": "Samuel, Samo, Zemfír, Samuela, Tália, Zemfíra",
        "27.8.": "Silvia, Silvio, Silvius",
        "28.8.": "Augustín, August, Augusta, Augustína, Gustína",
        "29.8.": "Nikola, Nikolaj, Koleta, Nikoleta, Nikol",
        "30.8.": "Ružena, Ružica",
        "31.8.": "Nora, Rajmund, Ramón, Rajmunda, Ramona",
        "1.9.": "Drahoslava, Egid, Egídius",
        "2.9.": "Linda, Absolón, Axel, Justus, Ermelinda, Melinda, Rebeka",
        "3.9.": "Belo, Antim, Klélia",
        "4.9.": "Rozália, Kandid, Mojžiš, Rozalín, Rozálio, Kandida, Róza, Rozeta, Rozita, Rusalka",
        "5.9.": "Regína, Bojan, Bojimír, Bojislav, Borimír, Branimír, Chotimír, Justinián, Otakar, Regan, Regulus, Viktorín, Bojana, Bojimíra, Boislava, Branimíra, Budislava, Chotimíra, Larisa",
        "6.9.": "Alica, Brian, Magnus, Mansvét, Zachariáš, Bria",
        "7.9.": "Marianna, Mariana",
        "8.9.": "Miriama, Miriana",
        "9.9.": "Martina, Gordan, Gordián, Gordon, Omar, Gordana, Rea, Tina",
        "10.9.": "Oleg, Honór, Vitold, Honóra, Krasava, Vitolda",
        "11.9.": "Bystrík, Prótus, Zdislav, Helga, Zdislava",
        "12.9.": "Mária, Maja, Manon, Manona, Marica, Mariela, Marieta, Marika, Marila, Mariola, Marlena, Marusia",
        "13.9.": "Ctibor, Amát, Amátus, Stibor, Sven, Amáta, Tobias",
        "14.9.": "Ľudomil, Dragan, Dragutín, Drahan, Drahotín, Ľudomila, Radka, Serena",
        "15.9.": "Jolana, Melisa, Melita",
        "16.9.": "Ľudmila, Duňa",
        "17.9.": "Olympia, Lambert, Záviš",
        "18.9.": "Eugénia, Ariadna",
        "19.9.": "Konštantín, Trofín, Konstancia, Konštantína",
        "20.9.": "Ľuboslav, Ľuboslava, Eustach, Filibert, Liboslav, Eustachia, Liboslava",
        "21.9.": "Matúš, Ifigénia, Mirela",
        "22.9.": "Móric, Maurícius, Maurus",
        "23.9.": "Zdenka, Polyxénia, Tekla, Zdena",
        "24.9.": "Ľubor, Ľuboš, Terenc",
        "25.9.": "Vladislav, Vladivoj, Eufrozina, Fruzína, Vladislava",
        "26.9.": "Edita",
        "27.9.": "Cyprián, Damián, Kozmas, Damiána, Mirabela",
        "28.9.": "Václav, Chariton, Kariton, Václava",
        "29.9.": "Michal, Michaela, Michael, Michala",
        "30.9.": "Jarolím, Hieronym, Jeremiáš, Jarolíma, Ráchel, Ráchela, Una",
        "1.10.": "Arnold, Remig, Remus, Arnolda, Belina",
        "2.10.": "Levoslav, Leodegar, Levoslava",
        "3.10.": "Stela, Amadeus, Evald, Amadea",
        "4.10.": "František, Edvin, Fraňo",
        "5.10.": "Viera, Blahomír, Placid, Blahomíra, Karitína, Placida",
        "6.10.": "Natália",
        "7.10.": "Eliška",
        "8.10.": "Brigita, Brit, Brita",
        "9.10.": "Dionýz, Dionýzia",
        "10.10.": "Slavomíra, Gedeon, Záboj, Krasomila",
        "11.10.": "Valentína, Belín, Zvonimír, Zvonislav, Bruna, Brunhilda, Luneta, Selena, Zvonimíra, Zvonislava",
        "12.10.": "Maximilián, Max, Maximiliána",
        "13.10.": "Koloman, Edgar",
        "14.10.": "Boris, Borislav, Kalist, Borislava, Kalista",
        "15.10.": "Terézia, Tereza",
        "16.10.": "Vladimíra, Gál, Havel, Havla",
        "17.10.": "Hedviga, Jadviga",
        "18.10.": "Lukáš",
        "19.10.": "Kristián, Christián, Izák, Christiána, Kristiána",
        "20.10.": "Vendelín, Eunika, Vendelína",
        "21.10.": "Uršuľa, Anatol, Anatólia, Antília",
        "22.10.": "Sergej, Dobromil, Sergius, Zdravomil, Kordula, Korduľa, Pribislava, Saloma, Saloména, Solomia",
        "23.10.": "Alojzia, Žitomír",
        "24.10.": "Kvetoslava, Aretas, Cvetan, Gilbert, Harold, Herald, Krasomil, Kvetoň, Kvetoslav, Rafael, Šalamún, Areta, Cvetana, Gilberta, Kveta, Kvetana, Kvetava, Rafaela",
        "25.10.": "Aurel, Krišpín, Vojmír, Zosim, Živan, Živko, Dália, Vojmíra, Živa, Živana",
        "26.10.": "Demeter, Amand, Dimitrij, Evarist, Amanda, Demetria",
        "27.10.": "Sabína, Horislav, Hromislav, Horislava, Hromislava, Sabrina, Zoa, Zoana",
        "28.10.": "Dobromila, Júda, Judáš",
        "29.10.": "Klára, Narcis, Zenob, Klarisa, Narcisa, Zenóbia, Kiara",
        "30.10.": "Šimon, Simona, Arzen, Asen, Simon, Asena, Simoneta, Šimona",
        "31.10.": "Aurélia, Stacho, Volfgang",
        "1.11.": "Denis, Denisa",
        "2.11.": "Cézar, Cezária",
        "3.11.": "Hubert",
        "4.11.": "Karol, Džesika, Jesika, Karola, Skarleta",
        "5.11.": "Imrich, Emerich, Imriška",
        "6.11.": "Renáta, Renát, Renáto, Renátus",
        "7.11.": "René, Engelbert",
        "8.11.": "Bohumír, Bohumíra",
        "9.11.": "Teodor, Orest, Teo, Teodorik, Teodoz, Deodata, Tea, Teodora, Teodózia",
        "10.11.": "Tibor, Tiber, Meluzína, Tibora",
        "11.11.": "Maroš, Martin, Martinián",
        "12.11.": "Svätopluk, Astrid, Jonáš, Astrida",
        "13.11.": "Stanislav",
        "14.11.": "Irma, Juventín, Mladen, Mladoň, Mladotín, Ima, Juventína, Mladena, Mladotína",
        "15.11.": "Leopold, Leopolda, Leopoldína",
        "16.11.": "Agnesa, Otmar, Agneša, Inéza",
        "17.11.": "Klaudia, Klodeta",
        "18.11.": "Eugen, Platón",
        "19.11.": "Alžbeta, Betina, Elizabeta, Lila, Liliana, Líza, Lili, Lilly",
        "20.11.": "Félix, Filemon, Homér",
        "21.11.": "Elvíra, Ctirad, Ctirada",
        "22.11.": "Cecília, Cecilián, Šejla",
        "23.11.": "Klement, Klementín, Kliment, Kolumbín, Klementína, Kolumbína",
        "24.11.": "Emília, Milín, Milina",
        "25.11.": "Katarína, Katrina",
        "26.11.": "Kornel, Valerián",
        "27.11.": "Milan, Nestor, Virgil, Milana",
        "28.11.": "Henrieta, Gerhard, Tristan, Desdemona, Eta",
        "29.11.": "Vratko, Saturnín, Zaida",
        "30.11.": "Andrej, Ondrej, Andreas",
        "1.12.": "Edmund, Edmunda",
        "2.12.": "Bibiána, Budimír, Budislav, Budimíra, Viviána",
        "3.12.": "Oldrich, Sofron, Xavér, Sofrónia, Xavéria",
        "4.12.": "Barbora, Babeta, Barbara, Barica",
        "5.12.": "Oto, Gerald, Otakar, Otokar, Geralda, Geraldína, Jitka, Ota, Sáva",
        "6.12.": "Mikuláš, Nikita, Niko, Nikolas, Mikuláška, Nikoleta",
        "7.12.": "Ambróz, Amarant, Amaranta, Ambrózia",
        "8.12.": "Marína",
        "9.12.": "Izabela, Dalila, Leokádia",
        "10.12.": "Radúz, Herbert",
        "11.12.": "Hilda, Hildegard, Hildegarda",
        "12.12.": "Otília, Spiridon, Dília, Odeta",
        "13.12.": "Lucia, Rosan, Rosana, Roxana",
        "14.12.": "Branislava, Bronislava, Broňa",
        "15.12.": "Ivica, Detrich, Radan, Radana",
        "16.12.": "Albína, Bela, Teofánia",
        "17.12.": "Kornélia, Lazár, Kora, Korina",
        "18.12.": "Sláva, Slávka, Gracián, Grácia, Graciána, Slavislava",
        "19.12.": "Judita, Abrahám, Mstislav, Neméz, Ita, Mstislava, Neméza",
        "20.12.": "Dagmara, Dagmar, Dag, Dagobert, Daga, Damara",
        "21.12.": "Bohdan",
        "22.12.": "Adela, Ada, Adelaida, Adelgunda, Adelína, Adina, Alida",
        "23.12.": "Nadežda, Naďa",
        "24.12.": "Adam, Eva, Evamária, Evelína, Gaja, Gajana, Geja",
        "25.12.": "1. sviatok vianočný",
        "26.12.": "Štefan",
        "27.12.": "Filoména, Filomén",
        "28.12.": "Ivana, Ivona, Iva",
        "29.12.": "Milada, Jonatán, Miladín, Nátan, Natanel",
        "30.12.": "Dávid, Lotar",
        "31.12.": "Silvester, Horst"					
				}'; 
				$names_array = json_decode($ndjson);
				return $names_array;				
			}		
			public function get_czech_namedays_array(){
				$ndjson = '{
"1.1.": "Mečislav",
"2.1.": "Karina,Vasil",
"3.1.": "Radmila,Radomil,Jenovéfa,Jenifer",
"4.1.": "Diana,Dajana,Deana",
"5.1.": "Dalimil,Dylan",
"6.1.": "Kašpar,Melichar,Baltazar",
"7.1.": "Vilma,Vilemína,Atila",
"8.1.": "Čestmír,Erhard",
"9.1.": "Vladan,Valtr,Vlaďka,Vladana",
"10.1.": "Břetislav,Břetislava",
"11.1.": "Bohdana,Teodora",
"12.1.": "Pravoslav,Pravoslava",
"13.1.": "Edita,Leontýna",
"14.1.": "Radovan,Radovana",
"15.1.": "Alice,Severín",
"16.1.": "Ctirad,Ctislav",
"17.1.": "Drahoslav,Drahoš",
"18.1.": "Vladislav,Vladislava,Priska",
"19.1.": "Doubravka,Fabián",
"20.1.": "Ilona,Sebastián",
"21.1.": "Běla,Bianka,Géza",
"22.1.": "Slavomír,Slavomíra,Slávek",
"23.1.": "Zdeněk,Raimund,Ramon",
"24.1.": "Milena,Amanda,Tim",
"25.1.": "Miloš,Miloň",
"26.1.": "Zora,Zoran,Danica,Aurora",
"27.1.": "Ingrid,Ingeborg,Inka",
"28.1.": "Otýlie,Manfréd",
"29.1.": "Zdislava,Zdislav",
"30.1.": "Robin,Erna",
"31.1.": "Marika,Marieta",
"1.2.": "Hynek,Jasmína",
"2.2.": "Nela,Aida",
"3.2.": "Blažej,Donald",
"4.2.": "Jarmila,Gilbert",
"5.2.": "Dobromila,Dobromil",
"6.2.": "Vanda,Samanta",
"7.2.": "Veronika,Verona,Berenika",
"8.2.": "Milada,Aranka,Mlada",
"9.2.": "Apolena,Ronald",
"10.2.": "Mojmír,Mojmíra",
"11.2.": "Božena,Dezider",
"12.2.": "Slavěna,Slávka,Glorie",
"13.2.": "Věnceslav,Věnceslava,Jordan",
"14.2.": "Valentýn,Valentýna",
"15.2.": "Jiřina,Jorga,Jorika",
"16.2.": "Ljuba,Luba,Danuta",
"17.2.": "Miloslava,Grácie,Fiona",
"18.2.": "Gizela,Flavie",
"19.2.": "Patrik,Konrád",
"20.2.": "Oldřich,Dorián",
"21.2.": "Lenka,Eleonora,Lena",
"22.2.": "Petr,Etela",
"23.2.": "Svatopluk,Svatobor",
"24.2.": "Matěj,Matyáš",
"25.2.": "Liliana,Valburga,Taras,Nevena",
"26.2.": "Dorota,Dora,Doris,Božetěch",
"27.2.": "Alexandr,Torsten",
"28.2.": "Lumír,Lumíra,Kira",
"29.2.": "Horymír",
"1.3.": "Bedřich,Bedřiška,Dětřich",
"2.3.": "Anežka,Inéz,Inesa",
"3.3.": "Kamil,Vladivoj",
"4.3.": "Stela,Jadranka",
"5.3.": "Kazimír,Kazimíra",
"6.3.": "Miroslav,Mirek,Fridolín",
"7.3.": "Tomáš,Tom,Tomislav",
"8.3.": "Gabriela,Zoltán,Merlin",
"9.3.": "Františka,Rebeka,Radúz",
"10.3.": "Viktorie,Melita,Melisa,Ildika",
"11.3.": "Anděla,Angelika,Anděl",
"12.3.": "Řehoř",
"13.3.": "Růžena,Roza,Rosana",
"14.3.": "Rút,Matylda,Maud",
"15.3.": "Ida,Hilda,Longin",
"16.3.": "Elena,Herbert,Amos",
"17.3.": "Vlastimil,Vlastimila",
"18.3.": "Eduard,Eduarda",
"19.3.": "Josef,Josefa,Sibyla",
"20.3.": "Světlana,Světla,Roxana",
"21.3.": "Radek,Radko",
"22.3.": "Leona,Lea,Leokádie,Leonie",
"23.3.": "Ivona,Alfons,Axel",
"24.3.": "Gabriel,Zbyslav",
"25.3.": "Marián,Mario,Marius",
"26.3.": "Emanuel,Emanuela,Manuel,Manuela",
"27.3.": "Dita,Malvína,Rupert",
"28.3.": "Soňa,Gedeon",
"29.3.": "Taťána,Slavomil,Slavomila",
"30.3.": "Arnošt,Ernest,Arnold,Arnoštka,Arne,Arna",
"31.3.": "Kvido,Quido,Arpád",
"1.4.": "Hugo,Veleslav,Velen",
"2.4.": "Erika,Aron",
"3.4.": "Richard,Richarda",
"4.4.": "Ivana,Izidor",
"5.4.": "Miroslava,Mirka,Mira",
"6.4.": "Vendula,Venuše",
"7.4.": "Heřman,Hermína,Armin,Armand,Mína,",
"8.4.": "Ema,Konstantina",
"9.4.": "Dušan,Dušana,Dustin",
"10.4.": "Darja,Darie",
"11.4.": "Izabela,Ratmír,Ariel",
"12.4.": "Julius,Julián,Zenon",
"13.4.": "Aleš,Aleška,Norma",
"14.4.": "Vincenc,Vincent,Pravomil,Pravomila",
"15.4.": "Anastázie,Oktavián",
"16.4.": "Irena,Erina,Ireneus",
"17.4.": "Rudolf,Rudolfa,Rolf,Ralf,Raul,",
"18.4.": "Valérie,Verner,Valer",
"19.4.": "Rostislav,Rastislav,Timon",
"20.4.": "Marcela,Odeta,Celina",
"21.4.": "Alexandra,Selma",
"22.4.": "Evženie,Leonid",
"23.4.": "Vojtěch,Vojtěška,Gerhard,Garik",
"24.4.": "Jiří,Fidel",
"25.4.": "Marek,Ervín,Ervína",
"26.4.": "Oto,Ota,Uve,Udo",
"27.4.": "Jaroslav,Jarolím",
"28.4.": "Vlastislav,Vlastislava,Paris",
"29.4.": "Robert,Roberta,Roderik,Roger",
"30.4.": "Blahoslav,Blahoslava,Blahomír,Blahomil",
"1.5.": "Jeremiáš,Pamela",
"2.5.": "Zikmund,Atanas",
"3.5.": "Alexej,Alexa,Alexie",
"4.5.": "Květoslav,Florián",
"5.5.": "Klaudie,Klaudius",
"6.5.": "Radoslav,Radislav",
"7.5.": "Stanislav,Stojan",
"8.5.": "Zlatan,Zlatko,Zlatomír,Aurel",
"9.5.": "Ctibor,Honoráta",
"10.5.": "Blažena,Gordon",
"11.5.": "Svatava,Svatoslava,Svatomíra",
"12.5.": "Pankrác,Vsevolod",
"13.5.": "Servác,Ofélie",
"14.5.": "Bonifác,Dina",
"15.5.": "Žofie,Sofie,Harald",
"16.5.": "Přemysl,Přemek,Přemyslav",
"17.5.": "Aneta,Paskal,Dětmar",
"18.5.": "Nataša,Timea",
"19.5.": "Ivo,Celestýn,Alvin",
"20.5.": "Zbyšek",
"21.5.": "Monika,Mona",
"22.5.": "Emil,Rita,Emilián",
"23.5.": "Vladimír,Vladimíra,Želmíra",
"24.5.": "Jana,Vanesa",
"25.5.": "Viola,Violeta,Urban",
"26.5.": "Filip,Filipa,Filipína",
"27.5.": "Valdemar,Vadim,Vojslav",
"28.5.": "Vilém,Viliam,Vilibald",
"29.5.": "Maxmilián,Maxim,Max",
"30.5.": "Ferdinand,Elmar",
"31.5.": "Kamila,Nila",
"1.6.": "Laura,Lora,Loreta",
"2.6.": "Jarmil,Jaromil",
"3.6.": "Tamara,Kevin,Lešek",
"4.6.": "Dalibor,Tara,Fatima",
"5.6.": "Dobroslav,Dobroslava,Dobruše",
"6.6.": "Norbert,Norman",
"7.6.": "Iveta,Slavoj,Slavibor",
"8.6.": "Medard,Pěva",
"9.6.": "Stanislava,Anabela",
"10.6.": "Gita,Margita,Gréta",
"11.6.": "Bruno,Barnabáš,Brunhilda",
"12.6.": "Antonie,Táňa",
"13.6.": "Antonín,Genadij",
"14.6.": "Roland,Herta,Rolanda",
"15.6.": "Vít,Víta,Senta",
"16.6.": "Zbyněk,Zbyhněv,Zbyňka",
"17.6.": "Adolf,Adina,Adolfina,Ada",
"18.6.": "Milan,Milana,Milíč",
"19.6.": "Leoš,Leo,Leon,Lev,Ruslan,",
"20.6.": "Květa,Květuše,Flora",
"21.6.": "Alois,Aloisie,Lejla",
"22.6.": "Pavla,Zaira,Arabela",
"23.6.": "Zdeňka,Zdena,Zdenka,Sidonie",
"24.6.": "Jan,Jonatan,Dejan",
"25.6.": "Ivan,Salome,Fabrizio",
"26.6.": "Adriana,Adrian",
"27.6.": "Ladislav,Ladislava",
"28.6.": "Lubomír,Lubomíra,Lubomil,Serena",
"29.6.": "Petr,Pavel,Esmeralda",
"30.6.": "Šárka,Vlastimír,Vlastimíra",
"1.7.": "Jaroslava,Vesna",
"2.7.": "Patricie,Alma",
"3.7.": "Radomír,Radomíra,Anatol",
"4.7.": "Prokop,Ulrich",
"5.7.": "Cyril,Metoděj",
"6.7.": "Spytihněv",
"7.7.": "Bohuslava,Hostivít",
"8.7.": "Nora,Edgar,Kilián",
"9.7.": "Drahoslava,Drahuše",
"10.7.": "Libuše,Amálie,Ludoslav,Ludoslava",
"11.7.": "Olga,Helga,Pius",
"12.7.": "Bořek,Borislav",
"13.7.": "Markéta,Margareta,Perla,Megan",
"14.7.": "Karolína,Larisa",
"15.7.": "Jindřich,Egon",
"16.7.": "Luboš,Cedrik,Carmen",
"17.7.": "Martina,Iris,Arleta",
"18.7.": "Drahomíra,Drahomír,Drahomila,Drahomil",
"19.7.": "Čeněk,Čeňka",
"20.7.": "Ilja,Eliáš,Eliana,Iljana",
"21.7.": "Vítězslav,Vítězslava",
"22.7.": "Magdaléna,Magda,Marlena,Rozvita",
"23.7.": "Libor,Liboslav,Libora,Liboslava",
"24.7.": "Kristýna,Tina,Gleb",
"25.7.": "Jakub,Timur",
"26.7.": "Anna,Anita,Nancy",
"27.7.": "Věroslav,Bertold",
"28.7.": "Viktor,Alina,Inocenc",
"29.7.": "Marta,Beatrice,Olaf",
"30.7.": "Bořivoj,Vojen",
"31.7.": "Ignác,Ignát",
"1.8.": "Oskar,Ludomír,Medea",
"2.8.": "Gustav,Elfrída,Gustava",
"3.8.": "Miluše,Nikodém,Jerguš",
"4.8.": "Dominik,Dominika,Rainer,Neda",
"5.8.": "Kristián,Milivoj,Osvald",
"6.8.": "Oldřiška,Ulrika,Něhoslav",
"7.8.": "Lada,Kajetán,Iboja",
"8.8.": "Soběslav,Virginie,Soběslava",
"9.8.": "Roman,Romeo,Ratibor,Ratislav",
"10.8.": "Vavřinec,Lars,Laurenc",
"11.8.": "Zuzana,Filoména",
"12.8.": "Klára,Jasna,Jasoň",
"13.8.": "Alena,Sven,Belinda",
"14.8.": "Alan,Alen",
"15.8.": "Hana,Mirela",
"16.8.": "Jáchym,Abrahám",
"17.8.": "Petra,Petronela,Petula,Záviš",
"18.8.": "Helena,Jelena,Ena",
"19.8.": "Ludvík,Ludvíka,Luisa",
"20.8.": "Bernard,Bernarda,Dino,Bernardina,Bernardeta,",
"21.8.": "Johana,Johanka,Noemi",
"22.8.": "Bohuslav,Božislav,Tichomír",
"23.8.": "Sandra,Tekla,Polyxena",
"24.8.": "Bartoloměj,Natanael",
"25.8.": "Radim,Radima,Elvíra",
"26.8.": "Luděk,Luďka,Ludiše",
"27.8.": "Otakar,Otakara",
"28.8.": "Augustýn,Augustýna,Augusta,Pelagie",
"29.8.": "Evelína,Miron,Myron",
"30.8.": "Vladěna,Kim,Kimberley",
"31.8.": "Pavlína,Bela,Aris",
"1.9.": "Linda,Samuel,Jiljí",
"2.9.": "Adéla,Adelína",
"3.9.": "Bronislav,Bronislava,Branislav,Branislava",
"4.9.": "Jindřiška,Rozálie",
"5.9.": "Boris,Bojan,Bojana",
"6.9.": "Boleslav,Boleslava",
"7.9.": "Regína,Gina,Rea",
"8.9.": "Mariana,Mariola,Marion",
"9.9.": "Daniela,Omar,Neklan,Gordana",
"10.9.": "Irma,Krasava",
"11.9.": "Denisa,Denis,Diviš,Dionýz,Bystrík,",
"12.9.": "Marie,Maja,Máša,Ria",
"13.9.": "Lubor,Melinda",
"14.9.": "Radka,Radoslava",
"15.9.": "Jolana,Jolanta,Dolores",
"16.9.": "Ludmila,Lidmila,Lola,Lolita,Kornelie,Kornel",
"17.9.": "Naděžda,Naďa,Lambert,Paloma",
"18.9.": "Kryštof,Ariana",
"19.9.": "Zita,Konstantin",
"20.9.": "Oleg,Helmut,Eustach",
"21.9.": "Matouš,Debora,Ruben",
"22.9.": "Darina,Moris,Mořic",
"23.9.": "Berta,Lina",
"24.9.": "Jaromír,Jaromíra,Mercedes",
"25.9.": "Zlata,Zlatuše",
"26.9.": "Andrea,Andriana",
"27.9.": "Jonáš,Damián",
"28.9.": "Václav,Václava,Brian",
"29.9.": "Michal,Michael,Rafael,Rafaela",
"30.9.": "Jeroným,Ráchel",
"1.10.": "Igor,Ivar,Ivor",
"2.10.": "Olivie,Oliver,Olympie",
"3.10.": "Bohumil,Bohuš",
"4.10.": "František,Evald",
"5.10.": "Eliška,Elza,Dalie",
"6.10.": "Hanuš,Hanuše",
"7.10.": "Justýna,Sergej,Justin",
"8.10.": "Věra,Věroslava,Taisa",
"9.10.": "Štefan,Sára,Zara",
"10.10.": "Marina,Marin,Záboj,Bivoj",
"11.10.": "Andrej,Andreas,André",
"12.10.": "Marcel,Edvín,Serafín",
"13.10.": "Renáta,Koloman,Gerald",
"14.10.": "Agáta,Háta,Krasoslav",
"15.10.": "Tereza,Terezie,Aurélie",
"16.10.": "Havel,Galina",
"17.10.": "Hedvika,Heda,Despina",
"18.10.": "Lukáš,Donovan",
"19.10.": "Michaela,Michala,Joel",
"20.10.": "Vendelín,Eunika,Kleopatra,Vendelína",
"21.10.": "Brigita,Uršula,Voršila,Birgita,Brit,Brita",
"22.10.": "Sabina,Sabrina,Korina,Kordula",
"23.10.": "Teodor,Teo,Fedor",
"24.10.": "Nina,Narcis,Narcisa",
"25.10.": "Beáta,Vojmír,Kryšpín",
"26.10.": "Erik,Erich",
"27.10.": "Šarlota,Zoe,Zoja,Lota,Živa,Živan",
"28.10.": "Alfréd,Alfréda",
"29.10.": "Silvie,Sylva,Silván",
"30.10.": "Tadeáš,Demeter,Hvězdoslav,Dimitrij",
"31.10.": "Štěpánka,Volfgang",
"1.11.": "Felix,Felície",
"2.11.": "Tobiáš,Jessica",
"3.11.": "Hubert,Teofil",
"4.11.": "Karel,Karla,Skarlet",
"5.11.": "Miriam,Emerich,Vědunka,Zacharíáš",
"6.11.": "Liběna,Leonard",
"7.11.": "Saskie,Engelbert",
"8.11.": "Bohumír,Bohumíra",
"9.11.": "Bohdan,Darek,Božidar",
"10.11.": "Evžen,Orest,Noe,Lionel",
"11.11.": "Martin,Davor",
"12.11.": "Benedikt,Beno,Astrid,Benedikta,Vitold,",
"13.11.": "Tibor,Brenda",
"14.11.": "Sáva,Mladen",
"15.11.": "Leopold,Leopoldina",
"16.11.": "Otmar,Otomar,Daisy",
"17.11.": "Mahulena,Gertruda,Edeltruda",
"18.11.": "Romana,Odon",
"19.11.": "Alžběta,Běta,Ilsa",
"20.11.": "Nikola,Nikol",
"21.11.": "Albert,Alberta,Aldo",
"22.11.": "Cecílie,Cindy",
"23.11.": "Klement,Klementina,Lukrécie",
"24.11.": "Emílie,Lothar",
"25.11.": "Kateřina,Katrin,Rina",
"26.11.": "Artur,Kurt,Konrád,Artuš,Aram,",
"27.11.": "Xenie,Oxana,Virgil",
"28.11.": "René,Renát,Tristan",
"29.11.": "Zina,Zinajda",
"30.11.": "Ondřej,Ondřejka",
"1.12.": "Iva,Edmund",
"2.12.": "Blanka,Bibiana,Vivien",
"3.12.": "Svatoslav,Svatomír,Xaver",
"4.12.": "Barbora,Barbara,Babeta",
"5.12.": "Jitka,Liana,Abigail",
"6.12.": "Mikuláš,Nikolas,Nikita",
"7.12.": "Ambrož,Benjamín",
"8.12.": "Květoslava,Květomila",
"9.12.": "Vratislav,Vratislava,Dalila",
"10.12.": "Julie,Juliána",
"11.12.": "Dana,Danuše",
"12.12.": "Simona,Šimona",
"13.12.": "Lucie,Lucián,Luciána",
"14.12.": "Lýdie,Livie,Liv",
"15.12.": "Radana,Radan,Zdirad",
"16.12.": "Albína,Albín",
"17.12.": "Daniel,Dan,Lazar,Chantal",
"18.12.": "Miloslav,Milorad",
"19.12.": "Ester,Darius,Mstislav",
"20.12.": "Dagmar,Dáša,Dag",
"21.12.": "Natálie,Rodan",
"22.12.": "Šimon,Simon,Simeon",
"23.12.": "Vlasta,Nika,Niké",
"24.12.": "Adam,Eva",
"25.12.": "Vánoce",
"26.12.": "Štěpán",
"27.12.": "Žaneta,Melánie",
"28.12.": "Bohumila,Donika",
"29.12.": "Judita,Natan,Juta",
"30.12.": "David,Donát",
"31.12.": "Silvestr,Silvestra,Horst,Forest"								
				}';
				$names_array = json_decode($ndjson);
				return $names_array;				
			} 
			public function get_austrian_namedays_array()
			{
				$ndjson = '{
1.1.": "Maria,Wilhelm",
"2.1.": "Basilius,Dietmar,Gregor",
"3.1.": "Genoveva,Odilo",
"4.1.": "Angela,Marius,Rüdiger,Titus",
"5.1.": "Emilia,Johann",
"6.1.": "Erminold",
"7.1.": "Raimund,Valentin",
"8.1.": "Erhard,Gudula,Severin",
"9.1.": "Adrian,Alice,Eberhard,Julian",
"10.1.": "Leonie,Paulus",
"11.1.": "Paulin,Paulinus,Theodosius,Ronan",
"12.1.": "Ernst,Tatjana,Xenia",
"13.1.": "Hilarius,Hilmar,Jutta,Remigius",
"14.1.": "Engelmar,Felix,Rainer",
"15.1.": "Arnold,Maurus,Romedius",
"16.1.": "Dietwald,Marcel,Tilman",
"17.1.": "Antonius,Beatrix",
"18.1.": "Margitta,Ulfried,Uwe",
"19.1.": "Agritius,Marius,Martha,Pia",
"20.1.": "Fabianus,Sebastian,Ursula,Ute",
"21.1.": "Agnes,Ines,Meinrad",
"22.1.": "Vinzenz",
"23.1.": "Hartmut,Heinrich,Nikolaus",
"24.1.": "Franz,Thurid,Vera",
"25.1.": "Paulus,Wolfram",
"26.1.": "Paula,Timotheus,Titus",
"27.1.": "Angela,Julian",
"28.1.": "Caroline,Karoline,Manfred,Thomas",
"29.1.": "Gerhard,Gerd,Josef,Valerius",
"30.1.": "Adelgunde,Martina",
"31.1.": "Johannes,Marcella",
"1.2.": "Brigitta,Katharina,Reginald,Severus",
"2.2.": "Bodo",
"3.2.": "Ansgar,Blasius,Oskar",
"4.2.": "Andreas,Rabanus,Veronika",
"5.2.": "Agatha,Albuin",
"6.2.": "Dorothea,Doris,Paul",
"7.2.": "Ava,Richard",
"8.2.": "Hieronymus,Josefina,Josefine",
"9.2.": "Alto,Anna,Katharina,Apollonia",
"10.2.": "Scholastika,Siegmar",
"11.2.": "Anselm",
"12.2.": "Benedikt,Eulalia,Gregor",
"13.2.": "Adolf,Christina,Irmhild",
"14.2.": "Cyrill,Method,Valentin",
"15.2.": "Georgia,Siegfried",
"16.2.": "Adalbert,Juliana,Liane,Philippa",
"17.2.": "Alexius,Benignus,Bonosus",
"18.2.": "Constanze,Simon,Simone",
"19.2.": "Hadwig,Irmgard,Irma",
"20.2.": "Corona,Falko,Jacinta",
"21.2.": "Enrica,Gunthild,Petrus",
"22.2.": "Isabella",
"23.2.": "Raffaela,Romana",
"24.2.": "Matthias",
"25.2.": "Walburga",
"26.2.": "Edigna,Gerlinde,Ottokar",
"27.2.": "Baldur,Marko,Markward,Gabriel",
"28.2.": "Oswald,Roman,Silvana",
"29.2.": "Hilarius,Oswald",
"1.3.": "Albin,Leontina,Roger",
"2.3.": "Agnes,Karl",
"3.3.": "Friedrich,Camilla,Kunigunde",
"4.3.": "Edwin,Humbert,Kasimir",
"5.3.": "Dietmar,Jeremia,Olivia",
"6.3.": "Fridolin,Nicola,Rosa",
"7.3.": "Felicitas,Perpetua,Reinhard",
"8.3.": "Gerhard,Johannes",
"9.3.": "Bruno,Franziska",
"10.3.": "Emil,John,Gustav",
"11.3.": "Alram,Rosina",
"12.3.": "Almut,Beatrix,Serafina",
"13.3.": "Judith,Leander,Pauline",
"14.3.": "Eva,Evelyn,Mathilde",
"15.3.": "Clemens,Klemens,Maria,Luise",
"16.3.": "Eduard,Herbert",
"17.3.": "Gertraud,Gertrud,Patrick",
"18.3.": "Cyrill,Edward,Sibylle",
"19.3.": "Josef,Josefa,Josefine",
"20.3.": "Claudia,Wolfram",
"21.3.": "Alexandra,Axel,Christian,Emilia",
"22.3.": "Clemens,Klemens,Elmar,Lea",
"23.3.": "Otto,Rebekka,Toribio",
"24.3.": "Elias,Karin,Katharina",
"25.3.": "Judith,Lucia",
"26.3.": "Lara,Ludger",
"27.3.": "Ernst,Frowin,Heimo",
"28.3.": "Guntram,Ingbert",
"29.3.": "Berthold,Helmut,Ludolf",
"30.3.": "Amadeus,Dodo",
"31.3.": "Benjamin,Cornelia",
"1.4.": "Hugo,Irene,Irina",
"2.4.": "Franz,Mirjam,Sandra",
"3.4.": "Richard,Sixtus",
"4.4.": "Isidor,Konrad",
"5.4.": "Crescentia,Vinzenz",
"6.4.": "Notker,Wilhelm",
"7.4.": "Johann",
"8.4.": "Beate,Rose-Marie,Walter",
"9.4.": "Casilda,Waltraud",
"10.4.": "Ezechiel,Gernot,Holda",
"11.4.": "Hildebrand,Stanislaus",
"12.4.": "Herta,Julius,Zeno",
"13.4.": "Hermenegild,Ida,Martin",
"14.4.": "Elmo,Erna,Ernestine",
"15.4.": "Anastasia,Damian,Una",
"16.4.": "Bernadette,Magnus",
"17.4.": "Eberhard,Rudolph",
"18.4.": "Werner,Wigbert",
"19.4.": "Gerold,Leo,Marcel",
"20.4.": "Hildegund,Odetta,Wilhelm",
"21.4.": "Anselm,Konrad",
"22.4.": "Alfred,Kaj,Leonidas",
"23.4.": "Adalbert,Georg,Jörg,Jürgen",
"24.4.": "Egbert,Fidelis,Wilfried",
"25.4.": "Erwin,Markus",
"26.4.": "Helene,Trudpert",
"27.4.": "Petrus,Zita",
"28.4.": "Hugo,Ludwig,Pierre",
"29.4.": "Katharina,Roswitha",
"30.4.": "Pauline,Pius,Silvio",
"1.5.": "Josef",
"2.5.": "Athanasius,Boris,Siegmund",
"3.5.": "Jakob,Philipp,Viola",
"4.5.": "Florian,Guido,Valeria",
"5.5.": "Godehard,Jutta,Sigrid",
"6.5.": "Antonia,Britto,Gundula",
"7.5.": "Gisela,Helga,Notker,Silke",
"8.5.": "Ida,Klara,Ulla,Ulrike",
"9.5.": "Beatus,Caroline,Volkmar",
"10.5.": "Gordian,Isidor,Liliana",
"11.5.": "Gangolf,Joachim,Mamertus",
"12.5.": "Pankraz,Pankratius",
"13.5.": "Servatius",
"14.5.": "Bonifatius,Christian",
"15.5.": "Hertraud,Rupert,Sonja,Sophie",
"16.5.": "Adolf,Johann",
"17.5.": "Dietmar,Pascal,Walter",
"18.5.": "Erich,Erika,Felix,Johannes",
"19.5.": "Ivo,Kuno,Yvonne",
"20.5.": "Bernhardin,Elfriede,Mira",
"21.5.": "Christoph,Constantin,Josef,Julio",
"22.5.": "Julia,Ortwin,Rita",
"23.5.": "Alma,Desiree,Renate",
"24.5.": "Dagmar,Esther",
"25.5.": "Beda,Gregor,Magdalene",
"26.5.": "Alwin,Philipp",
"27.5.": "August,Bruno,Randolph",
"28.5.": "German,Wilhelm",
"29.5.": "Erwin,Irmtraud,Maximin",
"30.5.": "Ferdinand,Johanna,Otto",
"31.5.": "Helma,Mechthild,Petra",
"1.6.": "Justin,Silvana,Simeon,Ronan",
"2.6.": "Armin,Erasmus,Marcel,Petrus",
"3.6.": "Hildburg,Karl,Silvia",
"4.6.": "Christa,Iona,Klothilde",
"5.6.": "Erika,Winfried",
"6.6.": "Bertrand,Kevin,Norbert",
"7.6.": "Anita,Eoban,Gottlieb,Robert",
"8.6.": "Elga,Maria,Medardus",
"9.6.": "Annamaria,Ephraim,Grazia",
"10.6.": "Bardo,Diana,Heinrich,Heinz",
"11.6.": "Alice,Barnabas,Paula",
"12.6.": "Florinda,Guido,Leo",
"13.6.": "Antonius,Bernhard",
"14.6.": "Hartwig,Meinrad",
"15.6.": "Gebhard,Lothar,Veit",
"16.6.": "Benno,Luitgard,Quirin",
"17.6.": "Adolf,Alena,Volker",
"18.6.": "Elisabeth,Ilsa,Marina",
"19.6.": "Juliana,Romuald",
"20.6.": "Adalbert,Florentina",
"21.6.": "Alban,Alois,Aloisia,Ralf",
"22.6.": "Paulinus,Thomas",
"23.6.": "Edeltraud,Marion,Ortrud",
"24.6.": "Johannes,Reingard",
"25.6.": "Dorothea,Eleonora,Ella",
"26.6.": "Anthelm,Vigilius",
"27.6.": "Cyrill,Heimo,Hemma,Maxim",
"28.6.": "Ekkehard,Harald,Irenäus",
"29.6.": "Gero,Paul,Peter",
"30.6.": "Bertram,Ehrentrud,Otto",
"1.7.": "Aaron,Dietrich,Otto,Theobald",
"2.7.": "Wiltrud",
"3.7.": "Günther,Ramon,Ramona,Thomas",
"4.7.": "Berta,Elisabeth,Ulrich",
"5.7.": "Albrecht,Antonius,Letizia",
"6.7.": "Goar,Isaias,Marietta",
"7.7.": "Edda,Firmin,Willibald",
"8.7.": "Amalia,Edgar,Kilian",
"9.7.": "Augustin",
"10.7.": "Engelbert,Knud,Raphael",
"11.7.": "Benedikt,Olga,Oliver",
"12.7.": "Felix,Henriette,Siegbert",
"13.7.": "Arno,Heinrich,Kunigunde",
"14.7.": "Goswin,Kamilus,Roland",
"15.7.": "Bonaventura,Egon,Waldemar",
"16.7.": "Irmgard",
"17.7.": "Charlotte,Donata,Gabriella",
"18.7.": "Answer,Arnulf,Ulf,Friedrich",
"19.7.": "Bernulf,Marina,Poppo,Reto",
"20.7.": "Apollinaris,Bernhard,Margaretha",
"21.7.": "Daniel,Daniela,Julia,Laurentius",
"22.7.": "Maria,Magdalena",
"23.7.": "Birgitta,Birgit,Liborius",
"24.7.": "Christoph",
"25.7.": "Jakobus,Thomas,Valentina",
"26.7.": "Anna,Gloria,Joachim",
"27.7.": "Berthold,Natalie,Pantaleon",
"28.7.": "Adele,Ada,Bantus,Beatus,Innozenz",
"29.7.": "Ladislaus,Martha,Olaf",
"30.7.": "Ingeborg,Inga,Petrus",
"31.7.": "Hermann,Ignatius,Justinus",
"1.8.": "Alfons,Kenneth,Peter",
"2.8.": "Eusebius,Julian,Petrus",
"3.8.": "August,Lydia,Nikodemus",
"4.8.": "Johannes,Rainer",
"5.8.": "Oswald",
"6.8.": "Gilbert",
"7.8.": "Afra,Albert,Cajetan",
"8.8.": "Cyriak,Dominik,Elgar",
"9.8.": "Edith",
"10.8.": "Astrid,Laurenz,Lars",
"11.8.": "Klara,Susanna",
"12.8.": "Karl,Radegunde",
"13.8.": "Cassian,Hippolyt,Marko,Pontianus",
"14.8.": "Maximilian,Meinhard",
"15.8.": "Tarsitius",
"16.8.": "Alfried,Rochus,Stefan",
"17.8.": "Gudrun,Hyazinth,Janine",
"18.8.": "Claudia,Helena,Rainaki",
"19.8.": "Johann,Julius,Sebald",
"20.8.": "Bernhard,Bernd,Ronald",
"21.8.": "Maximilian,Pius",
"22.8.": "Regina",
"23.8.": "Isolde,Rosa,Zachäus",
"24.8.": "Bartholomäus,Michaela",
"25.8.": "Elvira,Josef,Ludwig",
"26.8.": "Gregor,Miriam,Teresa",
"27.8.": "Gebhard,Monika,Vivian",
"28.8.": "Adelinde,Aline,Augustin",
"29.8.": "Johannes",
"30.8.": "Felix,Heribert,Rebekka",
"31.8.": "Paulinus,Raimund",
"1.9.": "Ägidius,Ruth,Verena",
"2.9.": "Ingrid,René,Salomon",
"3.9.": "Gregor,Silvia,Sophie",
"4.9.": "Ida,Iris,Irmgard,Rosalie",
"5.9.": "Roswitha,Teresa",
"6.9.": "Bertram,Gundolf,Magnus",
"7.9.": "Otto,Ralph,Regina",
"8.9.": "Adrian",
"9.9.": "Edgar,Otmar,Pedro",
"10.9.": "Carlo,Diethard,Isabella",
"11.9.": "Felix,Maternus,Regula",
"12.9.": "Gerfried,Maria",
"13.9.": "Johann,Notburga,Tobias",
"14.9.": "Albert,Cornelius",
"15.9.": "Dolores,Melitta,Melissa",
"16.9.": "Edith,Ludmilla,Mechthild",
"17.9.": "Ariane,Hildegard,Robert",
"18.9.": "Herlinde,Lambert,Rica",
"19.9.": "Igor,Januarius",
"20.9.": "Susanne",
"21.9.": "Deborah,Jonas,Matthäus",
"22.9.": "Emmeram,Mauritius",
"23.9.": "Gerhild,Linus,Thekla",
"24.9.": "Gerhard,Hermann,Rupert,Virgil",
"25.9.": "Irmfried,Serge",
"26.9.": "Cosima,Damian,Kosmas",
"27.9.": "Dietrich,Hiltrud,Vinzenz",
"28.9.": "Giselher,Lioba,Thekla,Wenzel",
"29.9.": "Gabriel,Gabriela,Michael,Michaela,Rafael,Rafaela",
"30.9.": "Hieronymus,Urs,Victor",
"1.10.": "Remigius",
"2.10.": "Gideon",
"3.10.": "Bianca,Ewald,Udo",
"4.10.": "Aurea,Edwin,Franz",
"5.10.": "Gallina,Herwig,Meinolf",
"6.10.": "Adalbero,Bruno,Melanie",
"7.10.": "Jörg,Justina,Rosa,Maria",
"8.10.": "Felix,Günther,Simeon",
"9.10.": "Dionys,Günter,Sara,Johannes",
"10.10.": "Gereon,Samuel,Viktor",
"11.10.": "Bruno,Jakob",
"12.10.": "Edwin,Gottfried,Maximilian",
"13.10.": "Eduard,Gerald",
"14.10.": "Burkhard,Kallixtus",
"15.10.": "Aurelia,Theresia",
"16.10.": "Gallus,Hedwig,Margareta",
"17.10.": "Anselm,Ignatius",
"18.10.": "Gwenn,Justus,Lukas",
"19.10.": "Isaak,Johannes,Paul,Peter",
"20.10.": "Ira,Irina,Vitalis,Wendelin",
"21.10.": "Karl,Ursula,Ulla",
"22.10.": "Cordula,Ingbert,Salome",
"23.10.": "Johannes,Severin,Uta",
"24.10.": "Alois,Aloisia,Anton,Armella",
"25.10.": "Krispin,Krispinian",
"26.10.": "Albin,Amand,Wigand",
"27.10.": "Christa,Sabina,Wolfhard",
"28.10.": "Simon,Thaddäus",
"29.10.": "Ermelinda,Melinda",
"30.10.": "Alfons,Angelo,Dieter",
"31.10.": "Quentin,Wolfgang",
"1.11.": "Arthur,Harald,Otmar,Rupert",
"2.11.": "Angela,Margarethe,Tobias",
"3.11.": "Hubert,Martin,Pirmin,Rupert",
"4.11.": "Karl,Karla,Modesta",
"5.11.": "Bernhard,Berthild,Emmerich",
"6.11.": "Christine,Leonhard,Rudolf",
"7.11.": "Carina,Engelbert,Willibrord",
"8.11.": "Gottfried,Willehad",
"9.11.": "Herfried,Roland,Theodor",
"10.11.": "Andrea,Andreas,Jens,Leo",
"11.11.": "Martin,Menas,Senta",
"12.11.": "Emil,Josaphat,Kunibert",
"13.11.": "Eugen,Livia,Stanislaus",
"14.11.": "Nikolaus,Sidonia",
"15.11.": "Albert,Leopold,Leopoldine",
"16.11.": "Margareta,Otmar",
"17.11.": "Gertrud,Hilda,Florin",
"18.11.": "Odo,Philippine",
"19.11.": "Elisabeth,Bettina,Lisa",
"20.11.": "Bernward,Edmund,Korbinian",
"21.11.": "Amalie",
"22.11.": "Cäcilia,Salvator",
"23.11.": "Clemens,Columban,Detlef",
"24.11.": "Albert,Flora",
"25.11.": "Katharina,Kathrin,Katja",
"26.11.": "Anneliese,Gebhard,Konrad",
"27.11.": "Albrecht,Brunhilde,Uta",
"28.11.": "Berta,Gunther,Jakob",
"29.11.": "Christine,Friedrich,Friederike",
"30.11.": "Andreas,Andrea,Volkert",
"1.12.": "Blanka,Charles,Eligius,Natalie",
"2.12.": "Bibiana,Jan,Lucius",
"3.12.": "Emma,Franz,Xaver,Jason",
"4.12.": "Adolf,Barbara,Johannes",
"5.12.": "Anno,Gerald,Niels,Reinhard",
"6.12.": "Denise,Henrike,Nikolaus",
"7.12.": "Ambrosius,Benedikte",
"8.12.": "Edith,Elfriede",
"9.12.": "Liborius,Reinmar,Valerie",
"10.12.": "Angelina,Bruno,Emma,Herbert",
"11.12.": "Arthur,Damasus,Tassilo",
"12.12.": "Johanna",
"13.12.": "Jodok,Lucia,Odilia",
"14.12.": "Berthold,Johannes",
"15.12.": "Carlo,Christiane,Nina",
"16.12.": "Adelheid,Heidi,Elke",
"17.12.": "Jolanda,Lazarus,Viviana",
"18.12.": "Philipp,Wunibald",
"19.12.": "Benjamin,Susanne",
"20.12.": "Eike,Holger,Julius,Regina",
"21.12.": "Hagar,Peter",
"22.12.": "Jutta",
"23.12.": "Victoria",
"24.12.": "Adam,Eva",
"25.12.": "Anastasia,Eugenia,Josefina,Natalis,Therese",
"26.12.": "Stephan,Stephanie",
"27.12.": "Fabiola",
"28.12.": "Donna,Mattea",
"29.12.": "David,Jonathan,Thomas",
"30.12.": "Felix,Lothar",
"31.12.": "Melanie,Silvester"				
				}';
				$names_array = json_decode($ndjson);
				return $names_array;				
			}			  	
			public function get_hungarian_namedays_array()
			{
				$ndjson = '{	
1.1.": "Fruzsina",
"2.1.": "Ábel",
"3.1.": "Benjámin,Genovéva",
"4.1.": "Leóna,Titusz",
"5.1.": "Simon",
"6.1.": "Boldizsár",
"7.1.": "Attila,Ramóna",
"8.1.": "Gyöngyvér",
"9.1.": "Marcell",
"10.1.": "Melánia",
"11.1.": "Ágota",
"12.1.": "Ernõ",
"13.1.": "Veronika",
"14.1.": "Bódog",
"15.1.": "Lóránd,Lóránt",
"16.1.": "Gusztáv",
"17.1.": "Antal,Antónia",
"18.1.": "Piroska",
"19.1.": "Márió,Sára",
"20.1.": "Fábián,Sebestyén",
"21.1.": "Ágnes",
"22.1.": "Artúr,Vince",
"23.1.": "Rajmund,Zelma",
"24.1.": "Timót",
"25.1.": "Pál",
"26.1.": "Paula,Vanda",
"27.1.": "Angelika",
"28.1.": "Karola,Károly",
"29.1.": "Adél",
"30.1.": "Martina",
"31.1.": "Gerda,Marcella",
"1.2.": "Ignác",
"2.2.": "Aida,Karolina",
"3.2.": "Balázs",
"4.2.": "Csenge,Ráhel",
"5.2.": "Ágota,Ingrid",
"6.2.": "Dóra,Dorottya",
"7.2.": "Rómeó,Tódor",
"8.2.": "Aranka",
"9.2.": "Abigél,Alex",
"10.2.": "Elvira",
"11.2.": "Bertold,Marietta",
"12.2.": "Lídia,Lívia",
"13.2.": "Ella,Linda",
"14.2.": "Bálint,Valentin",
"15.2.": "Georgina,Kolos",
"16.2.": "Julianna,Lilla",
"17.2.": "Donát",
"18.2.": "Bernadett",
"19.2.": "Zsuzsanna",
"20.2.": "Aladár,Álmos",
"21.2.": "Eleonóra",
"22.2.": "Gerzson",
"23.2.": "Alfréd",
"24.2.": "Mátyás",
"25.2.": "Géza",
"26.2.": "Edina",
"27.2.": "Ákos,Bátor",
"28.2.": "Elemér",
"1.3.": "Albin",
"2.3.": "Lujza",
"3.3.": "Kornélia",
"4.3.": "Kázmér",
"5.3.": "Adorján,Adrián",
"6.3.": "Inez,Leonóra",
"7.3.": "Tamás",
"8.3.": "Zoltán",
"9.3.": "Fanni,Franciska",
"10.3.": "Ildikó",
"11.3.": "Szilárd",
"12.3.": "Gergely",
"13.3.": "Ajtony,Krisztián",
"14.3.": "Matild",
"15.3.": "Kristóf",
"16.3.": "Henrietta",
"17.3.": "Gertrúd,Patrik",
"18.3.": "Ede,Sándor",
"19.3.": "Bánk,József",
"20.3.": "Klaudia",
"21.3.": "Benedek",
"22.3.": "Beáta,Izolda",
"23.3.": "Emõke",
"24.3.": "Gábor,Karina",
"25.3.": "Irén,Írisz",
"26.3.": "Emánuel",
"27.3.": "Hajnalka",
"28.3.": "Gedeon,Johanna",
"29.3.": "Auguszta",
"30.3.": "Zalán",
"31.3.": "Árpád",
"1.4.": "Hugó",
"2.4.": "Áron",
"3.4.": "Buda,Richárd",
"4.4.": "Izidor",
"5.4.": "Vince",
"6.4.": "Bíborka,Vilmos",
"7.4.": "Herman",
"8.4.": "Dénes",
"9.4.": "Erhard",
"10.4.": "Zsolt",
"11.4.": "Leó,Szaniszló",
"12.4.": "Gyula",
"13.4.": "Ida",
"14.4.": "Tibor",
"15.4.": "Anasztázia,Tas",
"16.4.": "Csongor",
"17.4.": "Rudolf",
"18.4.": "Andrea,Ilma",
"19.4.": "Emma",
"20.4.": "Tivadar",
"21.4.": "Konrád",
"22.4.": "Csilla,Noémi",
"23.4.": "Béla",
"24.4.": "György",
"25.4.": "Márk",
"26.4.": "Ervin",
"27.4.": "Zita",
"28.4.": "Valéria",
"29.4.": "Péter",
"30.4.": "Katalin,Kitti",
"1.5.": "Fülöp,Jakab",
"2.5.": "Zsigmond",
"3.5.": "Irma,Tímea",
"4.5.": "Flórián,Mónika",
"5.5.": "Adrián,Györgyi",
"6.5.": "Frida,Ivett",
"7.5.": "Gizella",
"8.5.": "Mihály",
"9.5.": "Gergely",
"10.5.": "Ármin,Pálma",
"11.5.": "Ferenc",
"12.5.": "Pongrác",
"13.5.": "Imola,Szervác",
"14.5.": "Bonifác",
"15.5.": "Szonja,Zsófia",
"16.5.": "Botond,Mózes",
"17.5.": "Paszkál",
"18.5.": "Alexandra,Erik",
"19.5.": "Ivó,Milán",
"20.5.": "Bernát,Felícia",
"21.5.": "Konstantin",
"22.5.": "Júlia,Rita",
"23.5.": "Dezsõ",
"24.5.": "Eliza,Eszter",
"25.5.": "Orbán",
"26.5.": "Evelin,Fülöp",
"27.5.": "Hella",
"28.5.": "Csanád,Emil",
"29.5.": "Magdolna",
"30.5.": "Janka,Zsanett",
"31.5.": "Angéla,Petronella",
"1.6.": "Tünde",
"2.6.": "Anita,Kármen",
"3.6.": "Klotild",
"4.6.": "Bulcsú",
"5.6.": "Fatime",
"6.6.": "Cintia,Norbert",
"7.6.": "Róbert",
"8.6.": "Medárd",
"9.6.": "Félix",
"10.6.": "Gréta,Margit",
"11.6.": "Barnabás",
"12.6.": "Villõ",
"13.6.": "Anett,Antal",
"14.6.": "Vazul",
"15.6.": "Jolán,Vid",
"16.6.": "Jusztin",
"17.6.": "Alida,Laura",
"18.6.": "Arnold,Levente",
"19.6.": "Gyárfás",
"20.6.": "Rafael",
"21.6.": "Alajos,Leila",
"22.6.": "Paulina",
"23.6.": "Zoltán",
"24.6.": "Iván",
"25.6.": "Vilmos",
"26.6.": "János,Pál",
"27.6.": "László",
"28.6.": "Irén,Levente",
"29.6.": "Péter,Pál",
"30.6.": "Pál",
"1.7.": "Annamária,Tihamér",
"2.7.": "Ottó",
"3.7.": "Kornél,Soma",
"4.7.": "Ulrik",
"5.7.": "Emese,Sarolta",
"6.7.": "Csaba",
"7.7.": "Apollónia",
"8.7.": "Ellák",
"9.7.": "Lukrécia",
"10.7.": "Amália",
"11.7.": "Lili,Nóra",
"12.7.": "Dalma,Izabella",
"13.7.": "Jenõ",
"14.7.": "Örs,Stella",
"15.7.": "Henrik,Roland",
"16.7.": "Valter",
"17.7.": "Elek,Endre",
"18.7.": "Frigyes",
"19.7.": "Emília",
"20.7.": "Illés",
"21.7.": "Dániel,Daniella",
"22.7.": "Magdolna",
"23.7.": "Lenke",
"24.7.": "Kincsõ,Kinga",
"25.7.": "Jakab,Kristóf",
"26.7.": "Anikó,Anna",
"27.7.": "Liliána,Olga",
"28.7.": "Szabolcs",
"29.7.": "Flóra,Márta",
"30.7.": "Judit,Xénia",
"31.7.": "Oszkár",
"1.8.": "Boglárka",
"2.8.": "Lehel",
"3.8.": "Hermina",
"4.8.": "Dominika,Domonkos",
"5.8.": "Krisztina",
"6.8.": "Berta,Bettina",
"7.8.": "Ibolya",
"8.8.": "László",
"9.8.": "Emõd",
"10.8.": "Lõrinc",
"11.8.": "Tiborc,Zsuzsanna",
"12.8.": "Klára",
"13.8.": "Ipoly",
"14.8.": "Marcell",
"15.8.": "Mária",
"16.8.": "Ábrahám",
"17.8.": "Jácint",
"18.8.": "Ilona",
"19.8.": "Huba",
"20.8.": "István",
"21.8.": "Hajna,Sámuel",
"22.8.": "Menyhért,Mirjam",
"23.8.": "Bence",
"24.8.": "Bertalan",
"25.8.": "Lajos,Patrícia",
"26.8.": "Izsó",
"27.8.": "Gáspár",
"28.8.": "Ágoston",
"29.8.": "Beatrix,Erna",
"30.8.": "Rózsa",
"31.8.": "Bella,Erika",
"1.9.": "Egon,Egyed",
"2.9.": "Dorina,Rebeka",
"3.9.": "Hilda",
"4.9.": "Rozália",
"5.9.": "Lõrinc,Viktor",
"6.9.": "Zakariás",
"7.9.": "Regina",
"8.9.": "Adrienn,Mária",
"9.9.": "Ádám",
"10.9.": "Hunor,Nikolett",
"11.9.": "Teodóra",
"12.9.": "Mária",
"13.9.": "Kornél",
"14.9.": "Roxána,Szeréna",
"15.9.": "Enikõ,Melitta",
"16.9.": "Edit",
"17.9.": "Zsófia",
"18.9.": "Diána",
"19.9.": "Vilhelmina",
"20.9.": "Friderika",
"21.9.": "Máté,Mirella",
"22.9.": "Móric",
"23.9.": "Tekla",
"24.9.": "Gellért,Mercédesz",
"25.9.": "Eufrozina,Kende",
"26.9.": "Jusztina,Pál",
"27.9.": "Adalbert",
"28.9.": "Vencel",
"29.9.": "Mihály",
"30.9.": "Jeromos",
"1.10.": "Malvin",
"2.10.": "Petra",
"3.10.": "Helga",
"4.10.": "Ferenc",
"5.10.": "Aurél",
"6.10.": "Brúnó,Renáta",
"7.10.": "Amália",
"8.10.": "Koppány",
"9.10.": "Dénes",
"10.10.": "Gedeon",
"11.10.": "Brigitta",
"12.10.": "Miksa",
"13.10.": "Ede,Kálmán",
"14.10.": "Helén",
"15.10.": "Teréz",
"16.10.": "Gál",
"17.10.": "Hedvig",
"18.10.": "Lukács",
"19.10.": "Nándor",
"20.10.": "Vendel",
"21.10.": "Orsolya",
"22.10.": "Elõd",
"23.10.": "Gyöngyi",
"24.10.": "Salamon",
"25.10.": "Bianka,Blanka",
"26.10.": "Dömötör",
"27.10.": "Szabina",
"28.10.": "Simon,Szimonetta",
"29.10.": "Nárcisz",
"30.10.": "Alfonz",
"31.10.": "Farkas",
"1.11.": "Marianna",
"2.11.": "Achilles",
"3.11.": "Gyõzõ",
"4.11.": "Károly",
"5.11.": "Imre",
"6.11.": "Lénárd",
"7.11.": "Rezsõ",
"8.11.": "Zsombor",
"9.11.": "Tivadar",
"10.11.": "Réka",
"11.11.": "Márton",
"12.11.": "Jónás,Renátó",
"13.11.": "Szilvia",
"14.11.": "Aliz",
"15.11.": "Albert,Lipót",
"16.11.": "Ödön",
"17.11.": "Gergõ,Hortenzia",
"18.11.": "Jenõ",
"19.11.": "Erzsébet",
"20.11.": "Jolán",
"21.11.": "Olivér",
"22.11.": "Cecília",
"23.11.": "Kelemen,Klementina",
"24.11.": "Emma",
"25.11.": "Katalin",
"26.11.": "Virág",
"27.11.": "Virgil",
"28.11.": "Stefánia",
"29.11.": "Taksony",
"30.11.": "Andor,András",
"1.12.": "Elza",
"2.12.": "Melinda,Vivien",
"3.12.": "Ferenc,Olívia",
"4.12.": "Barbara,Borbála",
"5.12.": "Vilma",
"6.12.": "Miklós",
"7.12.": "Ambrus",
"8.12.": "Mária",
"9.12.": "Natália",
"10.12.": "Judit",
"11.12.": "Árpád",
"12.12.": "Gabriella",
"13.12.": "Luca,Otília",
"14.12.": "Szilárda",
"15.12.": "Valér",
"16.12.": "Aletta,Etelka",
"17.12.": "Lázár,Olimpia",
"18.12.": "Auguszta",
"19.12.": "Viola",
"20.12.": "Teofil",
"21.12.": "Tamás",
"22.12.": "Zénó",
"23.12.": "Viktória",
"24.12.": "Ádám,Éva",
"25.12.": "Eugénia",
"26.12.": "István",
"27.12.": "János",
"28.12.": "Kamilla",
"29.12.": "Tamara,Tamás",
"30.12.": "Dávid",
"31.12.": "Szilveszter"
				}';
				$names_array = json_decode($ndjson);
				return $names_array;				
			} 	

}
?>