<?php
namespace COUPONEMAILS;

class Coupon_Emails_Calendars
{	
			public function get_slovak_namedays_array()
			{
				$ndjson = '{
		 "1.1.": "Nový rok",
		 "2.1.": "Alexandra, Karina, Ábel, Makar, Karin, Kara, Kasandra, Sanda, Sandra, Saša, Senda",
		 "3.1.": "Daniela, Danila, Danuta, Genovéva, Radmila",
		 "4.1.": "Drahoslav, Drahoľub, Drahomil, Drahoň, Drahoš, Duchoslav, León, Títus, Drahoľuba, Drahomila, Duchoslava, Leóna, Leónia",
		 "5.1.": "Andrea, Artúr",
		 "6.1.": "Antónia, Melchior, Melichar, Menhard",
		 "7.1.": "Bohuslava, Atila, Lucián, Bohuna, Boleslava, Božislava, Luciána",
		 "8.1.": "Severín, Čestmír, Pravomil, Čestmíra, Pravomila, Severína",
		 "9.1.": "Alexej, Alex, Domoľub, Julián, Pravoľub, Vladan, Vladen, Alexia, Pravoľuba, Vladana, Vladena",
		 "10.1.": "Dáša, Agatón, Dalimil, Dalimír, Dalimila, Dalimíra",
		 "11.1.": "Malvína, Honorát, Tasilo, Honoráta",
		 "12.1.": "Ernest, Arkád, Arnošt, Arkádia, Arnoštka, Erna, Ernestína",
		 "13.1.": "Rastislav, Čistomil, Čistoslav, Rastic, Rastimír, Ratislav, Vidor, Čistomila, Čistoslava, Rastislava, Ratislava",
		 "14.1.": "Radovan, Hilár, Uriáš, Uriel, Hilária, Radovana",
		 "15.1.": "Dobroslav, Dobrotín, Domoslav, Loránt, Múdroslav, Domoslava",
		 "16.1.": "Kristína",
		 "17.1.": "Nataša, Antal",
		 "18.1.": "Bohdana, Priskus, Piroška, Priska",
		 "19.1.": "Drahomíra, Mário, Sára, Márius, Dúbravka",
		 "20.1.": "Dalibor, Fabián, Fábius, Sebastián, Šebastián, Fábia, Fabiána, Fabiola, Sebastiána",
		 "21.1.": "Vincent, Vincencia",
		 "22.1.": "Zora, Dorián, Sírius, Slavoľub, Slavomil, Zoran, Auróra, Cyntia, Doriána, Sinda, Slavomila, Zorana",
		 "23.1.": "Miloš, Miloň, Selma",
		 "24.1.": "Timotej, Ctiboh, Timotea",
		 "25.1.": "Gejza, Saul, Šavol",
		 "26.1.": "Tamara, Polykarp, Slavibor, Slavislav, Slaviboj, Slavoboj, Svätoboj, Svätobor, Xenofón, Žarko, Polykarpa",
		 "27.1.": "Bohuš, Pribislav, Pribiš",
		 "28.1.": "Alfonz, Manfréd, Alfonzia",
		 "29.1.": "Gašpar, Pribina",
		 "30.1.": "Ema, Jasna",
		 "31.1.": "Emil, Emilián, Emiliána",
        "1.2.": "Tatiana, Hynek, Trifon, Táňa",
        "2.2.": "Erik, Erika, Aida",
        "3.2.": "Blažej, Celerín, Celerína",
        "4.2.": "Veronika, Nika, Verena, Verona, Veronica",
        "5.2.": "Agáta, Moderát, Modest, Leda, Moderáta, Modesta",
        "6.2.": "Dorota, Dorisa, Titanila",
        "7.2.": "Vanda, Romuald",
        "8.2.": "Zoja, Aranka",
        "9.2.": "Zdenko, Rainold, Rinaldo, Zdeno, Apolena, Apoliena, Apolónia",
        "10.2.": "Gabriela, Scholastika, Školastika",
        "11.2.": "Dezider, Želislav, Dezidera, Želislava",
        "12.2.": "Perla, Ron, Ronald, Zoro, Zoroslav, Eulália, Slavena, Solveiga, Zoroslava",
        "13.2.": "Arpád, Jordán, Jordána",
        "14.2.": "Valentín, Velimír",
        "15.2.": "Pravoslav, Faust, Faustína, Georgia, Georgína, Pravoslava",
        "16.2.": "Ida, Liana, Pamfil, Pamfília",
        "17.2.": "Miloslava, Flavián, Flávius, Silván, Silvín, Flávia, Milomíra, Miluša, Silvána",
        "18.2.": "Jaromír, Simeon, Jaromíra, Konkordia, Bernadetta",
        "19.2.": "Vlasta, Konrád, Kurt",
        "20.2.": "Lívia, Aladár, Lívio, Lívius, Udo, Ulrich, Alma, Ulrika, Ulriška",
        "21.2.": "Eleonóra",
        "22.2.": "Etela",
        "23.2.": "Roman, Romana, Romina",
        "24.2.": "Matej, Jazmína, Goran, Mateja",
        "25.2.": "Frederik, Frederika, Taras, Federika",
        "26.2.": "Viktor, Porfýr, Edina",
        "27.2.": "Alexander, Leander, Sandro, Skender, Drahotína, Dražica, Leandra",
        "28.2.": "Zlatica, Elemír, Elo, Lumír, Zlata",
        "29.2.": "Radomír",
        "1.3.": "Albín",
        "2.3.": "Anežka",
        "3.3.": "Bohumil, Bohumila, Ticián, Ginda, Kunigunda, Ticiána",
        "4.3.": "Kazimír, Gerazim, Romeo, Jadrana, Kazimíra",
        "5.3.": "Fridrich, Lucius, Teofil, Friderika, Teofila",
        "6.3.": "Radoslav, Radoslava, Fridolín, Koriolán, Radislav, Radovan, Felícia, Fridolína, Radislava",
        "7.3.": "Tomáš, Tomislav, Tomáška, Tomislava",
        "8.3.": "Alan, Alana",
        "9.3.": "Františka, Erhard",
        "10.3.": "Branislav, Bruno, Bratislav, Bronislav, Bratislava, Taras",
        "11.3.": "Angela, Angelika, Angel, Volfram, Algelína, Jurina",
        "12.3.": "Gregor, Teofan, Gregora, Gregoria, Gregorína",
        "13.3.": "Vlastimil, Kira, Rozína",
        "14.3.": "Matilda, Metaneta",
        "15.3.": "Svetlana,Agap, Belomír, Rodan, Roderich, Roderik, Torkvát, Agapa, Agapia, Rodana, Roderika",
        "16.3.": "Boleslav, Amos, Bolemír, Heribert, Bolemíra",
        "17.3.": "Ľubica, Ľuban, Ľuben, Zbignev, Zbyšek, Ľuba",
        "18.3.": "Eduard, Ctislav, Salvátor, Ctislava, Eduarda",
        "19.3.": "Jozef, Sibyla",
        "20.3.": "Víťazoslav, Klaudián, Klaudín, Klaudio, Klaudius, Víťazoslava",
        "21.3.": "Blahoslav, Blahoboj, Blahosej, Radek, Radko",
        "22.3.": "Beňadik, Benedikt, Oktavián, Oktávius, Benedikta, Benilda, Benita, Izolda, Oktávia",
        "23.3.": "Adrián, Apián, Dárius, Viktorián, Apia",
        "24.3.": "Gabriel",
        "25.3.": "Marián, Humbert, Anunciáta, Irida, Irisa",
        "26.3.": "Emanuel, Eman, Manuel, Emanuela, Manuela",
        "27.3.": "Alena, Rupert, Ruprecht, Dita",
        "28.3.": "Soňa, Ilarion",
        "29.3.": "Miroslav, Mieroslav, Bertold, Bertolda, Mieroslava",
        "30.3.": "Vieroslava, Vieroľub, Vieromil, Vieroslav",
        "31.3.": "Benjamín, Kvído, Balbína",
        "1.4.": "Hugo, Hugolín",
        "2.4.": "Zita, Áron",
        "3.4.": "Richard, Richarda",
        "4.4.": "Izidor, Izidora",
        "5.4.": "Miroslava, Mira",
        "6.4.": "Irena, Irína, Celestín, Ruben, Sixtus, Celestína, Venuša",
        "7.4.": "Zoltán, Armand, Herman, Rufínus, Rúfus, Armanda, Rufína, Rumjana",
        "8.4.": "Albert, Albertín, Albrecht, Valter, Alberta, Albertína, Albrechta",
        "9.4.": "Milena, Erhard, Mileva",
        "10.4.": "Igor, Ezechiel, Ivar, Ivor, Radomil, Igora, Radomila",
        "11.4.": "Július, Antip, Ariel, Ariela, Arleta, Leo, Lev",
        "12.4.": "Estera, Aster, Davorín, Zenon, Astéria",
        "13.4.": "Aleš, Artem, Artemon, Artemia, Artemida, Norma",
        "14.4.": "Justína, Hrdoslav, Hrdoš, Justín, Davorína, Hrdoslava, Justa",
        "15.4.": "Fedor, Fedora",
        "16.4.": "Dana, Danica",
        "17.4.": "Rudolf, Ralf, Rolf, Rudolfa, Rudolfína",
        "18.4.": "Valér, Apolón, Erich, Verner, Ilma",
        "19.4.": "Jela, Krescenc, Krescencia",
        "20.4.": "Marcel, Hvezdoň",
        "21.4.": "Ervín, Abelard, Adelard, Anzelm, Žitoslav, Anzelma, Ervína, Saskia, Žitoslava",
        "22.4.": "Slavomír, Slávo, Tvrdomír, Jelena, Noema",
        "23.4.": "Vojtech, Adalbert, Roger, Adalberta, Vojtecha, Vojteška",
        "24.4.": "Juraj, Fidél, Gaston, Georg, Helmut, Jorik, Jürgen, Deora, Fidélia, Jorga, Jorika, Juraja",
        "25.4.": "Marek, Izmael, Marko, Markus",
        "26.4.": "Jaroslava",
        "27.4.": "Jaroslav, Aristid, Tulius, Aristída, Tulia",
        "28.4.": "Jarmila, Prudencius, Prudencia",
        "29.4.": "Lea, Timon",
        "30.4.": "Anastázia, Anastáz, Blahomil, Asia, Blahomila, Nasťa, Nastasia",
        "1.5.": "Amarila, Pamela, Kevin",
        "2.5.": "Žigmund, Atanáz, Atanázia, Aténa",
        "3.5.": "Galina, Horác, Desana, Halina, Timea",
        "4.5.": "Florián, Flór, Aglája, Floriána, Florína, Pelagia",
        "5.5.": "Lesana, Gothard, Pius, Lesia, Pia, Toska",
        "6.5.": "Hermína, Ovídius, Radivoj, Tankréd, Elfrída, Frída, Herina, Mineta",
        "7.5.": "Monika, Napoleon, Stanimír, Mona",
        "8.5.": "Ingrida, Ina, Inga",
        "9.5.": "Roland, Rolanda",
        "10.5.": "Viktória, Armín, Armína, Beatrica",
        "11.5.": "Blažena, Miranda, Svatava",
        "12.5.": "Pankrác, Achiles",
        "13.5.": "Servác, Chraniboj, Chranibor, Chranislav, Servián, Chranislava, Imelda, Konzuela",
        "14.5.": "Bonifác",
        "15.5.": "Žofia, Brenda, Raisa, Sofia, Zosia",
        "16.5.": "Svetozár, Peregrín, Peregrína",
        "17.5.": "Gizela, Andronik, Ditmar, Paskal, Andronika, Paskália",
        "18.5.": "Viola",
        "19.5.": "Gertrúda, Gerda",
        "20.5.": "Bernard, Bernardín, Hviezdoslav, Bernadeta, Bernarda, Bernardína, Hviezdoslava",
        "21.5.": "Zina, Dobromír, Hostimil, Hostirad, Hostislav, Hostisvit, Teobald, Dobromíra, Hostimila, Hostislava",
        "22.5.": "Júlia, Juliána, Liana, Rita",
        "23.5.": "Želmíra, Želmír, Želimír",
        "24.5.": "Ela",
        "25.5.": "Urban, Vselovod, Vševlad, Vanesa",
        "26.5.": "Dušan",
        "27.5.": "Iveta, Vadim, Valdemar, Valdemara",
        "28.5.": "Viliam, Vilhelm, Elektra, Elma, Vilhelmína",
        "29.5.": "Vilma, Elmar, Maxim, Maxima",
        "30.5.": "Ferdinand, Neander, Ferdinanda",
        "31.5.": "Petrana, Petronela, Petrónius, Blahoslav, Nela, Petrónia, Nelly",
        "1.6.": "Žaneta",
        "2.6.": "Oxana, Xénia, Erazim, Erazmus, Jaromil, Vlastimila",
        "3.6.": "Karolína, Kevin, Lino, Linus, Palmíro, Kaja, Klotilda, Lina, Lineta, Palmíra",
        "4.6.": "Lenka, Lena",
        "5.6.": "Laura, Dorotej, Fatima, Laurencia, Loreta, Loriána",
        "6.6.": "Norbert, Norman, Romulus, Adolfína, Norberta, Perzida",
        "7.6.": "Róbert, Borislav, Robin, Teodot, Dalma, Oriána, Róberta, Robina",
        "8.6.": "Medard",
        "9.6.": "Stanislava, Felicián, Prímus, Vojeslav, Berenika, Vojeslava",
        "10.6.": "Margaréta, Gréta",
        "11.6.": "Dobroslava, Barnabáš, Dobrava, Dobrota, Dobrotína, Flóra, Pavoslava",
        "12.6.": "Zlatko, Svätoslav, Svetislav, Svetoslav, Zlatan, Zlatomír, Zlatoň, Zlatoš, Svätoslava, Svetislava, Svetoslava, Zlatana, Zlatomíra",
        "13.6.": "Anton, Genadij, Tobiáš",
        "14.6.": "Vasil, Bazil, Elizej, Kvintilián, Kvintín, Kvintus, Herta, Kvinta, Kvintiliána",
        "15.6.": "Vít, Jolana",
        "16.6.": "Bianka, Blanka, Benon, Božetech, Alina, Božetecha",
        "17.6.": "Adolf, Adolfína",
        "18.6.": "Vratislav, Leontín, Milovan, Milovín, Sedrik, Leontína, Milovana",
        "19.6.": "Alfréd, Leonid, Leonídas, Leoš, Ruslan, Alfréda",
        "20.6.": "Valéria, Florencián, Florentín, Silver, Florencia, Florentína",
        "21.6.": "Alojz, Elvis, Lejla",
        "22.6.": "Paulína, Achác, Eberhard, Paulín, Paula, Rozvita, Zaira",
        "23.6.": "Sidónia, Sidón",
        "24.6.": "Ján, Janis, Jaško, Jens, Johan, Jovan, Nino, Sean",
        "25.6.": "Tadeáš, Olívia, Olívius, Prosper, Febrónia, Oliva",
        "26.6.": "Adriána, Stojan, Adriena, Ria, Riana, Stojana",
        "27.6.": "Ladislav, Ladislava, Samson, Sulamita",
        "28.6.": "Beáta, Beátus, Slavoj, Bea",
        "29.6.": "Peter, Pavol, Petra, Pavel, Pavla, Petula",
        "30.6.": "Melánia, Vlastibor, Vlastimír, Šárka, Vlastimíra",
        "1.7.": "Diana, Dean, Dejan, Dina, Zian, Dajana, Deana, Kalina, Tabita, Tajana, Annamária",
        "2.7.": "Berta, Bertín, Bertína",
        "3.7.": "Miloslav, Irenej, Miliduch, Milomír, Milorad, Radimír, Rodimír, Radimíra",
        "4.7.": "Prokop, Procius, Prokopa",
        "5.7.": "Cyril, Metod, Cyrus, Cyrila",
        "6.7.": "Patrik, Patrícia, Patrokles",
        "7.7.": "Oliver, Donald, Kastor, Veleslav, Velislav, Valibals, Veleslava, Velislava",
        "8.7.": "Ivan, Ivo, Kilián, Perikles",
        "9.7.": "Lujza, Lukrécius, Lizelota, Lukrécia",
        "10.7.": "Amália, Amína, Lada",
        "11.7.": "Milota, Milutín",
        "12.7.": "Nina, Fortunát, Fortunáta",
        "13.7.": "Margita, Arne, Borivoj, Merkéta",
        "14.7.": "Kamil",
        "15.7.": "Henrich, Egon, Enrik, Enriko, Henrik, Henrika, Lota, Šarlota",
        "16.7.": "Drahomír, Karmela, Karmen, Karmena, Rút, Rúta",
        "17.7.": "Bohuslav, Božislav, Svorad",
        "18.7.": "Kamila",
        "19.7.": "Dušana",
        "20.7.": "Eliáš, Iľja, Ilia, Eliána, Iliana",
        "21.7.": "Daniel, Dan, Dalina",
        "22.7.": "Magdaléna, Magda, Mahuliena, Majda",
        "23.7.": "Oľga, Apolinár, Libérius, Libor, Liborius, Apolinára, Libora, Lilien",
        "24.7.": "Vladimír, Vlado, Kinga",
        "25.7.": "Jakub, Kubo, Žakelína",
        "26.7.": "Anna, Hana, Aneta, Anica, Anita, Annamária, Naneta",
        "27.7.": "Božena, Gorazd, Pantaleon",
        "28.7.": "Krištof, Inocent, Svätomír, Svätoš, Inocencia, Nausika, Svätomíra",
        "29.7.": "Marta, Olaf, Serafín, Serafa, Serafína",
        "30.7.": "Libuša, Abdon, Ingemar, Ingeborga, Ľubuša, Rowena",
        "31.7.": "Ignác, Ignát, Vatroslav, Ignácia",
        "1.8.": "Božidara, Božidar, Ľudomír, Božica, Kleopatra, Ľudomíra, Penelopa",
        "2.8.": "Gustáv, Gustáva",
        "3.8.": "Jerguš, Nikodém, Nikodéma",
        "4.8.": "Dominik, Dominika, Krasoslav, Rainer, Krasoslava",
        "5.8.": "Hortenzia, Hortenz, Milivoj, Osvald, Snežana",
        "6.8.": "Jozefína, Nehoslav, Jozefa",
        "7.8.": "Štefánia, Kajetán, Afra, Afrodita, Kajetána, Štefana",
        "8.8.": "Oskár, Donát, Hartvig, Virgín, Donáta, Virgínia",
        "9.8.": "Ľubomíra, Rastic",
        "10.8.": "Vavrinec, Lars, Laurenc, Laurus, Lorenc, Vavro",
        "11.8.": "Zuzana, Trojan, Dulcia, Dulcinela, Dulcínia",
        "12.8.": "Darina, Dárius, Dária",
        "13.8.": "Ľubomír, Hypolit, Kasián, Kasius, Belinda",
        "14.8.": "Mojmír, Eusébius, Mojtech, Eusébia",
        "15.8.": "Marcela",
        "16.8.": "Leonard, Jáchim, Joachim, Linhart, Rochus, Leonarda",
        "17.8.": "Milica, Bertram, Bertrand, Hyacint, Libert, Mirón, Hyacinta",
        "18.8.": "Elena, Helena, Ilona",
        "19.8.": "Lýdia, Vratislava",
        "20.8.": "Anabela, Arabela",
        "21.8.": "Jana, Johana, Jovana",
        "22.8.": "Tichomír, Sigfríd, Tichomil, Tichomíra",
        "23.8.": "Filip, Vlastislav, Filipa, Filipína, Vlastislava",
        "24.8.": "Bartolomej, Bartolomea",
        "25.8.": "Ľudovít, Ludvig, Radim, Ľudovíta",
        "26.8.": "Samuel, Samo, Zemfír, Samuela, Tália, Zemfíra",
        "27.8.": "Silvia, Silvio, Silvius",
        "28.8.": "Augustín, August, Augusta, Augustína, Gustína",
        "29.8.": "Nikola, Nikolaj, Koleta, Nikoleta, Nikol",
        "30.8.": "Ružena, Ružica",
        "31.8.": "Nora, Rajmund, Ramón, Rajmunda, Ramona",
        "1.9.": "Drahoslava, Egid, Egídius",
        "2.9.": "Linda, Absolón, Axel, Justus, Ermelinda, Melinda, Rebeka",
        "3.9.": "Belo, Antim, Klélia",
        "4.9.": "Rozália, Kandid, Mojžiš, Rozalín, Rozálio, Kandida, Róza, Rozeta, Rozita, Rusalka",
        "5.9.": "Regína, Bojan, Bojimír, Bojislav, Borimír, Branimír, Chotimír, Justinián, Otakar, Regan, Regulus, Viktorín, Bojana, Bojimíra, Boislava, Branimíra, Budislava, Chotimíra, Larisa",
        "6.9.": "Alica, Brian, Magnus, Mansvét, Zachariáš, Bria",
        "7.9.": "Marianna, Mariana",
        "8.9.": "Miriama, Miriana",
        "9.9.": "Martina, Gordan, Gordián, Gordon, Omar, Gordana, Rea, Tina",
        "10.9.": "Oleg, Honór, Vitold, Honóra, Krasava, Vitolda",
        "11.9.": "Bystrík, Prótus, Zdislav, Helga, Zdislava",
        "12.9.": "Mária, Maja, Manon, Manona, Marica, Mariela, Marieta, Marika, Marila, Mariola, Marlena, Marusia",
        "13.9.": "Ctibor, Amát, Amátus, Stibor, Sven, Amáta, Tobias",
        "14.9.": "Ľudomil, Dragan, Dragutín, Drahan, Drahotín, Ľudomila, Radka, Serena",
        "15.9.": "Jolana, Melisa, Melita",
        "16.9.": "Ľudmila, Duňa",
        "17.9.": "Olympia, Lambert, Záviš",
        "18.9.": "Eugénia, Ariadna",
        "19.9.": "Konštantín, Trofín, Konstancia, Konštantína",
        "20.9.": "Ľuboslav, Ľuboslava, Eustach, Filibert, Liboslav, Eustachia, Liboslava",
        "21.9.": "Matúš, Ifigénia, Mirela",
        "22.9.": "Móric, Maurícius, Maurus",
        "23.9.": "Zdenka, Polyxénia, Tekla, Zdena",
        "24.9.": "Ľubor, Ľuboš, Terenc",
        "25.9.": "Vladislav, Vladivoj, Eufrozina, Fruzína, Vladislava",
        "26.9.": "Edita",
        "27.9.": "Cyprián, Damián, Kozmas, Damiána, Mirabela",
        "28.9.": "Václav, Chariton, Kariton, Václava",
        "29.9.": "Michal, Michaela, Michael, Michala",
        "30.9.": "Jarolím, Hieronym, Jeremiáš, Jarolíma, Ráchel, Ráchela, Una",
        "1.10.": "Arnold, Remig, Remus, Arnolda, Belina",
        "2.10.": "Levoslav, Leodegar, Levoslava",
        "3.10.": "Stela, Amadeus, Evald, Amadea",
        "4.10.": "František, Edvin, Fraňo",
        "5.10.": "Viera, Blahomír, Placid, Blahomíra, Karitína, Placida",
        "6.10.": "Natália",
        "7.10.": "Eliška",
        "8.10.": "Brigita, Brit, Brita",
        "9.10.": "Dionýz, Dionýzia",
        "10.10.": "Slavomíra, Gedeon, Záboj, Krasomila",
        "11.10.": "Valentína, Belín, Zvonimír, Zvonislav, Bruna, Brunhilda, Luneta, Selena, Zvonimíra, Zvonislava",
        "12.10.": "Maximilián, Max, Maximiliána",
        "13.10.": "Koloman, Edgar",
        "14.10.": "Boris, Borislav, Kalist, Borislava, Kalista",
        "15.10.": "Terézia, Tereza",
        "16.10.": "Vladimíra, Gál, Havel, Havla",
        "17.10.": "Hedviga, Jadviga",
        "18.10.": "Lukáš",
        "19.10.": "Kristián, Christián, Izák, Christiána, Kristiána",
        "20.10.": "Vendelín, Eunika, Vendelína",
        "21.10.": "Uršuľa, Anatol, Anatólia, Antília",
        "22.10.": "Sergej, Dobromil, Sergius, Zdravomil, Kordula, Korduľa, Pribislava, Saloma, Saloména, Solomia",
        "23.10.": "Alojzia, Žitomír",
        "24.10.": "Kvetoslava, Aretas, Cvetan, Gilbert, Harold, Herald, Krasomil, Kvetoň, Kvetoslav, Rafael, Šalamún, Areta, Cvetana, Gilberta, Kveta, Kvetana, Kvetava, Rafaela",
        "25.10.": "Aurel, Krišpín, Vojmír, Zosim, Živan, Živko, Dália, Vojmíra, Živa, Živana",
        "26.10.": "Demeter, Amand, Dimitrij, Evarist, Amanda, Demetria",
        "27.10.": "Sabína, Horislav, Hromislav, Horislava, Hromislava, Sabrina, Zoa, Zoana",
        "28.10.": "Dobromila, Júda, Judáš",
        "29.10.": "Klára, Narcis, Zenob, Klarisa, Narcisa, Zenóbia, Kiara",
        "30.10.": "Šimon, Simona, Arzen, Asen, Simon, Asena, Simoneta, Šimona",
        "31.10.": "Aurélia, Stacho, Volfgang",
        "1.11.": "Denis, Denisa",
        "2.11.": "Cézar, Cezária",
        "3.11.": "Hubert",
        "4.11.": "Karol, Džesika, Jesika, Karola, Skarleta",
        "5.11.": "Imrich, Emerich, Imriška",
        "6.11.": "Renáta, Renát, Renáto, Renátus",
        "7.11.": "René, Engelbert",
        "8.11.": "Bohumír, Bohumíra",
        "9.11.": "Teodor, Orest, Teo, Teodorik, Teodoz, Deodata, Tea, Teodora, Teodózia",
        "10.11.": "Tibor, Tiber, Meluzína, Tibora",
        "11.11.": "Maroš, Martin, Martinián",
        "12.11.": "Svätopluk, Astrid, Jonáš, Astrida",
        "13.11.": "Stanislav",
        "14.11.": "Irma, Juventín, Mladen, Mladoň, Mladotín, Ima, Juventína, Mladena, Mladotína",
        "15.11.": "Leopold, Leopolda, Leopoldína",
        "16.11.": "Agnesa, Otmar, Agneša, Inéza",
        "17.11.": "Klaudia, Klodeta",
        "18.11.": "Eugen, Platón",
        "19.11.": "Alžbeta, Betina, Elizabeta, Lila, Liliana, Líza, Lili, Lilly",
        "20.11.": "Félix, Filemon, Homér",
        "21.11.": "Elvíra, Ctirad, Ctirada",
        "22.11.": "Cecília, Cecilián, Šejla",
        "23.11.": "Klement, Klementín, Kliment, Kolumbín, Klementína, Kolumbína",
        "24.11.": "Emília, Milín, Milina",
        "25.11.": "Katarína, Katrina",
        "26.11.": "Kornel, Valerián",
        "27.11.": "Milan, Nestor, Virgil, Milana",
        "28.11.": "Henrieta, Gerhard, Tristan, Desdemona, Eta",
        "29.11.": "Vratko, Saturnín, Zaida",
        "30.11.": "Andrej, Ondrej, Andreas",
        "1.12.": "Edmund, Edmunda",
        "2.12.": "Bibiána, Budimír, Budislav, Budimíra, Viviána",
        "3.12.": "Oldrich, Sofron, Xavér, Sofrónia, Xavéria",
        "4.12.": "Barbora, Babeta, Barbara, Barica",
        "5.12.": "Oto, Gerald, Otakar, Otokar, Geralda, Geraldína, Jitka, Ota, Sáva",
        "6.12.": "Mikuláš, Nikita, Niko, Nikolas, Mikuláška, Nikoleta",
        "7.12.": "Ambróz, Amarant, Amaranta, Ambrózia",
        "8.12.": "Marína",
        "9.12.": "Izabela, Dalila, Leokádia",
        "10.12.": "Radúz, Herbert",
        "11.12.": "Hilda, Hildegard, Hildegarda",
        "12.12.": "Otília, Spiridon, Dília, Odeta",
        "13.12.": "Lucia, Rosan, Rosana, Roxana",
        "14.12.": "Branislava, Bronislava, Broňa",
        "15.12.": "Ivica, Detrich, Radan, Radana",
        "16.12.": "Albína, Bela, Teofánia",
        "17.12.": "Kornélia, Lazár, Kora, Korina",
        "18.12.": "Sláva, Slávka, Gracián, Grácia, Graciána, Slavislava",
        "19.12.": "Judita, Abrahám, Mstislav, Neméz, Ita, Mstislava, Neméza",
        "20.12.": "Dagmara, Dagmar, Dag, Dagobert, Daga, Damara",
        "21.12.": "Bohdan",
        "22.12.": "Adela, Ada, Adelaida, Adelgunda, Adelína, Adina, Alida",
        "23.12.": "Nadežda, Naďa",
        "24.12.": "Adam, Eva, Evamária, Evelína, Gaja, Gajana, Geja",
        "25.12.": "1. sviatok vianočný",
        "26.12.": "Štefan",
        "27.12.": "Filoména, Filomén",
        "28.12.": "Ivana, Ivona, Iva",
        "29.12.": "Milada, Jonatán, Miladín, Nátan, Natanel",
        "30.12.": "Dávid, Lotar",
        "31.12.": "Silvester, Horst"					
				}'; 
				$names_array = json_decode($ndjson);
				return $names_array;				
			}		
			public function get_czech_namedays_array(){
				$ndjson = '{
"1.1.": "Mečislav",
"2.1.": "Karina,Vasil",
"3.1.": "Radmila,Radomil,Jenovéfa,Jenifer",
"4.1.": "Diana,Dajana,Deana",
"5.1.": "Dalimil,Dylan",
"6.1.": "Kašpar,Melichar,Baltazar",
"7.1.": "Vilma,Vilemína,Atila",
"8.1.": "Čestmír,Erhard",
"9.1.": "Vladan,Valtr,Vlaďka,Vladana",
"10.1.": "Břetislav,Břetislava",
"11.1.": "Bohdana,Teodora",
"12.1.": "Pravoslav,Pravoslava",
"13.1.": "Edita,Leontýna",
"14.1.": "Radovan,Radovana",
"15.1.": "Alice,Severín",
"16.1.": "Ctirad,Ctislav",
"17.1.": "Drahoslav,Drahoš",
"18.1.": "Vladislav,Vladislava,Priska",
"19.1.": "Doubravka,Fabián",
"20.1.": "Ilona,Sebastián",
"21.1.": "Běla,Bianka,Géza",
"22.1.": "Slavomír,Slavomíra,Slávek",
"23.1.": "Zdeněk,Raimund,Ramon",
"24.1.": "Milena,Amanda,Tim",
"25.1.": "Miloš,Miloň",
"26.1.": "Zora,Zoran,Danica,Aurora",
"27.1.": "Ingrid,Ingeborg,Inka",
"28.1.": "Otýlie,Manfréd",
"29.1.": "Zdislava,Zdislav",
"30.1.": "Robin,Erna",
"31.1.": "Marika,Marieta",
"1.2.": "Hynek,Jasmína",
"2.2.": "Nela,Aida",
"3.2.": "Blažej,Donald",
"4.2.": "Jarmila,Gilbert",
"5.2.": "Dobromila,Dobromil",
"6.2.": "Vanda,Samanta",
"7.2.": "Veronika,Verona,Berenika",
"8.2.": "Milada,Aranka,Mlada",
"9.2.": "Apolena,Ronald",
"10.2.": "Mojmír,Mojmíra",
"11.2.": "Božena,Dezider",
"12.2.": "Slavěna,Slávka,Glorie",
"13.2.": "Věnceslav,Věnceslava,Jordan",
"14.2.": "Valentýn,Valentýna",
"15.2.": "Jiřina,Jorga,Jorika",
"16.2.": "Ljuba,Luba,Danuta",
"17.2.": "Miloslava,Grácie,Fiona",
"18.2.": "Gizela,Flavie",
"19.2.": "Patrik,Konrád",
"20.2.": "Oldřich,Dorián",
"21.2.": "Lenka,Eleonora,Lena",
"22.2.": "Petr,Etela",
"23.2.": "Svatopluk,Svatobor",
"24.2.": "Matěj,Matyáš",
"25.2.": "Liliana,Valburga,Taras,Nevena",
"26.2.": "Dorota,Dora,Doris,Božetěch",
"27.2.": "Alexandr,Torsten",
"28.2.": "Lumír,Lumíra,Kira",
"29.2.": "Horymír",
"1.3.": "Bedřich,Bedřiška,Dětřich",
"2.3.": "Anežka,Inéz,Inesa",
"3.3.": "Kamil,Vladivoj",
"4.3.": "Stela,Jadranka",
"5.3.": "Kazimír,Kazimíra",
"6.3.": "Miroslav,Mirek,Fridolín",
"7.3.": "Tomáš,Tom,Tomislav",
"8.3.": "Gabriela,Zoltán,Merlin",
"9.3.": "Františka,Rebeka,Radúz",
"10.3.": "Viktorie,Melita,Melisa,Ildika",
"11.3.": "Anděla,Angelika,Anděl",
"12.3.": "Řehoř",
"13.3.": "Růžena,Roza,Rosana",
"14.3.": "Rút,Matylda,Maud",
"15.3.": "Ida,Hilda,Longin",
"16.3.": "Elena,Herbert,Amos",
"17.3.": "Vlastimil,Vlastimila",
"18.3.": "Eduard,Eduarda",
"19.3.": "Josef,Josefa,Sibyla",
"20.3.": "Světlana,Světla,Roxana",
"21.3.": "Radek,Radko",
"22.3.": "Leona,Lea,Leokádie,Leonie",
"23.3.": "Ivona,Alfons,Axel",
"24.3.": "Gabriel,Zbyslav",
"25.3.": "Marián,Mario,Marius",
"26.3.": "Emanuel,Emanuela,Manuel,Manuela",
"27.3.": "Dita,Malvína,Rupert",
"28.3.": "Soňa,Gedeon",
"29.3.": "Taťána,Slavomil,Slavomila",
"30.3.": "Arnošt,Ernest,Arnold,Arnoštka,Arne,Arna",
"31.3.": "Kvido,Quido,Arpád",
"1.4.": "Hugo,Veleslav,Velen",
"2.4.": "Erika,Aron",
"3.4.": "Richard,Richarda",
"4.4.": "Ivana,Izidor",
"5.4.": "Miroslava,Mirka,Mira",
"6.4.": "Vendula,Venuše",
"7.4.": "Heřman,Hermína,Armin,Armand,Mína,",
"8.4.": "Ema,Konstantina",
"9.4.": "Dušan,Dušana,Dustin",
"10.4.": "Darja,Darie",
"11.4.": "Izabela,Ratmír,Ariel",
"12.4.": "Julius,Julián,Zenon",
"13.4.": "Aleš,Aleška,Norma",
"14.4.": "Vincenc,Vincent,Pravomil,Pravomila",
"15.4.": "Anastázie,Oktavián",
"16.4.": "Irena,Erina,Ireneus",
"17.4.": "Rudolf,Rudolfa,Rolf,Ralf,Raul,",
"18.4.": "Valérie,Verner,Valer",
"19.4.": "Rostislav,Rastislav,Timon",
"20.4.": "Marcela,Odeta,Celina",
"21.4.": "Alexandra,Selma",
"22.4.": "Evženie,Leonid",
"23.4.": "Vojtěch,Vojtěška,Gerhard,Garik",
"24.4.": "Jiří,Fidel",
"25.4.": "Marek,Ervín,Ervína",
"26.4.": "Oto,Ota,Uve,Udo",
"27.4.": "Jaroslav,Jarolím",
"28.4.": "Vlastislav,Vlastislava,Paris",
"29.4.": "Robert,Roberta,Roderik,Roger",
"30.4.": "Blahoslav,Blahoslava,Blahomír,Blahomil",
"1.5.": "Jeremiáš,Pamela",
"2.5.": "Zikmund,Atanas",
"3.5.": "Alexej,Alexa,Alexie",
"4.5.": "Květoslav,Florián",
"5.5.": "Klaudie,Klaudius",
"6.5.": "Radoslav,Radislav",
"7.5.": "Stanislav,Stojan",
"8.5.": "Zlatan,Zlatko,Zlatomír,Aurel",
"9.5.": "Ctibor,Honoráta",
"10.5.": "Blažena,Gordon",
"11.5.": "Svatava,Svatoslava,Svatomíra",
"12.5.": "Pankrác,Vsevolod",
"13.5.": "Servác,Ofélie",
"14.5.": "Bonifác,Dina",
"15.5.": "Žofie,Sofie,Harald",
"16.5.": "Přemysl,Přemek,Přemyslav",
"17.5.": "Aneta,Paskal,Dětmar",
"18.5.": "Nataša,Timea",
"19.5.": "Ivo,Celestýn,Alvin",
"20.5.": "Zbyšek",
"21.5.": "Monika,Mona",
"22.5.": "Emil,Rita,Emilián",
"23.5.": "Vladimír,Vladimíra,Želmíra",
"24.5.": "Jana,Vanesa",
"25.5.": "Viola,Violeta,Urban",
"26.5.": "Filip,Filipa,Filipína",
"27.5.": "Valdemar,Vadim,Vojslav",
"28.5.": "Vilém,Viliam,Vilibald",
"29.5.": "Maxmilián,Maxim,Max",
"30.5.": "Ferdinand,Elmar",
"31.5.": "Kamila,Nila",
"1.6.": "Laura,Lora,Loreta",
"2.6.": "Jarmil,Jaromil",
"3.6.": "Tamara,Kevin,Lešek",
"4.6.": "Dalibor,Tara,Fatima",
"5.6.": "Dobroslav,Dobroslava,Dobruše",
"6.6.": "Norbert,Norman",
"7.6.": "Iveta,Slavoj,Slavibor",
"8.6.": "Medard,Pěva",
"9.6.": "Stanislava,Anabela",
"10.6.": "Gita,Margita,Gréta",
"11.6.": "Bruno,Barnabáš,Brunhilda",
"12.6.": "Antonie,Táňa",
"13.6.": "Antonín,Genadij",
"14.6.": "Roland,Herta,Rolanda",
"15.6.": "Vít,Víta,Senta",
"16.6.": "Zbyněk,Zbyhněv,Zbyňka",
"17.6.": "Adolf,Adina,Adolfina,Ada",
"18.6.": "Milan,Milana,Milíč",
"19.6.": "Leoš,Leo,Leon,Lev,Ruslan,",
"20.6.": "Květa,Květuše,Flora",
"21.6.": "Alois,Aloisie,Lejla",
"22.6.": "Pavla,Zaira,Arabela",
"23.6.": "Zdeňka,Zdena,Zdenka,Sidonie",
"24.6.": "Jan,Jonatan,Dejan",
"25.6.": "Ivan,Salome,Fabrizio",
"26.6.": "Adriana,Adrian",
"27.6.": "Ladislav,Ladislava",
"28.6.": "Lubomír,Lubomíra,Lubomil,Serena",
"29.6.": "Petr,Pavel,Esmeralda",
"30.6.": "Šárka,Vlastimír,Vlastimíra",
"1.7.": "Jaroslava,Vesna",
"2.7.": "Patricie,Alma",
"3.7.": "Radomír,Radomíra,Anatol",
"4.7.": "Prokop,Ulrich",
"5.7.": "Cyril,Metoděj",
"6.7.": "Spytihněv",
"7.7.": "Bohuslava,Hostivít",
"8.7.": "Nora,Edgar,Kilián",
"9.7.": "Drahoslava,Drahuše",
"10.7.": "Libuše,Amálie,Ludoslav,Ludoslava",
"11.7.": "Olga,Helga,Pius",
"12.7.": "Bořek,Borislav",
"13.7.": "Markéta,Margareta,Perla,Megan",
"14.7.": "Karolína,Larisa",
"15.7.": "Jindřich,Egon",
"16.7.": "Luboš,Cedrik,Carmen",
"17.7.": "Martina,Iris,Arleta",
"18.7.": "Drahomíra,Drahomír,Drahomila,Drahomil",
"19.7.": "Čeněk,Čeňka",
"20.7.": "Ilja,Eliáš,Eliana,Iljana",
"21.7.": "Vítězslav,Vítězslava",
"22.7.": "Magdaléna,Magda,Marlena,Rozvita",
"23.7.": "Libor,Liboslav,Libora,Liboslava",
"24.7.": "Kristýna,Tina,Gleb",
"25.7.": "Jakub,Timur",
"26.7.": "Anna,Anita,Nancy",
"27.7.": "Věroslav,Bertold",
"28.7.": "Viktor,Alina,Inocenc",
"29.7.": "Marta,Beatrice,Olaf",
"30.7.": "Bořivoj,Vojen",
"31.7.": "Ignác,Ignát",
"1.8.": "Oskar,Ludomír,Medea",
"2.8.": "Gustav,Elfrída,Gustava",
"3.8.": "Miluše,Nikodém,Jerguš",
"4.8.": "Dominik,Dominika,Rainer,Neda",
"5.8.": "Kristián,Milivoj,Osvald",
"6.8.": "Oldřiška,Ulrika,Něhoslav",
"7.8.": "Lada,Kajetán,Iboja",
"8.8.": "Soběslav,Virginie,Soběslava",
"9.8.": "Roman,Romeo,Ratibor,Ratislav",
"10.8.": "Vavřinec,Lars,Laurenc",
"11.8.": "Zuzana,Filoména",
"12.8.": "Klára,Jasna,Jasoň",
"13.8.": "Alena,Sven,Belinda",
"14.8.": "Alan,Alen",
"15.8.": "Hana,Mirela",
"16.8.": "Jáchym,Abrahám",
"17.8.": "Petra,Petronela,Petula,Záviš",
"18.8.": "Helena,Jelena,Ena",
"19.8.": "Ludvík,Ludvíka,Luisa",
"20.8.": "Bernard,Bernarda,Dino,Bernardina,Bernardeta,",
"21.8.": "Johana,Johanka,Noemi",
"22.8.": "Bohuslav,Božislav,Tichomír",
"23.8.": "Sandra,Tekla,Polyxena",
"24.8.": "Bartoloměj,Natanael",
"25.8.": "Radim,Radima,Elvíra",
"26.8.": "Luděk,Luďka,Ludiše",
"27.8.": "Otakar,Otakara",
"28.8.": "Augustýn,Augustýna,Augusta,Pelagie",
"29.8.": "Evelína,Miron,Myron",
"30.8.": "Vladěna,Kim,Kimberley",
"31.8.": "Pavlína,Bela,Aris",
"1.9.": "Linda,Samuel,Jiljí",
"2.9.": "Adéla,Adelína",
"3.9.": "Bronislav,Bronislava,Branislav,Branislava",
"4.9.": "Jindřiška,Rozálie",
"5.9.": "Boris,Bojan,Bojana",
"6.9.": "Boleslav,Boleslava",
"7.9.": "Regína,Gina,Rea",
"8.9.": "Mariana,Mariola,Marion",
"9.9.": "Daniela,Omar,Neklan,Gordana",
"10.9.": "Irma,Krasava",
"11.9.": "Denisa,Denis,Diviš,Dionýz,Bystrík,",
"12.9.": "Marie,Maja,Máša,Ria",
"13.9.": "Lubor,Melinda",
"14.9.": "Radka,Radoslava",
"15.9.": "Jolana,Jolanta,Dolores",
"16.9.": "Ludmila,Lidmila,Lola,Lolita,Kornelie,Kornel",
"17.9.": "Naděžda,Naďa,Lambert,Paloma",
"18.9.": "Kryštof,Ariana",
"19.9.": "Zita,Konstantin",
"20.9.": "Oleg,Helmut,Eustach",
"21.9.": "Matouš,Debora,Ruben",
"22.9.": "Darina,Moris,Mořic",
"23.9.": "Berta,Lina",
"24.9.": "Jaromír,Jaromíra,Mercedes",
"25.9.": "Zlata,Zlatuše",
"26.9.": "Andrea,Andriana",
"27.9.": "Jonáš,Damián",
"28.9.": "Václav,Václava,Brian",
"29.9.": "Michal,Michael,Rafael,Rafaela",
"30.9.": "Jeroným,Ráchel",
"1.10.": "Igor,Ivar,Ivor",
"2.10.": "Olivie,Oliver,Olympie",
"3.10.": "Bohumil,Bohuš",
"4.10.": "František,Evald",
"5.10.": "Eliška,Elza,Dalie",
"6.10.": "Hanuš,Hanuše",
"7.10.": "Justýna,Sergej,Justin",
"8.10.": "Věra,Věroslava,Taisa",
"9.10.": "Štefan,Sára,Zara",
"10.10.": "Marina,Marin,Záboj,Bivoj",
"11.10.": "Andrej,Andreas,André",
"12.10.": "Marcel,Edvín,Serafín",
"13.10.": "Renáta,Koloman,Gerald",
"14.10.": "Agáta,Háta,Krasoslav",
"15.10.": "Tereza,Terezie,Aurélie",
"16.10.": "Havel,Galina",
"17.10.": "Hedvika,Heda,Despina",
"18.10.": "Lukáš,Donovan",
"19.10.": "Michaela,Michala,Joel",
"20.10.": "Vendelín,Eunika,Kleopatra,Vendelína",
"21.10.": "Brigita,Uršula,Voršila,Birgita,Brit,Brita",
"22.10.": "Sabina,Sabrina,Korina,Kordula",
"23.10.": "Teodor,Teo,Fedor",
"24.10.": "Nina,Narcis,Narcisa",
"25.10.": "Beáta,Vojmír,Kryšpín",
"26.10.": "Erik,Erich",
"27.10.": "Šarlota,Zoe,Zoja,Lota,Živa,Živan",
"28.10.": "Alfréd,Alfréda",
"29.10.": "Silvie,Sylva,Silván",
"30.10.": "Tadeáš,Demeter,Hvězdoslav,Dimitrij",
"31.10.": "Štěpánka,Volfgang",
"1.11.": "Felix,Felície",
"2.11.": "Tobiáš,Jessica",
"3.11.": "Hubert,Teofil",
"4.11.": "Karel,Karla,Skarlet",
"5.11.": "Miriam,Emerich,Vědunka,Zacharíáš",
"6.11.": "Liběna,Leonard",
"7.11.": "Saskie,Engelbert",
"8.11.": "Bohumír,Bohumíra",
"9.11.": "Bohdan,Darek,Božidar",
"10.11.": "Evžen,Orest,Noe,Lionel",
"11.11.": "Martin,Davor",
"12.11.": "Benedikt,Beno,Astrid,Benedikta,Vitold,",
"13.11.": "Tibor,Brenda",
"14.11.": "Sáva,Mladen",
"15.11.": "Leopold,Leopoldina",
"16.11.": "Otmar,Otomar,Daisy",
"17.11.": "Mahulena,Gertruda,Edeltruda",
"18.11.": "Romana,Odon",
"19.11.": "Alžběta,Běta,Ilsa",
"20.11.": "Nikola,Nikol",
"21.11.": "Albert,Alberta,Aldo",
"22.11.": "Cecílie,Cindy",
"23.11.": "Klement,Klementina,Lukrécie",
"24.11.": "Emílie,Lothar",
"25.11.": "Kateřina,Katrin,Rina",
"26.11.": "Artur,Kurt,Konrád,Artuš,Aram,",
"27.11.": "Xenie,Oxana,Virgil",
"28.11.": "René,Renát,Tristan",
"29.11.": "Zina,Zinajda",
"30.11.": "Ondřej,Ondřejka",
"1.12.": "Iva,Edmund",
"2.12.": "Blanka,Bibiana,Vivien",
"3.12.": "Svatoslav,Svatomír,Xaver",
"4.12.": "Barbora,Barbara,Babeta",
"5.12.": "Jitka,Liana,Abigail",
"6.12.": "Mikuláš,Nikolas,Nikita",
"7.12.": "Ambrož,Benjamín",
"8.12.": "Květoslava,Květomila",
"9.12.": "Vratislav,Vratislava,Dalila",
"10.12.": "Julie,Juliána",
"11.12.": "Dana,Danuše",
"12.12.": "Simona,Šimona",
"13.12.": "Lucie,Lucián,Luciána",
"14.12.": "Lýdie,Livie,Liv",
"15.12.": "Radana,Radan,Zdirad",
"16.12.": "Albína,Albín",
"17.12.": "Daniel,Dan,Lazar,Chantal",
"18.12.": "Miloslav,Milorad",
"19.12.": "Ester,Darius,Mstislav",
"20.12.": "Dagmar,Dáša,Dag",
"21.12.": "Natálie,Rodan",
"22.12.": "Šimon,Simon,Simeon",
"23.12.": "Vlasta,Nika,Niké",
"24.12.": "Adam,Eva",
"25.12.": "Vánoce",
"26.12.": "Štěpán",
"27.12.": "Žaneta,Melánie",
"28.12.": "Bohumila,Donika",
"29.12.": "Judita,Natan,Juta",
"30.12.": "David,Donát",
"31.12.": "Silvestr,Silvestra,Horst,Forest"								
				}';
				$names_array = json_decode($ndjson);
				return $names_array;				
			} 
			public function get_austrian_namedays_array()
			{
				$ndjson = '{
"1.1.": "Maria,Wilhelm",
"2.1.": "Basilius,Dietmar,Gregor",
"3.1.": "Genoveva,Odilo",
"4.1.": "Angela,Marius,Rüdiger,Titus",
"5.1.": "Emilia,Johann",
"6.1.": "Erminold",
"7.1.": "Raimund,Valentin",
"8.1.": "Erhard,Gudula,Severin",
"9.1.": "Adrian,Alice,Eberhard,Julian",
"10.1.": "Leonie,Paulus",
"11.1.": "Paulin,Paulinus,Theodosius,Ronan",
"12.1.": "Ernst,Tatjana,Xenia",
"13.1.": "Hilarius,Hilmar,Jutta,Remigius",
"14.1.": "Engelmar,Felix,Rainer",
"15.1.": "Arnold,Maurus,Romedius",
"16.1.": "Dietwald,Marcel,Tilman",
"17.1.": "Antonius,Beatrix",
"18.1.": "Margitta,Ulfried,Uwe",
"19.1.": "Agritius,Marius,Martha,Pia",
"20.1.": "Fabianus,Sebastian,Ursula,Ute",
"21.1.": "Agnes,Ines,Meinrad",
"22.1.": "Vinzenz",
"23.1.": "Hartmut,Heinrich,Nikolaus",
"24.1.": "Franz,Thurid,Vera",
"25.1.": "Paulus,Wolfram",
"26.1.": "Paula,Timotheus,Titus",
"27.1.": "Angela,Julian",
"28.1.": "Caroline,Karoline,Manfred,Thomas",
"29.1.": "Gerhard,Gerd,Josef,Valerius",
"30.1.": "Adelgunde,Martina",
"31.1.": "Johannes,Marcella",
"1.2.": "Brigitta,Katharina,Reginald,Severus",
"2.2.": "Bodo",
"3.2.": "Ansgar,Blasius,Oskar",
"4.2.": "Andreas,Rabanus,Veronika",
"5.2.": "Agatha,Albuin",
"6.2.": "Dorothea,Doris,Paul",
"7.2.": "Ava,Richard",
"8.2.": "Hieronymus,Josefina,Josefine",
"9.2.": "Alto,Anna,Katharina,Apollonia",
"10.2.": "Scholastika,Siegmar",
"11.2.": "Anselm",
"12.2.": "Benedikt,Eulalia,Gregor",
"13.2.": "Adolf,Christina,Irmhild",
"14.2.": "Cyrill,Method,Valentin",
"15.2.": "Georgia,Siegfried",
"16.2.": "Adalbert,Juliana,Liane,Philippa",
"17.2.": "Alexius,Benignus,Bonosus",
"18.2.": "Constanze,Simon,Simone",
"19.2.": "Hadwig,Irmgard,Irma",
"20.2.": "Corona,Falko,Jacinta",
"21.2.": "Enrica,Gunthild,Petrus",
"22.2.": "Isabella",
"23.2.": "Raffaela,Romana",
"24.2.": "Matthias",
"25.2.": "Walburga",
"26.2.": "Edigna,Gerlinde,Ottokar",
"27.2.": "Baldur,Marko,Markward,Gabriel",
"28.2.": "Oswald,Roman,Silvana",
"29.2.": "Hilarius,Oswald",
"1.3.": "Albin,Leontina,Roger",
"2.3.": "Agnes,Karl",
"3.3.": "Friedrich,Camilla,Kunigunde",
"4.3.": "Edwin,Humbert,Kasimir",
"5.3.": "Dietmar,Jeremia,Olivia",
"6.3.": "Fridolin,Nicola,Rosa",
"7.3.": "Felicitas,Perpetua,Reinhard",
"8.3.": "Gerhard,Johannes",
"9.3.": "Bruno,Franziska",
"10.3.": "Emil,John,Gustav",
"11.3.": "Alram,Rosina",
"12.3.": "Almut,Beatrix,Serafina",
"13.3.": "Judith,Leander,Pauline",
"14.3.": "Eva,Evelyn,Mathilde",
"15.3.": "Clemens,Klemens,Maria,Luise",
"16.3.": "Eduard,Herbert",
"17.3.": "Gertraud,Gertrud,Patrick",
"18.3.": "Cyrill,Edward,Sibylle",
"19.3.": "Josef,Josefa,Josefine",
"20.3.": "Claudia,Wolfram",
"21.3.": "Alexandra,Axel,Christian,Emilia",
"22.3.": "Clemens,Klemens,Elmar,Lea",
"23.3.": "Otto,Rebekka,Toribio",
"24.3.": "Elias,Karin,Katharina",
"25.3.": "Judith,Lucia",
"26.3.": "Lara,Ludger",
"27.3.": "Ernst,Frowin,Heimo",
"28.3.": "Guntram,Ingbert",
"29.3.": "Berthold,Helmut,Ludolf",
"30.3.": "Amadeus,Dodo",
"31.3.": "Benjamin,Cornelia",
"1.4.": "Hugo,Irene,Irina",
"2.4.": "Franz,Mirjam,Sandra",
"3.4.": "Richard,Sixtus",
"4.4.": "Isidor,Konrad",
"5.4.": "Crescentia,Vinzenz",
"6.4.": "Notker,Wilhelm",
"7.4.": "Johann",
"8.4.": "Beate,Rose-Marie,Walter",
"9.4.": "Casilda,Waltraud",
"10.4.": "Ezechiel,Gernot,Holda",
"11.4.": "Hildebrand,Stanislaus",
"12.4.": "Herta,Julius,Zeno",
"13.4.": "Hermenegild,Ida,Martin",
"14.4.": "Elmo,Erna,Ernestine",
"15.4.": "Anastasia,Damian,Una",
"16.4.": "Bernadette,Magnus",
"17.4.": "Eberhard,Rudolph",
"18.4.": "Werner,Wigbert",
"19.4.": "Gerold,Leo,Marcel",
"20.4.": "Hildegund,Odetta,Wilhelm",
"21.4.": "Anselm,Konrad",
"22.4.": "Alfred,Kaj,Leonidas",
"23.4.": "Adalbert,Georg,Jörg,Jürgen",
"24.4.": "Egbert,Fidelis,Wilfried",
"25.4.": "Erwin,Markus",
"26.4.": "Helene,Trudpert",
"27.4.": "Petrus,Zita",
"28.4.": "Hugo,Ludwig,Pierre",
"29.4.": "Katharina,Roswitha",
"30.4.": "Pauline,Pius,Silvio",
"1.5.": "Josef",
"2.5.": "Athanasius,Boris,Siegmund",
"3.5.": "Jakob,Philipp,Viola",
"4.5.": "Florian,Guido,Valeria",
"5.5.": "Godehard,Jutta,Sigrid",
"6.5.": "Antonia,Britto,Gundula",
"7.5.": "Gisela,Helga,Notker,Silke",
"8.5.": "Ida,Klara,Ulla,Ulrike",
"9.5.": "Beatus,Caroline,Volkmar",
"10.5.": "Gordian,Isidor,Liliana",
"11.5.": "Gangolf,Joachim,Mamertus",
"12.5.": "Pankraz,Pankratius",
"13.5.": "Servatius",
"14.5.": "Bonifatius,Christian",
"15.5.": "Hertraud,Rupert,Sonja,Sophie",
"16.5.": "Adolf,Johann",
"17.5.": "Dietmar,Pascal,Walter",
"18.5.": "Erich,Erika,Felix,Johannes",
"19.5.": "Ivo,Kuno,Yvonne",
"20.5.": "Bernhardin,Elfriede,Mira",
"21.5.": "Christoph,Constantin,Josef,Julio",
"22.5.": "Julia,Ortwin,Rita",
"23.5.": "Alma,Desiree,Renate",
"24.5.": "Dagmar,Esther",
"25.5.": "Beda,Gregor,Magdalene",
"26.5.": "Alwin,Philipp",
"27.5.": "August,Bruno,Randolph",
"28.5.": "German,Wilhelm",
"29.5.": "Erwin,Irmtraud,Maximin",
"30.5.": "Ferdinand,Johanna,Otto",
"31.5.": "Helma,Mechthild,Petra",
"1.6.": "Justin,Silvana,Simeon,Ronan",
"2.6.": "Armin,Erasmus,Marcel,Petrus",
"3.6.": "Hildburg,Karl,Silvia",
"4.6.": "Christa,Iona,Klothilde",
"5.6.": "Erika,Winfried",
"6.6.": "Bertrand,Kevin,Norbert",
"7.6.": "Anita,Eoban,Gottlieb,Robert",
"8.6.": "Elga,Maria,Medardus",
"9.6.": "Annamaria,Ephraim,Grazia",
"10.6.": "Bardo,Diana,Heinrich,Heinz",
"11.6.": "Alice,Barnabas,Paula",
"12.6.": "Florinda,Guido,Leo",
"13.6.": "Antonius,Bernhard",
"14.6.": "Hartwig,Meinrad",
"15.6.": "Gebhard,Lothar,Veit",
"16.6.": "Benno,Luitgard,Quirin",
"17.6.": "Adolf,Alena,Volker",
"18.6.": "Elisabeth,Ilsa,Marina",
"19.6.": "Juliana,Romuald",
"20.6.": "Adalbert,Florentina",
"21.6.": "Alban,Alois,Aloisia,Ralf",
"22.6.": "Paulinus,Thomas",
"23.6.": "Edeltraud,Marion,Ortrud",
"24.6.": "Johannes,Reingard",
"25.6.": "Dorothea,Eleonora,Ella",
"26.6.": "Anthelm,Vigilius",
"27.6.": "Cyrill,Heimo,Hemma,Maxim",
"28.6.": "Ekkehard,Harald,Irenäus",
"29.6.": "Gero,Paul,Peter",
"30.6.": "Bertram,Ehrentrud,Otto",
"1.7.": "Aaron,Dietrich,Otto,Theobald",
"2.7.": "Wiltrud",
"3.7.": "Günther,Ramon,Ramona,Thomas",
"4.7.": "Berta,Elisabeth,Ulrich",
"5.7.": "Albrecht,Antonius,Letizia",
"6.7.": "Goar,Isaias,Marietta",
"7.7.": "Edda,Firmin,Willibald",
"8.7.": "Amalia,Edgar,Kilian",
"9.7.": "Augustin",
"10.7.": "Engelbert,Knud,Raphael",
"11.7.": "Benedikt,Olga,Oliver",
"12.7.": "Felix,Henriette,Siegbert",
"13.7.": "Arno,Heinrich,Kunigunde",
"14.7.": "Goswin,Kamilus,Roland",
"15.7.": "Bonaventura,Egon,Waldemar",
"16.7.": "Irmgard",
"17.7.": "Charlotte,Donata,Gabriella",
"18.7.": "Answer,Arnulf,Ulf,Friedrich",
"19.7.": "Bernulf,Marina,Poppo,Reto",
"20.7.": "Apollinaris,Bernhard,Margaretha",
"21.7.": "Daniel,Daniela,Julia,Laurentius",
"22.7.": "Maria,Magdalena",
"23.7.": "Birgitta,Birgit,Liborius",
"24.7.": "Christoph",
"25.7.": "Jakobus,Thomas,Valentina",
"26.7.": "Anna,Gloria,Joachim",
"27.7.": "Berthold,Natalie,Pantaleon",
"28.7.": "Adele,Ada,Bantus,Beatus,Innozenz",
"29.7.": "Ladislaus,Martha,Olaf",
"30.7.": "Ingeborg,Inga,Petrus",
"31.7.": "Hermann,Ignatius,Justinus",
"1.8.": "Alfons,Kenneth,Peter",
"2.8.": "Eusebius,Julian,Petrus",
"3.8.": "August,Lydia,Nikodemus",
"4.8.": "Johannes,Rainer",
"5.8.": "Oswald",
"6.8.": "Gilbert",
"7.8.": "Afra,Albert,Cajetan",
"8.8.": "Cyriak,Dominik,Elgar",
"9.8.": "Edith",
"10.8.": "Astrid,Laurenz,Lars",
"11.8.": "Klara,Susanna",
"12.8.": "Karl,Radegunde",
"13.8.": "Cassian,Hippolyt,Marko,Pontianus",
"14.8.": "Maximilian,Meinhard",
"15.8.": "Tarsitius",
"16.8.": "Alfried,Rochus,Stefan",
"17.8.": "Gudrun,Hyazinth,Janine",
"18.8.": "Claudia,Helena,Rainaki",
"19.8.": "Johann,Julius,Sebald",
"20.8.": "Bernhard,Bernd,Ronald",
"21.8.": "Maximilian,Pius",
"22.8.": "Regina",
"23.8.": "Isolde,Rosa,Zachäus",
"24.8.": "Bartholomäus,Michaela",
"25.8.": "Elvira,Josef,Ludwig",
"26.8.": "Gregor,Miriam,Teresa",
"27.8.": "Gebhard,Monika,Vivian",
"28.8.": "Adelinde,Aline,Augustin",
"29.8.": "Johannes",
"30.8.": "Felix,Heribert,Rebekka",
"31.8.": "Paulinus,Raimund",
"1.9.": "Ägidius,Ruth,Verena",
"2.9.": "Ingrid,René,Salomon",
"3.9.": "Gregor,Silvia,Sophie",
"4.9.": "Ida,Iris,Irmgard,Rosalie",
"5.9.": "Roswitha,Teresa",
"6.9.": "Bertram,Gundolf,Magnus",
"7.9.": "Otto,Ralph,Regina",
"8.9.": "Adrian",
"9.9.": "Edgar,Otmar,Pedro",
"10.9.": "Carlo,Diethard,Isabella",
"11.9.": "Felix,Maternus,Regula",
"12.9.": "Gerfried,Maria",
"13.9.": "Johann,Notburga,Tobias",
"14.9.": "Albert,Cornelius",
"15.9.": "Dolores,Melitta,Melissa",
"16.9.": "Edith,Ludmilla,Mechthild",
"17.9.": "Ariane,Hildegard,Robert",
"18.9.": "Herlinde,Lambert,Rica",
"19.9.": "Igor,Januarius",
"20.9.": "Susanne",
"21.9.": "Deborah,Jonas,Matthäus",
"22.9.": "Emmeram,Mauritius",
"23.9.": "Gerhild,Linus,Thekla",
"24.9.": "Gerhard,Hermann,Rupert,Virgil",
"25.9.": "Irmfried,Serge",
"26.9.": "Cosima,Damian,Kosmas",
"27.9.": "Dietrich,Hiltrud,Vinzenz",
"28.9.": "Giselher,Lioba,Thekla,Wenzel",
"29.9.": "Gabriel,Gabriela,Michael,Michaela,Rafael,Rafaela",
"30.9.": "Hieronymus,Urs,Victor",
"1.10.": "Remigius",
"2.10.": "Gideon",
"3.10.": "Bianca,Ewald,Udo",
"4.10.": "Aurea,Edwin,Franz",
"5.10.": "Gallina,Herwig,Meinolf",
"6.10.": "Adalbero,Bruno,Melanie",
"7.10.": "Jörg,Justina,Rosa,Maria",
"8.10.": "Felix,Günther,Simeon",
"9.10.": "Dionys,Günter,Sara,Johannes",
"10.10.": "Gereon,Samuel,Viktor",
"11.10.": "Bruno,Jakob",
"12.10.": "Edwin,Gottfried,Maximilian",
"13.10.": "Eduard,Gerald",
"14.10.": "Burkhard,Kallixtus",
"15.10.": "Aurelia,Theresia",
"16.10.": "Gallus,Hedwig,Margareta",
"17.10.": "Anselm,Ignatius",
"18.10.": "Gwenn,Justus,Lukas",
"19.10.": "Isaak,Johannes,Paul,Peter",
"20.10.": "Ira,Irina,Vitalis,Wendelin",
"21.10.": "Karl,Ursula,Ulla",
"22.10.": "Cordula,Ingbert,Salome",
"23.10.": "Johannes,Severin,Uta",
"24.10.": "Alois,Aloisia,Anton,Armella",
"25.10.": "Krispin,Krispinian",
"26.10.": "Albin,Amand,Wigand",
"27.10.": "Christa,Sabina,Wolfhard",
"28.10.": "Simon,Thaddäus",
"29.10.": "Ermelinda,Melinda",
"30.10.": "Alfons,Angelo,Dieter",
"31.10.": "Quentin,Wolfgang",
"1.11.": "Arthur,Harald,Otmar,Rupert",
"2.11.": "Angela,Margarethe,Tobias",
"3.11.": "Hubert,Martin,Pirmin,Rupert",
"4.11.": "Karl,Karla,Modesta",
"5.11.": "Bernhard,Berthild,Emmerich",
"6.11.": "Christine,Leonhard,Rudolf",
"7.11.": "Carina,Engelbert,Willibrord",
"8.11.": "Gottfried,Willehad",
"9.11.": "Herfried,Roland,Theodor",
"10.11.": "Andrea,Andreas,Jens,Leo",
"11.11.": "Martin,Menas,Senta",
"12.11.": "Emil,Josaphat,Kunibert",
"13.11.": "Eugen,Livia,Stanislaus",
"14.11.": "Nikolaus,Sidonia",
"15.11.": "Albert,Leopold,Leopoldine",
"16.11.": "Margareta,Otmar",
"17.11.": "Gertrud,Hilda,Florin",
"18.11.": "Odo,Philippine",
"19.11.": "Elisabeth,Bettina,Lisa",
"20.11.": "Bernward,Edmund,Korbinian",
"21.11.": "Amalie",
"22.11.": "Cäcilia,Salvator",
"23.11.": "Clemens,Columban,Detlef",
"24.11.": "Albert,Flora",
"25.11.": "Katharina,Kathrin,Katja",
"26.11.": "Anneliese,Gebhard,Konrad",
"27.11.": "Albrecht,Brunhilde,Uta",
"28.11.": "Berta,Gunther,Jakob",
"29.11.": "Christine,Friedrich,Friederike",
"30.11.": "Andreas,Andrea,Volkert",
"1.12.": "Blanka,Charles,Eligius,Natalie",
"2.12.": "Bibiana,Jan,Lucius",
"3.12.": "Emma,Franz,Xaver,Jason",
"4.12.": "Adolf,Barbara,Johannes",
"5.12.": "Anno,Gerald,Niels,Reinhard",
"6.12.": "Denise,Henrike,Nikolaus",
"7.12.": "Ambrosius,Benedikte",
"8.12.": "Edith,Elfriede",
"9.12.": "Liborius,Reinmar,Valerie",
"10.12.": "Angelina,Bruno,Emma,Herbert",
"11.12.": "Arthur,Damasus,Tassilo",
"12.12.": "Johanna",
"13.12.": "Jodok,Lucia,Odilia",
"14.12.": "Berthold,Johannes",
"15.12.": "Carlo,Christiane,Nina",
"16.12.": "Adelheid,Heidi,Elke",
"17.12.": "Jolanda,Lazarus,Viviana",
"18.12.": "Philipp,Wunibald",
"19.12.": "Benjamin,Susanne",
"20.12.": "Eike,Holger,Julius,Regina",
"21.12.": "Hagar,Peter",
"22.12.": "Jutta",
"23.12.": "Victoria",
"24.12.": "Adam,Eva",
"25.12.": "Anastasia,Eugenia,Josefina,Natalis,Therese",
"26.12.": "Stephan,Stephanie",
"27.12.": "Fabiola",
"28.12.": "Donna,Mattea",
"29.12.": "David,Jonathan,Thomas",
"30.12.": "Felix,Lothar",
"31.12.": "Melanie,Silvester"				
				}';
				$names_array = json_decode($ndjson);
				return $names_array;				
			}			  	
			public function get_hungarian_namedays_array()
			{
				$ndjson = '{	
1.1.": "Fruzsina",
"2.1.": "Ábel",
"3.1.": "Benjámin,Genovéva",
"4.1.": "Leóna,Titusz",
"5.1.": "Simon",
"6.1.": "Boldizsár",
"7.1.": "Attila,Ramóna",
"8.1.": "Gyöngyvér",
"9.1.": "Marcell",
"10.1.": "Melánia",
"11.1.": "Ágota",
"12.1.": "Ernõ",
"13.1.": "Veronika",
"14.1.": "Bódog",
"15.1.": "Lóránd,Lóránt",
"16.1.": "Gusztáv",
"17.1.": "Antal,Antónia",
"18.1.": "Piroska",
"19.1.": "Márió,Sára",
"20.1.": "Fábián,Sebestyén",
"21.1.": "Ágnes",
"22.1.": "Artúr,Vince",
"23.1.": "Rajmund,Zelma",
"24.1.": "Timót",
"25.1.": "Pál",
"26.1.": "Paula,Vanda",
"27.1.": "Angelika",
"28.1.": "Karola,Károly",
"29.1.": "Adél",
"30.1.": "Martina",
"31.1.": "Gerda,Marcella",
"1.2.": "Ignác",
"2.2.": "Aida,Karolina",
"3.2.": "Balázs",
"4.2.": "Csenge,Ráhel",
"5.2.": "Ágota,Ingrid",
"6.2.": "Dóra,Dorottya",
"7.2.": "Rómeó,Tódor",
"8.2.": "Aranka",
"9.2.": "Abigél,Alex",
"10.2.": "Elvira",
"11.2.": "Bertold,Marietta",
"12.2.": "Lídia,Lívia",
"13.2.": "Ella,Linda",
"14.2.": "Bálint,Valentin",
"15.2.": "Georgina,Kolos",
"16.2.": "Julianna,Lilla",
"17.2.": "Donát",
"18.2.": "Bernadett",
"19.2.": "Zsuzsanna",
"20.2.": "Aladár,Álmos",
"21.2.": "Eleonóra",
"22.2.": "Gerzson",
"23.2.": "Alfréd",
"24.2.": "Mátyás",
"25.2.": "Géza",
"26.2.": "Edina",
"27.2.": "Ákos,Bátor",
"28.2.": "Elemér",
"1.3.": "Albin",
"2.3.": "Lujza",
"3.3.": "Kornélia",
"4.3.": "Kázmér",
"5.3.": "Adorján,Adrián",
"6.3.": "Inez,Leonóra",
"7.3.": "Tamás",
"8.3.": "Zoltán",
"9.3.": "Fanni,Franciska",
"10.3.": "Ildikó",
"11.3.": "Szilárd",
"12.3.": "Gergely",
"13.3.": "Ajtony,Krisztián",
"14.3.": "Matild",
"15.3.": "Kristóf",
"16.3.": "Henrietta",
"17.3.": "Gertrúd,Patrik",
"18.3.": "Ede,Sándor",
"19.3.": "Bánk,József",
"20.3.": "Klaudia",
"21.3.": "Benedek",
"22.3.": "Beáta,Izolda",
"23.3.": "Emõke",
"24.3.": "Gábor,Karina",
"25.3.": "Irén,Írisz",
"26.3.": "Emánuel",
"27.3.": "Hajnalka",
"28.3.": "Gedeon,Johanna",
"29.3.": "Auguszta",
"30.3.": "Zalán",
"31.3.": "Árpád",
"1.4.": "Hugó",
"2.4.": "Áron",
"3.4.": "Buda,Richárd",
"4.4.": "Izidor",
"5.4.": "Vince",
"6.4.": "Bíborka,Vilmos",
"7.4.": "Herman",
"8.4.": "Dénes",
"9.4.": "Erhard",
"10.4.": "Zsolt",
"11.4.": "Leó,Szaniszló",
"12.4.": "Gyula",
"13.4.": "Ida",
"14.4.": "Tibor",
"15.4.": "Anasztázia,Tas",
"16.4.": "Csongor",
"17.4.": "Rudolf",
"18.4.": "Andrea,Ilma",
"19.4.": "Emma",
"20.4.": "Tivadar",
"21.4.": "Konrád",
"22.4.": "Csilla,Noémi",
"23.4.": "Béla",
"24.4.": "György",
"25.4.": "Márk",
"26.4.": "Ervin",
"27.4.": "Zita",
"28.4.": "Valéria",
"29.4.": "Péter",
"30.4.": "Katalin,Kitti",
"1.5.": "Fülöp,Jakab",
"2.5.": "Zsigmond",
"3.5.": "Irma,Tímea",
"4.5.": "Flórián,Mónika",
"5.5.": "Adrián,Györgyi",
"6.5.": "Frida,Ivett",
"7.5.": "Gizella",
"8.5.": "Mihály",
"9.5.": "Gergely",
"10.5.": "Ármin,Pálma",
"11.5.": "Ferenc",
"12.5.": "Pongrác",
"13.5.": "Imola,Szervác",
"14.5.": "Bonifác",
"15.5.": "Szonja,Zsófia",
"16.5.": "Botond,Mózes",
"17.5.": "Paszkál",
"18.5.": "Alexandra,Erik",
"19.5.": "Ivó,Milán",
"20.5.": "Bernát,Felícia",
"21.5.": "Konstantin",
"22.5.": "Júlia,Rita",
"23.5.": "Dezsõ",
"24.5.": "Eliza,Eszter",
"25.5.": "Orbán",
"26.5.": "Evelin,Fülöp",
"27.5.": "Hella",
"28.5.": "Csanád,Emil",
"29.5.": "Magdolna",
"30.5.": "Janka,Zsanett",
"31.5.": "Angéla,Petronella",
"1.6.": "Tünde",
"2.6.": "Anita,Kármen",
"3.6.": "Klotild",
"4.6.": "Bulcsú",
"5.6.": "Fatime",
"6.6.": "Cintia,Norbert",
"7.6.": "Róbert",
"8.6.": "Medárd",
"9.6.": "Félix",
"10.6.": "Gréta,Margit",
"11.6.": "Barnabás",
"12.6.": "Villõ",
"13.6.": "Anett,Antal",
"14.6.": "Vazul",
"15.6.": "Jolán,Vid",
"16.6.": "Jusztin",
"17.6.": "Alida,Laura",
"18.6.": "Arnold,Levente",
"19.6.": "Gyárfás",
"20.6.": "Rafael",
"21.6.": "Alajos,Leila",
"22.6.": "Paulina",
"23.6.": "Zoltán",
"24.6.": "Iván",
"25.6.": "Vilmos",
"26.6.": "János,Pál",
"27.6.": "László",
"28.6.": "Irén,Levente",
"29.6.": "Péter,Pál",
"30.6.": "Pál",
"1.7.": "Annamária,Tihamér",
"2.7.": "Ottó",
"3.7.": "Kornél,Soma",
"4.7.": "Ulrik",
"5.7.": "Emese,Sarolta",
"6.7.": "Csaba",
"7.7.": "Apollónia",
"8.7.": "Ellák",
"9.7.": "Lukrécia",
"10.7.": "Amália",
"11.7.": "Lili,Nóra",
"12.7.": "Dalma,Izabella",
"13.7.": "Jenõ",
"14.7.": "Örs,Stella",
"15.7.": "Henrik,Roland",
"16.7.": "Valter",
"17.7.": "Elek,Endre",
"18.7.": "Frigyes",
"19.7.": "Emília",
"20.7.": "Illés",
"21.7.": "Dániel,Daniella",
"22.7.": "Magdolna",
"23.7.": "Lenke",
"24.7.": "Kincsõ,Kinga",
"25.7.": "Jakab,Kristóf",
"26.7.": "Anikó,Anna",
"27.7.": "Liliána,Olga",
"28.7.": "Szabolcs",
"29.7.": "Flóra,Márta",
"30.7.": "Judit,Xénia",
"31.7.": "Oszkár",
"1.8.": "Boglárka",
"2.8.": "Lehel",
"3.8.": "Hermina",
"4.8.": "Dominika,Domonkos",
"5.8.": "Krisztina",
"6.8.": "Berta,Bettina",
"7.8.": "Ibolya",
"8.8.": "László",
"9.8.": "Emõd",
"10.8.": "Lõrinc",
"11.8.": "Tiborc,Zsuzsanna",
"12.8.": "Klára",
"13.8.": "Ipoly",
"14.8.": "Marcell",
"15.8.": "Mária",
"16.8.": "Ábrahám",
"17.8.": "Jácint",
"18.8.": "Ilona",
"19.8.": "Huba",
"20.8.": "István",
"21.8.": "Hajna,Sámuel",
"22.8.": "Menyhért,Mirjam",
"23.8.": "Bence",
"24.8.": "Bertalan",
"25.8.": "Lajos,Patrícia",
"26.8.": "Izsó",
"27.8.": "Gáspár",
"28.8.": "Ágoston",
"29.8.": "Beatrix,Erna",
"30.8.": "Rózsa",
"31.8.": "Bella,Erika",
"1.9.": "Egon,Egyed",
"2.9.": "Dorina,Rebeka",
"3.9.": "Hilda",
"4.9.": "Rozália",
"5.9.": "Lõrinc,Viktor",
"6.9.": "Zakariás",
"7.9.": "Regina",
"8.9.": "Adrienn,Mária",
"9.9.": "Ádám",
"10.9.": "Hunor,Nikolett",
"11.9.": "Teodóra",
"12.9.": "Mária",
"13.9.": "Kornél",
"14.9.": "Roxána,Szeréna",
"15.9.": "Enikõ,Melitta",
"16.9.": "Edit",
"17.9.": "Zsófia",
"18.9.": "Diána",
"19.9.": "Vilhelmina",
"20.9.": "Friderika",
"21.9.": "Máté,Mirella",
"22.9.": "Móric",
"23.9.": "Tekla",
"24.9.": "Gellért,Mercédesz",
"25.9.": "Eufrozina,Kende",
"26.9.": "Jusztina,Pál",
"27.9.": "Adalbert",
"28.9.": "Vencel",
"29.9.": "Mihály",
"30.9.": "Jeromos",
"1.10.": "Malvin",
"2.10.": "Petra",
"3.10.": "Helga",
"4.10.": "Ferenc",
"5.10.": "Aurél",
"6.10.": "Brúnó,Renáta",
"7.10.": "Amália",
"8.10.": "Koppány",
"9.10.": "Dénes",
"10.10.": "Gedeon",
"11.10.": "Brigitta",
"12.10.": "Miksa",
"13.10.": "Ede,Kálmán",
"14.10.": "Helén",
"15.10.": "Teréz",
"16.10.": "Gál",
"17.10.": "Hedvig",
"18.10.": "Lukács",
"19.10.": "Nándor",
"20.10.": "Vendel",
"21.10.": "Orsolya",
"22.10.": "Elõd",
"23.10.": "Gyöngyi",
"24.10.": "Salamon",
"25.10.": "Bianka,Blanka",
"26.10.": "Dömötör",
"27.10.": "Szabina",
"28.10.": "Simon,Szimonetta",
"29.10.": "Nárcisz",
"30.10.": "Alfonz",
"31.10.": "Farkas",
"1.11.": "Marianna",
"2.11.": "Achilles",
"3.11.": "Gyõzõ",
"4.11.": "Károly",
"5.11.": "Imre",
"6.11.": "Lénárd",
"7.11.": "Rezsõ",
"8.11.": "Zsombor",
"9.11.": "Tivadar",
"10.11.": "Réka",
"11.11.": "Márton",
"12.11.": "Jónás,Renátó",
"13.11.": "Szilvia",
"14.11.": "Aliz",
"15.11.": "Albert,Lipót",
"16.11.": "Ödön",
"17.11.": "Gergõ,Hortenzia",
"18.11.": "Jenõ",
"19.11.": "Erzsébet",
"20.11.": "Jolán",
"21.11.": "Olivér",
"22.11.": "Cecília",
"23.11.": "Kelemen,Klementina",
"24.11.": "Emma",
"25.11.": "Katalin",
"26.11.": "Virág",
"27.11.": "Virgil",
"28.11.": "Stefánia",
"29.11.": "Taksony",
"30.11.": "Andor,András",
"1.12.": "Elza",
"2.12.": "Melinda,Vivien",
"3.12.": "Ferenc,Olívia",
"4.12.": "Barbara,Borbála",
"5.12.": "Vilma",
"6.12.": "Miklós",
"7.12.": "Ambrus",
"8.12.": "Mária",
"9.12.": "Natália",
"10.12.": "Judit",
"11.12.": "Árpád",
"12.12.": "Gabriella",
"13.12.": "Luca,Otília",
"14.12.": "Szilárda",
"15.12.": "Valér",
"16.12.": "Aletta,Etelka",
"17.12.": "Lázár,Olimpia",
"18.12.": "Auguszta",
"19.12.": "Viola",
"20.12.": "Teofil",
"21.12.": "Tamás",
"22.12.": "Zénó",
"23.12.": "Viktória",
"24.12.": "Ádám,Éva",
"25.12.": "Eugénia",
"26.12.": "István",
"27.12.": "János",
"28.12.": "Kamilla",
"29.12.": "Tamara,Tamás",
"30.12.": "Dávid",
"31.12.": "Szilveszter"
				}';
				$names_array = json_decode($ndjson);
				return $names_array;				
			} 	
			public function get_croatian_namedays_array()
			{
				$ndjson = '{
					"1.1": "Marija, Reljefima",
					"2.1": "Bazilije, Grgur",
					"3.1": "Isusovo, Genoveva, Cvijeta",
					"4.1": "Sdislava",
					"5.1": "Emilijana, Radoslav, Miljenko",
					"6.1": "Gašpar",
					"7.1": "Rajmund, Lucijan, Zorislav",
					"8.1": "Severin, Bogoljub, Apolinarij",
					"9.1": "Julijan, Živko, Miodrag",
					"10.1": "Agaton, Dobroslav, Aldo",
					"11.1": "Honorat, Neven",
					"12.1": "Arkadije, Živana, Ernest",
					"13.1": "Hilarije, Veselko, Radovan",
					"14.1": "Felik, Srećko",
					"15.1": "Franjo",
					"16.1": "Marcel, Oton, Mislav",
					"17.1": "Antun, Lavoslav, Vojmil",
					"18.1": "Margareta, Priska",
					"19.1": "Mario, Ljiljana, Marta",
					"20.1": "Fabijan, Sebastijan",
					"21.1": "Agneza, Janja, Neža",
					"22.1": "Vinko, Irena",
					"23.1": "Emerencijana, Ema, Vjera, Milko",
					"24.1": "Franjo, Bogoslav",
					"25.1": "Ananija",
					"26.1": "Timotej, Tit, Paula, Tonka",
					"27.1": "Angela, Vitalijan, Pribislav",
					"28.1": "Toma, Tomislav",
					"29.1": "Vilana, Valerije, Konstancije",
					"30.1": "Martina, Tina, Gordana",
					"31.1": "Ivan, Marcela, Julije",
					"1.2": "Brigita, Gita, Miroslav",
					"2.2": "Marijan",
					"3.2": "Blaž, Vlaho, Tripun",
					"4.2": "Katarina, Andrija, Veronika",
					"5.2": "Agata, Dobrila, Jagoda",
					"6.2": "Pavao, Doroteja, Dora",
					"7.2": "Pio, Rikard, Držislav",
					"8.2": "Jeronim, Jerko",
					"9.2": "Apolonija, Zora, Sunčica",
					"10.2": "Alojzije, Skolastika, Rastija",
					"11.2": "Lurdska",
					"12.2": "Reginald, Damjan, Eulalija",
					"13.2": "Jordan, Božidar, Božica",
					"14.2": "Valentin, Valentina, Zdravko",
					"15.2": "Klaudije",
					"16.2": "Onezim, Julijana, Miljenko",
					"17.2": "Donat",
					"18.2": "Angelico, Šimun, Flavijan, Gizela",
					"19.2": "Konrad, Ratko, Blago",
					"20.2": "Lav, Lea",
					"21.2": "Petar, Damir, Eleonora",
					"22.2": "Grozdan",
					"23.2": "Polikarp, Romana",
					"24.2": "Montan, Goran, Modest, Ranko",
					"25.2": "Aleksandar, Sandra, Branimir",
					"26.2": "Gabriel, Donat",
					"27.2": "Roman, Teofil, Bogoljub",
					"28.2": "",
					"1.3": "Čista, Albin, Zoran",
					"2.3": "Ines, Čedomil, Iskra",
					"3.3": "Anzelmo, Marin, Kamilo",
					"4.3": "Kazimir, Eugen, Natko",
					"5.3": "Euzebije, Vedran",
					"6.3": "Koleta, Zvjezdana, Viktor",
					"7.3": "Perpetua, Felicita, Ardo",
					"8.3": "Pačista, Ivan",
					"9.3": "Franciska, Franjka",
					"10.3": "Emilijan, Emil, Krunoslav",
					"11.3": "Firmil, Trvtko",
					"12.3": "Bernard, Budislav, Maksimilijan",
					"13.3": "Rozalija, Ratka, Kristina",
					"14.3": "Matilda, Miljana, Borka",
					"15.3": "Bezimena, Longin",
					"16.3": "Hrvoje, Miljan",
					"17.3": "Patrik, Domagoj, Hrvatin",
					"18.3": "Ćiril, Cvjetan",
					"19.3": "Joso, Joško",
					"20.3": "Klaudija, Dionizije, Vladislav",
					"21.3": "Kristijan, Vesna, Vlasta",
					"22.3": "Sredoposna, Oktav",
					"23.3": "Oton, Dražen",
					"24.3": "Katarina, Simeon",
					"25.3": "Blagovijest",
					"26.3": "Montan, Maksima, Emanuel",
					"27.3": "Ivan, Rupert, Lidija, Lada",
					"28.3": "Priska, Sonja, Polion",
					"29.3": "Gluha, Jona, Bertold",
					"30.3": "Kvirin, Viktor, Krescent",
					"31.3": "Benjamin, Amos, Ljubomir",
					"1.4": "Hugo, Teodora",
					"2.4": "Franjo, Dragoljub",
					"3.4": "Rikard, Svevlad, Benedikt",
					"4.4": "Izidor, Dora, Strahimir",
					"5.4": "Krescencija, Vinko, Marija",
					"6.4": "Vilim, Rajko",
					"7.4": "Ivan, Herman, Epifan",
					"8.4": "Dionizije, Alemka",
					"9.4": "Marija, Demetrije",
					"10.4": "Ezekijel",
					"11.4": "Stanislav, Stana, Radmila",
					"12.4": "Julije, Viktor, Davorka",
					"13.4": "Martin, Ida",
					"14.4": "Valerijan, Maksim",
					"15.4": "Krescent, Bosiljka, Anastazija",
					"16.4": "Josip, Bernardica",
					"17.4": "Rudolf, Robert",
					"18.4": "Eleuterija, Amadej",
					"19.4": "Konrad, Ema, Rastislav",
					"20.4": "Janja, Marcijan",
					"21.4": "Anzelmo, Goran",
					"22.4": "Soter, Kajo, Vojmil",
					"23.4": "Juraj, Juro, Ðuro, Ðurdica",
					"24.4": "Fidelis, Vjeran, Vjerko, Vjera",
					"25.4": "Marko, Maroje",
					"26.4": "Kleto, Marcelin, Višnja",
					"27.4": "Ozana, Jakov",
					"28.4": "Petar, Ljudevit, Grignon",
					"29.4": "Katarina, Sijenska",
					"30.4": "Pio, Josip, Cottolengo",
					"1.5": "Josip",
					"2.5": "Anastazije, Eugen, Boris",
					"3.5": "Filip, Jakov, Jakica",
					"4.5": "Florijan, Cvjetko, Cvijeta",
					"5.5": "Vinko, Maksim, Andenlko",
					"6.5": "Dominik, Nedjeljko, Benedikta",
					"7.5": "Dujam, Duje, Duška, Gizela",
					"8.5": "Marija, Marina, Ida",
					"9.5": "Herman, Mirna, Beato, Kristofor",
					"10.5": "Ivan, Gospa",
					"11.5": "Mamerto",
					"12.5": "Leopold, Mandic",
					"13.5": "Gospa, Servacije, Ena",
					"14.5": "Matija, Mate, Matko, Matea",
					"15.5": "Sofija",
					"16.5": "Ivan, Andrija, Nenad",
					"17.5": "Paskal, Paško",
					"18.5": "Ivan, Venancije, Srecko",
					"19.5": "Celestin, Rajko, Teofil, Inka",
					"20.5": "Bernardin",
					"21.5": "Eugen, Mazenod",
					"22.5": "Renata, Rita, Jelena, Jagoda",
					"23.5": "Deziderije, Želimir, Vilim",
					"24.5": "Marija, Suzana",
					"25.5": "Beda, Grgur",
					"26.5": "Filip, Zdenko, Eleuterij",
					"27.5": "Augustin",
					"28.5": "German",
					"29.5": "Polion, Euzebije, Veceslav",
					"30.5": "Ivana, Ferdinand",
					"31.5": "Jakov, Salomon",
					"1.6": "Marija, Justin, Malden",
					"2.6": "Marcelin, Petar, Sadok, Eugen",
					"3.6": "Karlo",
					"4.6": "Kvirin, Petar, Predrag",
					"5.6": "Bonifacije, Valerija, Darinka",
					"6.6": "Nobert, Neda, Klaudije, Berto",
					"7.6": "Robert",
					"8.6": "Dijana, Cecilija, Medardo",
					"9.6": "Efrem, Ranko",
					"10.6": "Margareta, Dijana",
					"11.6": "Barnaba, Borna",
					"12.6": "Ivan, Bosiljko, Nino",
					"13.6": "Antun, Ante, Tonci, Toni",
					"14.6": "Rufin, Elizej, Zlatko",
					"15.6": "Vid, Modest",
					"16.6": "Franjo",
					"17.6": "Laura, Nevenka, Adolf",
					"18.6": "Marko, Marcelijan, Ljubomir",
					"19.6": "Romualdo",
					"20.6": "Silverije",
					"21.6": "Alojzije",
					"22.6": "Ivan, Toma",
					"23.6": "Josip, Sidonija, Zdenka",
					"24.6": "Ivan",
					"25.6": "Vilim, Nora",
					"26.6": "Ivan, Pavao, Vigilije, Zoran",
					"27.6": "Ladislav, Ciril",
					"28.6": "Irenej, Smiljan",
					"29.6": "Petar, Pavao, Krešimir",
					"30.6": "Kajo",
					"1.7": "Estera",
					"2.7": "Oton, Višnja, Ostoja",
					"3.7": "Toma, Tomislav, Tomo, Miki",
					"4.7": "Elizabeta, Elza, Berta",
					"5.7": "Ciril, Metod, Slaven",
					"6.7": "Marija",
					"7.7": "Vilibald, Vilko, Klaudija",
					"8.7": "Akvila, Priscila",
					"9.7": "Marija, Ivan",
					"10.7": "Amalija, Alma, Ljubica, Ljuba",
					"11.7": "Benedikt, Olga, Oliver",
					"12.7": "Mislav, Tanja, Suzana",
					"13.7": "Euzebije",
					"14.7": "Kamilo, Miroslav",
					"15.7": "Bonaventura",
					"16.7": "Karmela",
					"17.7": "Ceslav, Branko, Dunja",
					"18.7": "Fridrik, Dalibor, Arnold",
					"19.7": "Justa, Rufina, Zlatka",
					"20.7": "Ilija, Ilijana",
					"21.7": "Danijel, Lovro, Danica",
					"22.7": "Marija",
					"23.7": "Brigita, Ivan, Slobodan",
					"24.7": "Kristina, Mirjana",
					"25.7": "Jakov, Kristofor, Kristo",
					"26.7": "Joakim, Ana",
					"27.7": "Klement, Natalija",
					"28.7": "Inocent",
					"29.7": "Marta, Blaženka",
					"30.7": "Petar, Rufin, Anda",
					"31.7": "Vatroslav, Ognjen",
					"1.8": "Alfons, Vjera, Nada",
					"2.8": "Euzebije",
					"3.8": "Augustin, Lidija",
					"4.8": "Ivan, Ivica, Tertulijan",
					"5.8": "Snježana, Nives",
					"6.8": "Stjepan",
					"7.8": "Siksto, Kajetan, Albert",
					"8.8": "Dominik, Nedjeljko, Dinko",
					"9.8": "Edith, Tvrtko",
					"10.8": "Lovro, Laura",
					"11.8": "Klara, Asiška, Jasminka",
					"12.8": "Anicet, Hilarija",
					"13.8": "Poncijan, Hipolit, Ivan",
					"14.8": "Maksimilijan, Alfred",
					"15.8": "Marija, Velika",
					"16.8": "Rok, Stjepan",
					"17.8": "Hijacint, Slobodan",
					"18.8": "Jelena, Manes",
					"19.8": "Ivan",
					"20.8": "Bernard, Branko, Dino",
					"21.8": "Hermogen, Anastazij",
					"22.8": "Regina, Vladislava",
					"23.8": "Ruža, Filip",
					"24.8": "Bariša, Zlata",
					"25.8": "Ljudevit, Josip, Patricija",
					"26.8": "Aleksandar",
					"27.8": "Monika, Honorat, Caslav",
					"28.8": "Augustin, Tin, Gustav",
					"29.8": "Sabina",
					"30.8": "Feliks, Radoslava",
					"31.8": "Rajmund, Rajko, Paulin",
					"1.9": "Egidije, Branimir, Branislav",
					"2.9": "Kalista, Divna",
					"3.9": "Grgur, Grga, Mansvet",
					"4.9": "Dunja, Ida",
					"5.9": "Roman, Lovro",
					"6.9": "Davor",
					"7.9": "Marko",
					"8.9": "Marica, Maja, Alen",
					"9.9": "Petar",
					"10.9": "Nikola, Pulherija, Lijepa",
					"11.9": "Hijacint, Cvjetko, Miljenko",
					"12.9": "Ime, Marija",
					"13.9": "Ivan, Ljubo",
					"14.9": "Višeslav",
					"15.9": "Dolores",
					"16.9": "Kornelije, Cipirijan",
					"17.9": "Robert, Franje",
					"18.9": "Ivan, Irena",
					"19.9": "Januarije, Emilija",
					"20.9": "Andrija",
					"21.9": "Matej, Mate, Matko",
					"22.9": "Toma, Mauricije",
					"23.9": "Lino, Tekla",
					"24.9": "Mercedes",
					"25.9": "Nikola, Aurelija, Kleofa",
					"26.9": "Kuzma, Damjan, Damir",
					"27.9": "Vinko, Gaj",
					"28.9": "Dominik, Vjenceslav",
					"29.9": "Mihovil, Rafael, Gabrijel",
					"30.9": "Jeronim, Jerko",
					"1.10": "Tereza, Terezija",
					"2.10": "Andelko, Anda",
					"3.10": "Kandid, Maksimilijan, Evald",
					"4.10": "Franjo",
					"5.10": "Rajmund, Flavijan, Miodrag",
					"6.10": "Bruno, Fides, Verica, Vjera",
					"7.10": "Justina",
					"8.10": "Šimun, Zvonimir",
					"9.10": "Ljudevit, Dionizije, Ivan",
					"10.10": "Franjo, Danijel, Danko",
					"11.10": "Emilijan, Bruno",
					"12.10": "Serafin, Makso, Edvin",
					"13.10": "Edvard, Edo, Teofil",
					"14.10": "Kalist",
					"15.10": "Terezija, Tereza, Zlata",
					"16.10": "Margareta, Marija, Alacoque",
					"17.10": "Ignacije, Vatroslav, Ognjen",
					"18.10": "Luka, Trifonija",
					"19.10": "Pavao",
					"20.10": "Vendelin, Irena, Miroslava",
					"21.10": "Uršula, Hilarija",
					"22.10": "Marija, Dražen, Cedomil",
					"23.10": "Ivan, Borislav, Severin",
					"24.10": "Antun, Jaroslav",
					"25.10": "Katarina",
					"26.10": "Demetrije, Zvonimir",
					"27.10": "Gordana, Cvitko",
					"28.10": "Šimun, Juda",
					"29.10": "Narcis, Stojko, Darko, Ida",
					"30.10": "Marcel, Marojko, Lukan",
					"31.10": "Alfonz, Vuk, Vukmir",
					"1.11": "Svetislav, Sveto",
					"2.11": "Dušica, Duško",
					"3.11": "Martin, Hubert",
					"4.11": "Karlo, Dragutin, Drago",
					"5.11": "Emerik, Mirko",
					"6.11": "Leonard, Vedran, Sever",
					"7.11": "Engelbert, Andelko",
					"8.11": "Milotislav, Bogdan",
					"9.11": "Ivan",
					"10.11": "Leon, Lavoslav, Lav",
					"11.11": "Martin",
					"12.11": "Jozafat, Milan, Renato",
					"13.11": "Stanislav, Stanko",
					"14.11": "Nikola, Ivan",
					"15.11": "Albert, Leopold",
					"16.11": "Margareta",
					"17.11": "Elizabeta, Igor, Grgur",
					"18.11": "",
					"19.11": "Janja, Matilda, Krispin",
					"20.11": "Feliks, Srecko, Edmund",
					"21.11": "Mavro",
					"22.11": "Cecilija, Filemon",
					"23.11": "Klement, Milivoj",
					"24.11": "Krizogon, Krševan",
					"25.11": "Katarina",
					"26.11": "Konrad, Leonardo, Dubravko",
					"27.11": "Virgilije, Severin, Velimir",
					"28.11": "Jakov, Markijski, Katarina",
					"29.11": "Saturnin, Svjetlana",
					"30.11": "Andrija, Andreja",
					"1.12": "Eligije, Božena",
					"2.12": "Bibijana, Blanka",
					"3.12": "Franjo, Klaudije, Lucije",
					"4.12": "Ivan, Barbara",
					"5.12": "Saba, Krispina, Sabina",
					"6.12": "Nikola, Nikša",
					"7.12": "Ambrozije, Marin",
					"8.12": "",
					"9.12": "Valerija, Zdravka",
					"10.12": "Julija, Judita",
					"11.12": "Damaz, Barsaba, Damir",
					"12.12": "Ivana",
					"13.12": "Lucija, Jasna, Svjetlana",
					"14.12": "Ivan, Krševan",
					"15.12": "Irenej",
					"16.12": "Adela, Albina, Zorka",
					"17.12": "Lazar, Izak, Jolanda",
					"18.12": "Gacijan, Bosiljko, Rufo",
					"19.12": "Urban, Vladimir, Božica",
					"20.12": "Eugen, Makarije, Amon",
					"21.12": "Petar, Perica",
					"22.12": "Honorat, Caslav, Zenon",
					"23.12": "Ivan, Viktorija",
					"24.12": "Adam, Eva",
					"25.12": "Božidar, Božo, Natalija",
					"26.12": "Stjepan, Krunoslav",
					"27.12": "Ivan, Ivo, Janko",
					"28.12": "Mladen, Nevenka",
					"29.12": "Toma, David, Davor",
					"30.12": "Feliks, Sabin",
					"31.12": "Silvestar, Zahvalnica",
				}';
				$names_array = json_decode($ndjson);
				return $names_array;
			} 
			public function get_spanish_namedays_array()
			{
				$ndjson = '{
					"1.1": "Manuel, Emanuel, Jesús",
					"2.1": "Gregorio, Astrid, Basilio, Emma",
					"3.1": "Daniel, Genova, Genoveva, Jennifer",
					"4.1": "Eugenio",
					"5.1": "Amada, Simón, Simona, Emiliana",
					"6.1": "Baltasar, Gaspar, Reyes, Adoración",
					"7.1": "Amadeo, Raimundo, Aquiles, Luciano",
					"8.1": "Maximino, Eladio",
					"9.1": "Julián, Pedro Urseolo",
					"10.1": "Gonzalo, Marciano, Alda, Aldo",
					"11.1": "Alejandro, Guillermo, Hortensia",
					"12.1": "Alfredo, Tatiana, Tania, Hilario",
					"13.1": "Verónica, Gumersindo, Milagros",
					"14.1": "Félix, Gil",
					"15.1": "Mauro, Raquel, Marcelo",
					"16.1": "Odette, Oto, Priscila",
					"17.1": "Alba, Antonio, Mariana, Alfredo",
					"18.1": "Florida, Beatriz, Mario, Pia",
					"19.1": "Mario, Vicente, Sebastián",
					"20.1": "Fabián",
					"21.1": "Vicente",
					"22.1": "Domingo, Imanol, Emma, Gaudencio",
					"23.1": "Alberto, Ildefonso, Alberta",
					"24.1": "Francisco, Tirso, Paz, Feliciano",
					"25.1": "Elvira, Paula, Timoteo",
					"26.1": "Paula, Tito, Gonzalo",
					"27.1": "Ángela, Tomás, Valerio",
					"28.1": "Tomas, Pedro Nolasco",
					"29.1": "Valeria, Valerio, Martina",
					"30.1": "Alejandro",
					"31.1": "Juan Bosco",
					"1.2": "Cecilio",
					"2.2": "Catalina, Aída, Felipe, Ayuda",
					"3.2": "Oscar, Blas, Adelina",
					"4.2": "Gilberto, Isidro, Verónica, Juana",
					"5.2": "Isaac, Ágata, Águeda",
					"6.2": "Gonzalo, Amando, Amanda, Silvano",
					"7.2": "Moisés, Ricardo",
					"8.2": "Jerónimo, Lucio, Elisanda",
					"9.2": "Donato, Sabino, Reinaldo, Apolonia",
					"10.2": "Guillermo, Amancio, Arnaldo, Arnau",
					"11.2": "Dante, Lourdes, Adolfo",
					"12.2": "Modesto, Eulalia",
					"13.2": "Cristian, Benigno",
					"14.2": "Dionisio, Valentín, Valentina",
					"15.2": "Georgia, Georgina, Faustino",
					"16.2": "Elías, Samuel, Isaías, Jeremías",
					"17.2": "Constanza, Rómulo, Alexis",
					"18.2": "Lucio, Simeón",
					"19.2": "Álvaro, Conrado, Almudina, Gabino",
					"20.2": "Eleuterio",
					"21.2": "Irene, Pedro Damián",
					"22.2": "Margarita, Leonor",
					"23.2": "Lázaro, Romance, Policarpo",
					"24.2": "Modesto",
					"25.2": "Cesáreo, Dióscoro",
					"26.2": "Néstor",
					"27.2": "Gabriel, Gabriela, Baldomero",
					"28.2": "Román, Leandro, Romano",
					"1.3": "Federico, Rosendo, Eudoxia",
					"2.3": "Enrique, Pablo, Enriqueta",
					"3.3": "Medín, Rosendo",
					"4.3": "Francisca, Arcadio, Eugenio",
					"5.3": "Juan José",
					"6.3": "Humberto, Olegario, Judith, Nina",
					"7.3": "Clotilde, Felicidad",
					"8.3": "Juan",
					"9.3": "Cándido, Francisca",
					"10.3": "Andrés, Macario",
					"11.3": "Ramiro, Oria",
					"12.3": "Josefina, Maximiliano, Fina",
					"13.3": "Patricia, Rodrigo, Ramiro",
					"14.3": "Jacobo, Matilde, Florentina",
					"15.3": "César, Luis, Raimundo, Madrona",
					"16.3": "Abrahan, Clemente",
					"17.3": "Patricio",
					"18.3": "Narciso, Salvador",
					"19.3": "José, Marcos, Josefa",
					"20.3": "Alejandra, Claudia",
					"21.3": "Clemencia, Fabiola, Nicolás",
					"22.3": "Sergio, Octaviano",
					"23.3": "Fidel, Oriol, Victoriano, Toribio",
					"24.3": "Delmiro, Edelmira, Edelmiro, Timolao",
					"25.3": "Abel, Gloria, Encarnación, Rebeca",
					"26.3": "Braulio, Diego",
					"27.3": "Ruperto, Lilia, Alejandro",
					"28.3": "Esperanza, Gundelina",
					"29.3": "Jonas, Segundo",
					"30.3": "Quirino",
					"31.3": "Amós, Benjamín",
					"1.4": "Venancio",
					"2.4": "Ofelia, Francisco",
					"3.4": "Sixto",
					"4.4": "Isidoro, Platón",
					"5.4": "Emilia, Vicente Ferrer",
					"6.4": "Celso, Diógenes",
					"7.4": "Donato, Juan Bautista",
					"8.4": "Dionisio, Amancio",
					"9.4": "Hugo, Casilda, Eusequio",
					"10.4": "Ezequiel",
					"11.4": "Gema, Oria, Estanislao",
					"12.4": "Andrés, Damián, Julio, Zenón",
					"13.4": "Martín, Hermenegildo",
					"14.4": "Lamberto",
					"15.4": "Máximo, Aníbal",
					"16.4": "Engracia, Bernadeta",
					"17.4": "Rodolfo, Anicéto",
					"18.4": "Perfecto",
					"19.4": "León, Crescencio",
					"20.4": "Inés, Víctor",
					"21.4": "Anselmo",
					"22.4": "Teodoro, Alexander, Apeles",
					"23.4": "Adalberto, Jorge, Gorka",
					"24.4": "Leoncio, Honorio, Honoria, Fidel",
					"25.4": "Antonio, Antonieta, Marco, Marcia",
					"26.4": "Basilio, Marcelino, Engracia, Isidoro",
					"27.4": "Montserrat, Zita",
					"28.4": "Amado, Pedro Chanel",
					"29.4": "Teodora, Karen, Katia, Wilfredo",
					"30.4": "Jaime, Amador, Pía, Pío",
					"1.5": "Berta, Tamar, Tamara, Oroncio",
					"2.5": "Germán, Araceli, Atanasio, Vindemial",
					"3.5": "Juvenal, Violeta, Evencio, Felipe",
					"4.5": "Florián, Froilán, Lidón, Silvano",
					"5.5": "Adrián, Silvano, Niceto, Ángelica",
					"6.5": "Domingo, Evodio, Protógenes, Judith",
					"7.5": "Augusto, Flavio, Gisela",
					"8.5": "Acacio",
					"9.5": "Gregorio, Hermas, Geroncio",
					"10.5": "Job, Solange, Gordiano",
					"11.5": "Estela, Favio, Amparo, Poncio",
					"12.5": "Domingo, Nerea, Nereo, Aquileo",
					"13.5": "Imelda, Fátima",
					"14.5": "Matías, Corona, Cora, Henedina",
					"15.5": "Cecilio, Eufrasia, Isidro, Torcuato",
					"16.5": "Brenda, Ubaldo, Honorato",
					"17.5": "Eric, Erica, Pascual",
					"18.5": "Alejandra, Félix, Próspero",
					"19.5": "Celestina, Celestino, Crispín",
					"20.5": "Orlando, Baudilio, Asterio",
					"21.5": "Constantino, Virginia, Giselle",
					"22.5": "Emilio, Rita, Rosana",
					"23.5": "Miguel, Mercurial, Eufebio",
					"24.5": "Rocío, Susana, Auxiliadora",
					"25.5": "Valentín, Valentina, Sonia",
					"26.5": "Felipe Neri, Zacarías",
					"27.5": "Carolina",
					"28.5": "Agustín, Bernardo, Emilio, Germán",
					"29.5": "Alejandro, Justo, Teodosia",
					"30.5": "Fernando, Estela, Fernanda, Hernán",
					"31.5": "Visitación, Petronila, Amelia",
					"1.6": "Alta, Graciano, Laura, Candelaria",
					"2.6": "Erasmo, Marcelino, Blandina",
					"3.6": "Oliva, Kevin, Cecilio, Davino",
					"4.6": "Emma, Quirino, Ruth, Saturnina",
					"5.6": "Eloisa, Marcia, Valeria, Nicanor",
					"6.6": "Norberto, Artemio, Cándida, Ismael",
					"7.6": "Roberto",
					"8.6": "Giraldo",
					"9.6": "Blanca, Primo, Feliciano, Diana",
					"10.6": "Amalia, Amelia, Getulio, Críspulo",
					"11.6": "Benito, Bernabé, Aléida",
					"12.6": "Nazario, Olimpo, Cirilo",
					"13.6": "Antonio, Joel, Andoni",
					"14.6": "Félix, Eliseo, Digna",
					"15.6": "Lidia, Vito, Landelino, Libia",
					"16.6": "Ciro, Aquilino, Aureliano, Siro",
					"17.6": "Ismael, Isauro, Montano",
					"18.6": "Justo, Marceliano, Marina",
					"19.6": "Aurora",
					"20.6": "Elia, Silverio, Macario",
					"21.6": "Luis, Demetria, Terencio, Raul, Gina",
					"22.6": "Albano, Paulino",
					"23.6": "Alicia, Apolo, Inmaculada, Agripina",
					"24.6": "Juan, Juana, Ivana, Joan",
					"25.6": "Salomón, Guillermo",
					"26.6": "Virgilio, Pelayo, Antelmo, Alicia",
					"27.6": "Socorro, Zoilo, Ladislao, Anecto",
					"28.6": "Marcela",
					"29.6": "Ciro, David, Pablo, Pedro",
					"30.6": "Marcial, Leonila",
					"1.7": "Aarón, Esther, Luz",
					"2.7": "Visitación, Martiniano, Vidal",
					"3.7": "Tomás, Heliodoro, Jacinto, Enrique",
					"4.7": "Berta, Elizabeth, Laureano, Isabel",
					"5.7": "Filomena, Filomeno, Zoa",
					"6.7": "Isaías, Dominica, Rómulo",
					"7.7": "Fermín, Roberto, Odón, Germano",
					"8.7": "Adrián, Edgar, Marina, Priscila",
					"9.7": "Milagros, Verónica",
					"10.7": "Cristóbal, Silvano, Honorato",
					"11.7": "Benito, Olga, Abundio, Sabino",
					"12.7": "Paulina, Oliverio",
					"13.7": "Eugenio, Sara, Joel",
					"14.7": "Camila, Vladimiro, Camilo",
					"15.7": "Carmelo, Hilario, Fausto",
					"16.7": "Carmen, Marcelina, Generosa",
					"17.7": "Elías",
					"18.7": "Emiliano, Federico, Luz",
					"19.7": "Aurea, Aureo",
					"20.7": "Elías, Elisa",
					"21.7": "Angelina, Lorenza, Daniel, Julia",
					"22.7": "Teófila, Zoraida, Magdalena, Primitiva",
					"23.7": "Brigida, Teresa, Boris",
					"24.7": "Cristina",
					"25.7": "Jaime, Santiago",
					"26.7": "Ana, Joaquín",
					"27.7": "Cucufate, Natalia",
					"28.7": "Celso",
					"29.7": "Marta, Olavo",
					"30.7": "Abdón",
					"31.7": "Ignacio",
					"1.8": "Alfonso, Dalmau",
					"2.8": "Angeles, Eusebio.",
					"3.8": "Gustavo, Lídia",
					"4.8": "Juan María Vianney",
					"5.8": "Africa, Blanca, Nieves",
					"6.8": "Salvador",
					"7.8": "Cayetano",
					"8.8": "Domingo",
					"9.8": "-",
					"10.8": "Lorenzo",
					"11.8": "Clara, Filomena, Susana",
					"12.8": "Herculano",
					"13.8": "Aurora, Hipólito",
					"14.8": "Atanasia",
					"15.8": "Asunción, Estrella, María, Paloma",
					"16.8": "Roque",
					"17.8": "Isaac, Jacinto",
					"18.8": "Elena",
					"19.8": "Magín",
					"20.8": "Bernardo Abad",
					"21.8": "Sidonio",
					"22.8": "Reina",
					"23.8": "Rosa",
					"24.8": "Bartolomé",
					"25.8": "Ginés",
					"26.8": "Ceferino",
					"27.8": "Mónica",
					"28.8": "Agustín",
					"29.8": "Sabina",
					"30.8": "Gaudencia",
					"31.8": "Raimón, Ramón",
					"1.9": "Arturo, Egidio, Gil",
					"2.9": "Raquel, Antolín",
					"3.9": "Dorotea",
					"4.9": "Moisés, Rosalía",
					"5.9": "Eudosio",
					"6.9": "Eva, Fausto",
					"7.9": "Regina",
					"8.9": "Adela, Meritxell, Nuria",
					"9.9": "Claustro, Felicia",
					"10.9": "Nicolás",
					"11.9": "Patiens",
					"12.9": "Dulce, María",
					"13.9": "Juan Crisóstomo",
					"14.9": "Exaltación",
					"15.9": "Aurora, Dolores, Mar",
					"16.9": "Rogelio",
					"17.9": "Ariadna, Columba, Roberto",
					"18.9": "Sofía",
					"19.9": "Nilo",
					"20.9": "Eustaquio",
					"21.9": "Mateo, Mauricio",
					"22.9": "Digna, Inocencio",
					"23.9": "Tecla, Lina, Lino",
					"24.9": "Gerardo, Mercedes",
					"25.9": "Dalmacio",
					"26.9": "Cosme, Damián",
					"27.9": "Florentino, Vicente",
					"28.9": "Wenceslao",
					"29.9": "Gabriel, Miguel, Rafael",
					"30.9": "Jerónimo",
					"1.10": "Teresa",
					"2.10": "Angeles Custodios",
					"3.10": "Francisco, Cándido",
					"4.10": "Francisco",
					"5.10": "Gala, Plácido",
					"6.10": "Bruno",
					"7.10": "Rosario",
					"8.10": "Salud, Thaís",
					"9.10": "Abrahan, Dionisio",
					"10.10": "Tomás",
					"11.10": "Begona",
					"12.10": "Pilar, Serafín",
					"13.10": "Eduardo",
					"14.10": "Calixto",
					"15.10": "Teresa",
					"16.10": "Margarita, María Alacoque",
					"17.10": "Ignacio",
					"18.10": "Lucas",
					"19.10": "Laura",
					"20.10": "Academia, Irene",
					"21.10": "Griselda, Ursula",
					"22.10": "Salomé",
					"23.10": "Servando",
					"24.10": "Antonio María Claret",
					"25.10": "Bernardo Calvó",
					"26.10": "Evaristo",
					"27.10": "Capitolina",
					"28.10": "Judas, Simón, Tadeo",
					"29.10": "Narciso",
					"30.10": "Bienvenida, Claudio",
					"31.10": "Quintin",
					"1.11": "Benigno, Penélope",
					"2.11": "Jorge, Gorka",
					"3.11": "Ermengol, Silvia",
					"4.11": "Carlos, Carlota, Carolina",
					"5.11": "Zacarías, Elisabet, Isabel",
					"6.11": "Leonardo",
					"7.11": "Carina, Ernesto",
					"8.11": "Severiano",
					"9.11": "Teodoro",
					"10.11": "Almudena, León",
					"11.11": "Martín",
					"12.11": "Aurelio",
					"13.11": "Leandro, Diego",
					"14.11": "Teodoto, Clemente",
					"15.11": "Alberto, Leopoldo",
					"16.11": "Edmundo, Margarita",
					"17.11": "Gertrudis, Hilda, Isabel, Victoria",
					"18.11": "Aurelio",
					"19.11": "Crispino, Fausto",
					"20.11": "Félix, Lucrecia, Ocatavio",
					"21.11": "Demetrio, Fructuoso, Piedad",
					"22.11": "Cecilia",
					"23.11": "Clemente",
					"24.11": "Flora",
					"25.11": "Erasmo",
					"26.11": "Juan",
					"27.11": "Auxilio",
					"28.11": "Rufo",
					"29.11": "Saturnino",
					"30.11": "Andrés",
					"1.12": "Adelaida, Eloy, Hugo",
					"2.12": "Elisa, Elsa",
					"3.12": "Francisco Javier, María",
					"4.12": "Bárbara",
					"5.12": "Crispina",
					"6.12": "Nicolás",
					"7.12": "Ambrosio",
					"8.12": "Concepción, Inmaculada, Pura",
					"9.12": "Juan Diego",
					"10.12": "Eulalia",
					"11.12": "Dámaso",
					"12.12": "Chantal, Guadalupe",
					"13.12": "Lucía",
					"14.12": "Juan, Nicasio, Pompeyo",
					"15.12": "Fortunato, Cristina",
					"16.12": "Albina",
					"17.12": "Lázaro, Yolanda",
					"18.12": "Esperanza, Macarena",
					"19.12": "Darío",
					"20.12": "Ptolomeo",
					"21.12": "Pedro Canisio",
					"22.12": "Floro",
					"23.12": "Juan",
					"24.12": "Delfín, Társila",
					"25.12": "Belén, Eugenia, Natividad",
					"26.12": "Esteban",
					"27.12": "Teófanos",
					"28.12": "Abel",
					"29.12": "Davíd",
					"30.12": "Raúl",
					"31.12": "Silvestre",
				}';
				$names_array = json_decode($ndjson);
				return $names_array;
			} 	
			public function get_polish_namedays_array()
			{
				$ndjson = '{
					"1.1": "Mieszko, Mieczysław",
					"2.1": "Izydor, Grzegorz",
					"3.1": "Danuta, Zdzisław",
					"4.1": "Elżbieta, Aniela",
					"5.1": "Hanna, Edward, Szymon",
					"6.1": "Kacper, Melchior",
					"7.1": "Lucjan, Julian",
					"8.1": "Seweryn, Juliusz",
					"9.1": "Adrian, Marcelina",
					"10.1": "Danuta, Wilhelm",
					"11.1": "Honorata, Matylda",
					"12.1": "Ada, Benedykt",
					"13.1": "Bogumiła, Weronika",
					"14.1": "Feliks, Nina",
					"15.1": "Paweł, Arnold, Izydor",
					"16.1": "Marcela, Włodzimierz",
					"17.1": "Antoni, Jan",
					"18.1": "Małgorzata, Piotr",
					"19.1": "Henryk, Marta",
					"20.1": "Fabian, Sebastian",
					"21.1": "Agnieszka, Jarosław",
					"22.1": "Anastazy, Wincenty",
					"23.1": "Ildefons, Rajmund",
					"24.1": "Rafał, Felicja, Franciszka",
					"25.1": "Paweł, Miłosz",
					"26.1": "Tymoteusz, Michał",
					"27.1": "Aniela, Jerzy",
					"28.1": "Walery, Karol",
					"29.1": "Franciszek, Józef",
					"30.1": "Maciej, Martyna",
					"31.1": "Jan, Marcela, Ludwika",
					"1.2": "Brygida, Ignacy",
					"2.2": "Maria, Mirosław",
					"3.2": "Błażej, Oskar",
					"4.2": "Andrzej, Józef, Tytus",
					"5.2": "Agata, Adelajda",
					"6.2": "Dorota, Bogdan, Paweł",
					"7.2": "Ryszard, Teodor",
					"8.2": "Hieronim, Sebastian",
					"9.2": "Apolina, Eryka, Cyryl",
					"10.2": "Elwira, Jacek",
					"11.2": "Grzegorz, Lucjan",
					"12.2": "Radosław, Damian",
					"13.2": "Grzegorz, Katarzyna",
					"14.2": "Cyryl, Metody",
					"15.2": "Jowita, Faustyn",
					"16.2": "Danuta, Julian",
					"17.2": "Aleksy, Łukasz",
					"18.2": "Szymon, Konstancja",
					"19.2": "Arnold, Józef, Konrad",
					"20.2": "Leon, Ludomir",
					"21.2": "Robert, Eleonora",
					"22.2": "Marta, Małgorzata",
					"23.2": "Romana, Damian",
					"24.2": "Maciej, Marek",
					"25.2": "Cezary, Donat",
					"26.2": "Mirosław, Aleksander",
					"27.2": "Gabriel, Anastazja",
					"28.2": "Roman, Ludomir",
					"1.3": "Albin, Antoni",
					"2.3": "Helena, Halszka",
					"3.3": "Maryna, Kunegunda",
					"4.3": "Eugeniusz, Kazimierz",
					"5.3": "Adrian, Fryderyk",
					"6.3": "Róża, Wiktor",
					"7.3": "Tomasz, Felicyta",
					"8.3": "Beata, Wincenty",
					"9.3": "Franciszka, Dominika",
					"10.3": "Cyprian, Aleksander",
					"11.3": "Benedykt, Konstantyn",
					"12.3": "Alojzy, Bernard",
					"13.3": "Bożena, Krystyna",
					"14.3": "Leon, Martyna",
					"15.3": "Longin, Klemens",
					"16.3": "Izabela, Oktawia",
					"17.3": "Patryk, Zbigniew",
					"18.3": "Cyryl, Edward",
					"19.3": "Józef, Bogdan",
					"20.3": "Klaudia, Eufemia",
					"21.3": "Ludomir, Benedykt",
					"22.3": "Katarzyna, Bogusław",
					"23.3": "Pelagia, Feliks",
					"24.3": "Marek, Gabriel",
					"25.3": "Mariola, Wienczysław",
					"26.3": "Emanuel, Teodor",
					"27.3": "Lidia, Ernest",
					"28.3": "Aniela, Jan",
					"29.3": "Wiktoryn, Helmut",
					"30.3": "Aniela, Leonard",
					"31.3": "Beniamin, Balbina",
					"1.4": "Grażyna, Irena",
					"2.4": "Wladysław, Franciszka",
					"3.4": "Ryszard, Irena",
					"4.4": "Benedykt, Izydor",
					"5.4": "Katarzyna, Wincenty",
					"6.4": "Izolda, Ireneusz",
					"7.4": "Rufin, Donat",
					"8.4": "Dionizy, Julia",
					"9.4": "Maria, Dymitr",
					"10.4": "Michał, Makary",
					"11.4": "Filip, Leon",
					"12.4": "Damian, Juliusz",
					"13.4": "Przemysław, Ida",
					"14.4": "Berenika, Walerian",
					"15.4": "Ludwina, Wacława",
					"16.4": "Cecylian, Bernadeta",
					"17.4": "Robert, Rudolf",
					"18.4": "Alicja, Bogusław",
					"19.4": "Adolf, Tymon",
					"20.4": "Czesław, Agnieszka",
					"21.4": "Bartosz, Feliks",
					"22.4": "Kazimierz, Łukasz",
					"23.4": "Jerzy, Wojciech, Idzi",
					"24.4": "Aleksy, Horacy",
					"25.4": "Marek, Jarosław",
					"26.4": "Maria, Klaudiusz",
					"27.4": "Ludwik, Piotr",
					"28.4": "Paweł, Waleria",
					"29.4": "Rita, Donata",
					"30.4": "Marian, Katarzyna",
					"1.5": "Józef, Jeremiasz",
					"2.5": "Zygmunt, Atanazy",
					"3.5": "Maria, Mariola",
					"4.5": "Monika, Florian",
					"5.5": "Irena, Waldemar",
					"6.5": "Filip, Judyta",
					"7.5": "Benedykt, Gizela",
					"8.5": "Ilza, Stanisław, Wiktor",
					"9.5": "Bożydar, Grzegorz",
					"10.5": "Izydor, Antoniny",
					"11.5": "Iga, Ignacy",
					"12.5": "Joanna, Achilles",
					"13.5": "Gloria, Gerwazy",
					"14.5": "Bonifacy, Dobiesław",
					"15.5": "Zofia, Nadzieja",
					"16.5": "Andrzej, Jędrzej",
					"17.5": "Brunon, Paschalis",
					"18.5": "Eryk, Feliks",
					"19.5": "Piotr, Iwa",
					"20.5": "Aleksandr, Bazyli",
					"21.5": "Jan, Wiktor",
					"22.5": "Helena, Wiesław",
					"23.5": "Emilia, Iwona",
					"24.5": "Joanna, Zuzanna",
					"25.5": "Borysław, Grzegorz",
					"26.5": "Filip, Paulina",
					"27.5": "Augustyn, Julian",
					"28.5": "Jaromir, Justyna",
					"29.5": "Magdalena, Bogumiła",
					"30.5": "Karol, Ferdynand",
					"31.5": "Aniela, Petronela",
					"1.6": "Jakub, Justyn",
					"2.6": "Erazm, Marianna",
					"3.6": "Leszek, Tamara",
					"4.6": "Franciszka, Karol",
					"5.6": "Bonifacy, Walter",
					"6.6": "Norbert, Laurenty",
					"7.6": "Robert, Wiesław",
					"8.6": "Maksym, Medard",
					"9.6": "Anna, Felicjan",
					"10.6": "Bogumił, Malgorzata",
					"11.6": "Barnaba, Radomił",
					"12.6": "Janina, Jan",
					"13.6": "Lucjan, Antoni",
					"14.6": "Bazyli, Eliza",
					"15.6": "Wit, Jolanta",
					"16.6": "Alina, Benon",
					"17.6": "Albert, Ignacy",
					"18.6": "Mark, Elzbieta",
					"19.6": "Gerwazy, Protazy",
					"20.6": "Dina, Bogna",
					"21.6": "Alicja, Alojzy",
					"22.6": "Paulina, Tomasz",
					"23.6": "Wanda, Zenon",
					"24.6": "Jan, Danuta",
					"25.6": "Lucja, Wilhelm",
					"26.6": "Jan, Paula",
					"27.6": "Maryla, Wladysław",
					"28.6": "Leon, Ireneusz",
					"29.6": "Piotr, Paweł",
					"30.6": "Emilia, Lucyca",
					"1.7": "Halina, Marian",
					"2.7": "Jagoda, Urban",
					"3.7": "Jack, Anatol",
					"4.7": "Malwina, Odon",
					"5.7": "Marii, Antoni",
					"6.7": "Dominika, Gotard",
					"7.7": "Benedykt, Cyryl",
					"8.7": "Adriana, Eugeniusz",
					"9.7": "Lukrecja, Weronika",
					"10.7": "Olaf, Witalis",
					"11.7": "Olga, Kalina",
					"12.7": "Jan, Brunon",
					"13.7": "Ernest, Malgorzata",
					"14.7": "Bonawentura, Stelia",
					"15.7": "Dawid, Henryk",
					"16.7": "Eustachy, Maria",
					"17.7": "Aneta, Bogdan",
					"18.7": "Emil, Erwin",
					"19.7": "Wincenty, Wodzisław",
					"20.7": "Czesław, Fryderyk",
					"21.7": "Daniel, Dalida",
					"22.7": "Maria, Magdalena",
					"23.7": "Bogna, Apolinary",
					"24.7": "Kinga, Krystyna",
					"25.7": "Walentyna, Krzysztof",
					"26.7": "Anna, Mirosława",
					"27.7": "Celestyn, Lilia",
					"28.7": "Aida, Innocenty",
					"29.7": "Olaf, Marta",
					"30.7": "Julita, Piotr",
					"31.7": "Ignacy, Lubomir",
					"1.8": "Alfons, Nadia",
					"2.8": "Karina, Gustaw",
					"3.8": "Lidia, August",
					"4.8": "Dominik, Jan",
					"5.8": "Maria, Oswald",
					"6.8": "Sława, Jakub",
					"7.8": "Klaudia, Kajetan",
					"8.8": "Cyprian, Dominik",
					"9.8": "Roman, Ryszard",
					"10.8": "Bogdan, Borys",
					"11.8": "Klara, Lidia",
					"12.8": "Lech, Euzebia",
					"13.8": "Diana, Hipolit",
					"14.8": "Alfred, Euzebiusz",
					"15.8": "Maria, Napoleon",
					"16.8": "Stefan, Roch",
					"17.8": "Anita, Eliza",
					"18.8": "Ilona, Klara",
					"19.8": "Jan, Bolesław",
					"20.8": "Bernard, Samuel",
					"21.8": "Franciszka, Joanna",
					"22.8": "Maria, Cezary",
					"23.8": "Róża, Apolinary",
					"24.8": "Emilia, Jerzy",
					"25.8": "Luiza, Ludwik",
					"26.8": "Maria, Zefiryna",
					"27.8": "Monika, Cezary",
					"28.8": "Patrycja, Wyszomir",
					"29.8": "Beata, Jan",
					"30.8": "Rebeka, Szczęsna",
					"31.8": "Izabela, Ramona",
					"1.9": "Bronisława, Idzi",
					"2.9": "Julian, Stefan",
					"3.9": "Izabela, Szymon",
					"4.9": "Ida, Lilianna",
					"5.9": "Dorota, Wawrzyniec",
					"6.9": "Beata, Eugeniusz",
					"7.9": "Regina, Melchior",
					"8.9": "Maria, Adriana",
					"9.9": "Piotr, Sergiusz",
					"10.9": "Łukasz, Mikołaj",
					"11.9": "Jacek, Dagna",
					"12.9": "Radzimir, Gwidon",
					"13.9": "Eugenia, Aureliusz",
					"14.9": "Roksana, Bernard",
					"15.9": "Albin, Nikodem",
					"16.9": "Edyta, Kornel",
					"17.9": "Franciszka, Hildegarda",
					"18.9": "Irma, Józef",
					"19.9": "January, Konstancja",
					"20.9": "Filipina, Eustachy",
					"21.9": "Jonasz, Mateusz",
					"22.9": "Tomasz, Maurycy",
					"23.9": "Bogusław, Tekla",
					"24.9": "Gerard, Teodor",
					"25.9": "Aurelia, Ladysław",
					"26.9": "Justyna, Cyprian",
					"27.9": "Damian, Amadeusz",
					"28.9": "Luba, Wacław",
					"29.9": "Michał, Michalina",
					"30.9": "Wera, Honoriusz",
					"1.10": "Danuta, Remigiusz",
					"2.10": "Teofil, Dionizja",
					"3.10": "Teresa, Heliodor",
					"4.10": "Rozalia, Edwin",
					"5.10": "Igor, Flawia",
					"6.10": "Artur, Brunon",
					"7.10": "Maria, Marek",
					"8.10": "Pelagia, Brygida",
					"9.10": "Arnold, Dionizy",
					"10.10": "Paulina, Franciszka",
					"11.10": "Emil, Aldona",
					"12.10": "Eustachy, Maksymilian",
					"13.10": "Gerard, Edward",
					"14.10": "Alan, Kalikst",
					"15.10": "Teresa, Jadwiga",
					"16.10": "Gaweł, Florentyna",
					"17.10": "Małgorzata, Wiktor",
					"18.10": "Juliusz, Łukasz",
					"19.10": "Pelagia, Piotr",
					"20.10": "Irena, Jan",
					"21.10": "Urszula, Hilaria",
					"22.10": "Filip, Kordula",
					"23.10": "Marlena, Seweryn",
					"24.10": "Rafał, Marcin",
					"25.10": "Daria, Wilhelmina",
					"26.10": "Lucjan, Ewaryst",
					"27.10": "Iwona, Sabina",
					"28.10": "Szymon, Tadeusz",
					"29.10": "Euzebia, Wioletta",
					"30.10": "Zenobia, Przemysław",
					"31.10": "Urban, Saturnin",
					"1.11": "Julian, Łukasz",
					"2.11": "Bohdana, Tobiasz",
					"3.11": "Sylwia, Hubert",
					"4.11": "Karol, Olgierd",
					"5.11": "Elżbieta, Sławomir",
					"6.11": "Feliks, Leonard",
					"7.11": "Antoni, Zytomir",
					"8.11": "Sewer, Hadriana",
					"9.11": "Ursyn, Todor",
					"10.11": "Lena, Ludomir",
					"11.11": "Marcin, Bartłomiej",
					"12.11": "Renata, Witold",
					"13.11": "Mikołaj, Stanisław",
					"14.11": "Roger, Serafina",
					"15.11": "Albert, Leopold",
					"16.11": "Gertruda, Edmund",
					"17.11": "Grzegorz, Salomea",
					"18.11": "Roman, Klaudyna",
					"19.11": "Elżbieta, Seweryn",
					"20.11": "Anatol, Sędzimir",
					"21.11": "Janusz, Konrad",
					"22.11": "Marek, Cecylia",
					"23.11": "Adela, Klemens",
					"24.11": "Flora, Emma",
					"25.11": "Katarzyna, Erazm",
					"26.11": "Delfina, Sylwester",
					"27.11": "Walery, Wilgiusz",
					"28.11": "Lesław, Zdzisław",
					"29.11": "Błażej, Saturnin",
					"30.11": "Maura, Andrzej",
					"1.12": "Natalia, Eligiusz",
					"2.12": "Balbina, Bibiana",
					"3.12": "Franciszka, Ksawery",
					"4.12": "Barbara, Krystian",
					"5.12": "Saba, Kryspin",
					"6.12": "Mikołaj, Jarema",
					"7.12": "Marcin, Ambroża",
					"8.12": "Maria, Świątożar",
					"9.12": "Wiesław, Leokadia",
					"10.12": "Julia, Daniela",
					"11.12": "Damazy, Waldemar",
					"12.12": "Dagmara, Aleksandra",
					"13.12": "Lucja, Otylia",
					"14.12": "Alfred, Izydor",
					"15.12": "Nina, Celina",
					"16.12": "Albina, Zdzisław",
					"17.12": "Olimpia, Łazarz",
					"18.12": "Gracjan, Bogusław",
					"19.12": "Gabriela, Dariusz",
					"20.12": "Bogumiła, Dominika",
					"21.12": "Tomasz, Tomisław",
					"22.12": "Zenon, Honorata",
					"23.12": "Wiktoria, Sławomira",
					"24.12": "Adam, Ewa",
					"25.12": "Anastazja, Eulalia",
					"26.12": "Jana, Żaneta",
					"27.12": "Teofila, Godzisław",
					"28.12": "Jana, Maksym",
					"29.12": "Dawid, Tomasz",
					"30.12": "Irmina, Eugeniusz",
					"31.12": "Melania, Sylwester",
				}';
				$names_array = json_decode($ndjson);
				return $names_array;
			} 					
			public function get_csv_string(){
				$str = "01-01;Manuel, Emanuel, Jesús
01-02;Gregorio, Astrid, Basilio, Emma
01-03;Daniel, Genova, Genoveva, Jennifer
01-04;Eugenio
01-05;Amada, Simón, Simona, Emiliana
01-06;Baltasar, Gaspar, Reyes, Adoración
01-07;Amadeo, Raimundo, Aquiles, Luciano
01-08;Maximino, Eladio
01-09;Julián, Pedro Urseolo
01-10;Gonzalo, Marciano, Alda, Aldo
01-11;Alejandro, Guillermo, Hortensia
01-12;Alfredo, Tatiana, Tania, Hilario
01-13;Verónica, Gumersindo, Milagros
01-14;Félix, Gil
01-15;Mauro, Raquel, Marcelo
01-16;Odette, Oto, Priscila
01-17;Alba, Antonio, Mariana, Alfredo
01-18;Florida, Beatriz, Mario, Pia
01-19;Mario, Vicente, Sebastián
01-20;Fabián
01-21;Vicente
01-22;Domingo, Imanol, Emma, Gaudencio
01-23;Alberto, Ildefonso, Alberta
01-24;Francisco, Tirso, Paz, Feliciano
01-25;Elvira, Paula, Timoteo
01-26;Paula, Tito, Gonzalo
01-27;Ángela, Tomás, Valerio
01-28;Tomas, Pedro Nolasco
01-29;Valeria, Valerio, Martina
01-30;Alejandro
01-31;Juan Bosco
02-01;Cecilio
02-02;Catalina, Aída, Felipe, Ayuda
02-03;Oscar, Blas, Adelina
02-04;Gilberto, Isidro, Verónica, Juana
02-05;Isaac, Ágata, Águeda
02-06;Gonzalo, Amando, Amanda, Silvano
02-07;Moisés, Ricardo
02-08;Jerónimo, Lucio, Elisanda
02-09;Donato, Sabino, Reinaldo, Apolonia
02-10;Guillermo, Amancio, Arnaldo, Arnau
02-11;Dante, Lourdes, Adolfo
02-12;Modesto, Eulalia
02-13;Cristian, Benigno
02-14;Dionisio, Valentín, Valentina
02-15;Georgia, Georgina, Faustino
02-16;Elías, Samuel, Isaías, Jeremías
02-17;Constanza, Rómulo, Alexis
02-18;Lucio, Simeón
02-19;Álvaro, Conrado, Almudina, Gabino
02-20;Eleuterio
02-21;Irene, Pedro Damián
02-22;Margarita, Leonor
02-23;Lázaro, Romance, Policarpo
02-24;Modesto
02-25;Cesáreo, Dióscoro
02-26;Néstor
02-27;Gabriel, Gabriela, Baldomero
02-28;Román, Leandro, Romano
02-29;
03-01;Federico, Rosendo, Eudoxia
03-02;Enrique, Pablo, Enriqueta
03-03;Medín, Rosendo
03-04;Francisca, Arcadio, Eugenio
03-05;Juan José
03-06;Humberto, Olegario, Judith, Nina
03-07;Clotilde, Felicidad
03-08;Juan
03-09;Cándido, Francisca
03-10;Andrés, Macario
03-11;Ramiro, Oria
03-12;Josefina, Maximiliano, Fina
03-13;Patricia, Rodrigo, Ramiro
03-14;Jacobo, Matilde, Florentina
03-15;César, Luis, Raimundo, Madrona
03-16;Abrahan, Clemente
03-17;Patricio
03-18;Narciso, Salvador
03-19;José, Marcos, Josefa
03-20;Alejandra, Claudia
03-21;Clemencia, Fabiola, Nicolás
03-22;Sergio, Octaviano
03-23;Fidel, Oriol, Victoriano, Toribio
03-24;Delmiro, Edelmira, Edelmiro, Timolao
03-25;Abel, Gloria, Encarnación, Rebeca
03-26;Braulio, Diego
03-27;Ruperto, Lilia, Alejandro
03-28;Esperanza, Gundelina
03-29;Jonas, Segundo
03-30;Quirino
03-31;Amós, Benjamín
04-01;Venancio
04-02;Ofelia, Francisco
04-03;Sixto
04-04;Isidoro, Platón
04-05;Emilia, Vicente Ferrer
04-06;Celso, Diógenes
04-07;Donato, Juan Bautista
04-08;Dionisio, Amancio
04-09;Hugo, Casilda, Eusequio
04-10;Ezequiel
04-11;Gema, Oria, Estanislao
04-12;Andrés, Damián, Julio, Zenón
04-13;Martín, Hermenegildo
04-14;Lamberto
04-15;Máximo, Aníbal
04-16;Engracia, Bernadeta
04-17;Rodolfo, Anicéto
04-18;Perfecto
04-19;León, Crescencio
04-20;Inés, Víctor
04-21;Anselmo
04-22;Teodoro, Alexander, Apeles
04-23;Adalberto, Jorge, Gorka
04-24;Leoncio, Honorio, Honoria, Fidel
04-25;Antonio, Antonieta, Marco, Marcia
04-26;Basilio, Marcelino, Engracia, Isidoro
04-27;Montserrat, Zita
04-28;Amado, Pedro Chanel
04-29;Teodora, Karen, Katia, Wilfredo
04-30;Jaime, Amador, Pía, Pío
05-01;Berta, Tamar, Tamara, Oroncio
05-02;Germán, Araceli, Atanasio, Vindemial
05-03;Juvenal, Violeta, Evencio, Felipe
05-04;Florián, Froilán, Lidón, Silvano
05-05;Adrián, Silvano, Niceto, Ángelica
05-06;Domingo, Evodio, Protógenes, Judith
05-07;Augusto, Flavio, Gisela
05-08;Acacio
05-09;Gregorio, Hermas, Geroncio
05-10;Job, Solange, Gordiano
05-11;Estela, Favio, Amparo, Poncio
05-12;Domingo, Nerea, Nereo, Aquileo
05-13;Imelda, Fátima
05-14;Matías, Corona, Cora, Henedina
05-15;Cecilio, Eufrasia, Isidro, Torcuato
05-16;Brenda, Ubaldo, Honorato
05-17;Eric, Erica, Pascual
05-18;Alejandra, Félix, Próspero
05-19;Celestina, Celestino, Crispín
05-20;Orlando, Baudilio, Asterio
05-21;Constantino, Virginia, Giselle
05-22;Emilio, Rita, Rosana
05-23;Miguel, Mercurial, Eufebio
05-24;Rocío, Susana, Auxiliadora
05-25;Valentín, Valentina, Sonia
05-26;Felipe Neri, Zacarías
05-27;Carolina
05-28;Agustín, Bernardo, Emilio, Germán
05-29;Alejandro, Justo, Teodosia
05-30;Fernando, Estela, Fernanda, Hernán
05-31;Visitación, Petronila, Amelia
06-01;Alta, Graciano, Laura, Candelaria
06-02;Erasmo, Marcelino, Blandina
06-03;Oliva, Kevin, Cecilio, Davino
06-04;Emma, Quirino, Ruth, Saturnina
06-05;Eloisa, Marcia, Valeria, Nicanor
06-06;Norberto, Artemio, Cándida, Ismael
06-07;Roberto
06-08;Giraldo
06-09;Blanca, Primo, Feliciano, Diana
06-10;Amalia, Amelia, Getulio, Críspulo
06-11;Benito, Bernabé, Aléida
06-12;Nazario, Olimpo, Cirilo
06-13;Antonio, Joel, Andoni
06-14;Félix, Eliseo, Digna
06-15;Lidia, Vito, Landelino, Libia
06-16;Ciro, Aquilino, Aureliano, Siro
06-17;Ismael, Isauro, Montano
06-18;Justo, Marceliano, Marina
06-19;Aurora
06-20;Elia, Silverio, Macario
06-21;Luis, Demetria, Terencio, Raul, Gina
06-22;Albano, Paulino
06-23;Alicia, Apolo, Inmaculada, Agripina
06-24;Juan, Juana, Ivana, Joan
06-25;Salomón, Guillermo
06-26;Virgilio, Pelayo, Antelmo, Alicia
06-27;Socorro, Zoilo, Ladislao, Anecto
06-28;Marcela
06-29;Ciro, David, Pablo, Pedro
06-30;Marcial, Leonila
07-01;Aarón, Esther, Luz
07-02;Visitación, Martiniano, Vidal
07-03;Tomás, Heliodoro, Jacinto, Enrique
07-04;Berta, Elizabeth, Laureano, Isabel
07-05;Filomena, Filomeno, Zoa
07-06;Isaías, Dominica, Rómulo
07-07;Fermín, Roberto, Odón, Germano
07-08;Adrián, Edgar, Marina, Priscila
07-09;Milagros, Verónica
07-10;Cristóbal, Silvano, Honorato
07-11;Benito, Olga, Abundio, Sabino
07-12;Paulina, Oliverio
07-13;Eugenio, Sara, Joel
07-14;Camila, Vladimiro, Camilo
07-15;Carmelo, Hilario, Fausto
07-16;Carmen, Marcelina, Generosa
07-17;Elías
07-18;Emiliano, Federico, Luz
07-19;Aurea, Aureo
07-20;Elías, Elisa
07-21;Angelina, Lorenza, Daniel, Julia
07-22;Teófila, Zoraida, Magdalena, Primitiva
07-23;Brigida, Teresa, Boris
07-24;Cristina
07-25;Jaime, Santiago
07-26;Ana, Joaquín
07-27;Cucufate, Natalia
07-28;Celso
07-29;Marta, Olavo
07-30;Abdón
07-31;Ignacio
08-01;Alfonso, Dalmau
08-02;Angeles, Eusebio.
08-03;Gustavo, Lídia
08-04;Juan María Vianney
08-05;Africa, Blanca, Nieves
08-06;Salvador
08-07;Cayetano
08-08;Domingo
08-09;-
08-10;Lorenzo
08-11;Clara, Filomena, Susana
08-12;Herculano
08-13;Aurora, Hipólito
08-14;Atanasia
08-15;Asunción, Estrella, María, Paloma
08-16;Roque
08-17;Isaac, Jacinto
08-18;Elena
08-19;Magín
08-20;Bernardo Abad
08-21;Sidonio
08-22;Reina
08-23;Rosa
08-24;Bartolomé
08-25;Ginés
08-26;Ceferino
08-27;Mónica
08-28;Agustín
08-29;Sabina
08-30;Gaudencia
08-31;Raimón, Ramón
09-01;Arturo, Egidio, Gil
09-02;Raquel, Antolín
09-03;Dorotea
09-04;Moisés, Rosalía
09-05;Eudosio
09-06;Eva, Fausto
09-07;Regina
09-08;Adela, Meritxell, Nuria
09-09;Claustro, Felicia
09-10;Nicolás
09-11;Patiens
09-12;Dulce, María
09-13;Juan Crisóstomo
09-14;Exaltación
09-15;Aurora, Dolores, Mar
09-16;Rogelio
09-17;Ariadna, Columba, Roberto
09-18;Sofía
09-19;Nilo
09-20;Eustaquio
09-21;Mateo, Mauricio
09-22;Digna, Inocencio
09-23;Tecla, Lina, Lino
09-24;Gerardo, Mercedes
09-25;Dalmacio
09-26;Cosme, Damián
09-27;Florentino, Vicente
09-28;Wenceslao
09-29;Gabriel, Miguel, Rafael
09-30;Jerónimo
10-01;Teresa
10-02;Angeles Custodios
10-03;Francisco, Cándido
10-04;Francisco
10-05;Gala, Plácido
10-06;Bruno
10-07;Rosario
10-08;Salud, Thaís
10-09;Abrahan, Dionisio
10-10;Tomás
10-11;Begona
10-12;Pilar, Serafín
10-13;Eduardo
10-14;Calixto
10-15;Teresa
10-16;Margarita, María Alacoque
10-17;Ignacio
10-18;Lucas
10-19;Laura
10-20;Academia, Irene
10-21;Griselda, Ursula
10-22;Salomé
10-23;Servando
10-24;Antonio María Claret
10-25;Bernardo Calvó
10-26;Evaristo
10-27;Capitolina
10-28;Judas, Simón, Tadeo
10-29;Narciso
10-30;Bienvenida, Claudio
10-31;Quintin
11-01;Benigno, Penélope
11-02;Jorge, Gorka
11-03;Ermengol, Silvia
11-04;Carlos, Carlota, Carolina
11-05;Zacarías, Elisabet, Isabel
11-06;Leonardo
11-07;Carina, Ernesto
11-08;Severiano
11-09;Teodoro
11-10;Almudena, León
11-11;Martín
11-12;Aurelio
11-13;Leandro, Diego
11-14;Teodoto, Clemente
11-15;Alberto, Leopoldo
11-16;Edmundo, Margarita
11-17;Gertrudis, Hilda, Isabel, Victoria
11-18;Aurelio
11-19;Crispino, Fausto
11-20;Félix, Lucrecia, Ocatavio
11-21;Demetrio, Fructuoso, Piedad
11-22;Cecilia
11-23;Clemente
11-24;Flora
11-25;Erasmo
11-26;Juan
11-27;Auxilio
11-28;Rufo
11-29;Saturnino
11-30;Andrés
12-01;Adelaida, Eloy, Hugo
12-02;Elisa, Elsa
12-03;Francisco Javier, María
12-04;Bárbara
12-05;Crispina
12-06;Nicolás
12-07;Ambrosio
12-08;Concepción, Inmaculada, Pura
12-09;Juan Diego
12-10;Eulalia
12-11;Dámaso
12-12;Chantal, Guadalupe
12-13;Lucía
12-14;Juan, Nicasio, Pompeyo
12-15;Fortunato, Cristina
12-16;Albina
12-17;Lázaro, Yolanda
12-18;Esperanza, Macarena
12-19;Darío
12-20;Ptolomeo
12-21;Pedro Canisio
12-22;Floro
12-23;Juan
12-24;Delfín, Társila
12-25;Belén, Eugenia, Natividad
12-26;Esteban
12-27;Teófanos
12-28;Abel
12-29;Davíd
12-30;Raúl
12-31;Silvestre
";

return $str;
			}
}


?>